datacenter: dc1

region: yxl

cluster:
  name: k8s
  domain: cluster.local

terraform:
  enabled: true

  lab:
    enabled: true

tiering:
  enabled: false
  storageClass: 'ssd-storage'
  size: '10Gi'

snapshots:
  storageClass: 'ssd-storage'
  size: '10Gi'

rollout:
  newReplicaStabilizationSeconds: 300
