apiVersion: v2
version: 1.0.0

name: development-core

dependencies:
  - name: artifact-hub
    version: '>= 1.17.0'
    repository: https://artifacthub.github.io/helm-charts/
    condition: artifact-hub.enabled

  - name: gitlab
    version: '9.5.1'
    repository: https://charts.gitlab.io/
    condition: gitlab.enabled

  - name: harbor
    version: 1.18.2
    repository: https://helm.goharbor.io
    condition: harbor.enabled

  - name: renovate
    version: '>= 37.183.0'
    repository: https://docs.renovatebot.com/helm-charts
    condition: renovate.enabled

  - name: hoppscotch
    version: '>= 0.3.1'
    repository: oci://ghcr.io/deliveryhero/helm-charts
    condition: hoppscotch.enabled

  - name: common
    version: '3.7.1'
    repository: https://bjw-s-labs.github.io/helm-charts/
