{{- if .Values.che.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: 'che-codex-activity'
  namespace: 'eclipse-che'
  labels:
    app.kubernetes.io/part-of: 'che.eclipse.org'
    app.kubernetes.io/component: 'workspaces-config'
  annotations:
    controller.devfile.io/mount-as: 'subpath'
    controller.devfile.io/mount-path: '/home/user'
    controller.devfile.io/mount-on-start: 'true'
data:
  .noidle: |
    watchedCommands:
      - name: 'codex'
        interactive: false
{{- end }}
