apiVersion: v2
version: 1.0.0

appVersion: 0.1.0

name: backups-core

dependencies:
  - name: common
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts/
  - name: velero
    version: 5.2.1
    repository: https://vmware-tanzu.github.io/helm-charts/

