apiVersion: resolvemy.host/v1alpha1
kind: ClusterNode
metadata:
  name: hpc2.home1.yvr.resolvemy.host

  namespace: core-prod

  labels:
    argocd.argoproj.io/instance: dc1-k3s-node1-ops-cluster

spec:
  name: hpc2.home1.yvr.resolvemy.host

  description: home1.yvr.resolvemy.host Desktop PC Gaming Desktop

  type: controlplane

  danger:
    warningdonotdounlessyouknowwhatyouaredoing:
      wipeOnReboot: false

  clusterRef:
    group: resolvemy.host
    kind: Cluster
    name: core-home1-talos
    namespace: core-prod

  tenantRef:
    group: mylogin.space
    kind: Tenant
    name: core.mylogin.space
    namespace: core-prod

  environment: prod

  bgp:
    instances:
      - asn: 64512
        name: wan-gw
        port: 1176
        type: cilium
        peers:
          - address: 2604:3D08:D174:2000::1C
            asn: 64567
            localAddress: 2604:3d08:d174:2000::11
            name: ipv6.cpe-sw1.home2.yvr.resolvemy.host

  networking:
    dns:
      servers:
        - 10.1.1.53
        - 172.31.193.254

  networks:
    - addresses:
        - 172.31.193.11/24
        - 2604:3d08:d174:2000::11/122
      bridge: true
      dns:
        - 1.1.1.1
        - 1.0.0.1
        - 8.8.8.8
      macAddress: e0:d5:5e:65:02:d7
      members:
        - macAddress: e0:d5:5e:65:02:d7
      model: new
      mtu: 9000
      routes:
        - gateway: 172.31.193.254
          metric: 600
          network: 0.0.0.0/0

        - gateway: 2604:3D08:D174:2000::1C
          metric: 600
          network: '::/0'
      routing:
        ospf:
          area: 0.0.0.0
          enabled: true
          type: broadcast
      static: true
      stp:
        enabled: false
      type: bridge

    - macAddress: e0:d5:5e:65:02:d9
      type: bridge
      bridge: true

      stp:
        enabled: false

      members:
        - macAddress: e0:d5:5e:65:02:d9

      addresses:
        - 172.31.193.12/24
        - 2604:3d08:d174:2000::12/122

      model: new

      dns:
        - 1.1.1.1
        - 8.8.8.8

      mtu: 9000

      routes: []

      routing:
        ospf:
          area: 0.0.0.0
          enabled: true
          type: broadcast

      static: true
      vlans:
        - vlanID: 150

    - addresses:
        - 172.31.241.14/30
      bridge: true
      model: legacy
      dns:
        - 1.1.1.1
        - 8.8.8.8
      macAddress: 00:e0:ed:9d:b8:02
      mtu: 9000
      static: true
      routing:
        bgp:
          enabled: true
      vlans:
        - vlanID: 150

  sysctls:
    - name: net.core.bpf_jit_harden
      value: '1'

    - name: net.ipv6.conf.br2.accept_ra_defrtr
      value: '0'

    - name: net.ipv6.conf.br0.accept_ra
      value: '2'

    - name: net.ipv6.conf.br1.accept_ra
      value: '2'

    - name: net.ipv4.tcp_max_syn_backlog
      value: '262144'

  overrides:
    kernel:
      parameters:
        - name: cpufreq.default_governor
          value: performance

        - name: intel_iommu
          value: 'on'

        - name: iommu
          value: pt

        - name: intel_pstate
          value: active

        - name: pcie_aspm
          value: 'off'

        - name: nvme_core.default_ps_max_latency_us
          value: '0'

        - name: intel_idle.max_cstate
          value: '0'

        - name: processor.max_cstate
          value: '1'
    talos:
      extensions:
        system:
          - intel-ucode
          - i915
          - nvidia-container-toolkit-lts
          - nonfree-kmod-nvidia-lts
          - thunderbolt
          - intel-ice-firmware
          - nfsd
          - multipath-tools
          - mdadm
          - ctr
          - nfsrahead
          - uinput
          - nvme-cli
          - usb-audio-drivers
      kernel:
        modules:
          - name: nvidia

          - name: nvidia_uvm

          - name: nvidia_drm

          - name: nvidia_modeset

          - name: dm_multipath
          - name: dm_round-robin