apiVersion: resolvemy.host/v1alpha1
kind: ClusterNode
metadata:
  name: hpc3.home1.yvr.resolvemy.host

  namespace: core-prod

  labels:
    argocd.argoproj.io/instance: dc1-k3s-node1-ops-cluster

spec:
  name: hpc3.home1.yvr.resolvemy.host

  description: home1.yvr.resolvemy.host iMac

  type: worker

  danger:
    warningdonotdounlessyouknowwhatyouaredoing:
      wipeOnReboot: false

  clusterRef:
    group: resolvemy.host
    kind: Cluster
    name: core-home1-talos
    namespace: core-prod

  tenantRef:
    group: mylogin.space
    kind: Tenant
    name: core.mylogin.space
    namespace: core-prod

  environment: prod

  bgp:
    instances:
      - asn: 64512
        name: wan-gw
        type: cilium
        peers:
          - address: 172.31.193.16
            asn: 64567
            name: cpe-sw1.home1.yvr.resolvemy.host

  networks:
    - macAddress: 38:c9:86:42:ff:90
      bridge: true

      addresses:
        - 172.31.193.21/24

      routes:
        - network: 0.0.0.0/0
          gateway: 172.31.193.254
          metric: 1024

      mtu: 9000
      routing:
        ospf:
          area: 0.0.0.0
          enabled: true
          type: broadcast

      static: true
      dns:
        - 1.1.1.1
        - 1.0.0.1
        - 8.8.8.8
      vlans:
        - vlanID: 150

    - macAddress: 00:30:93:0c:05:12
      bridge: true

      addresses:
        - 172.31.193.22/24

      routes:
        - gateway: 172.31.193.254
          metric: 1024
          network: 0.0.0.0/0

      mtu: 9000
      routing:
        ospf:
          area: 0.0.0.0
          enabled: true
          type: broadcast

      vlans:
        - vlanID: 150

      static: true
      dns:
        - 1.1.1.1
        - 1.0.0.1
        - 8.8.8.8

    - addresses:
        - 172.31.241.26/30
      bridge: true
      dns:
        - 1.1.1.1
        - 1.0.0.1
        - 8.8.8.8
      macAddress: 00:30:93:0c:05:13
      mtu: 9000
      routes: []
      static: true
      routing:
        bgp:
          enabled: true

  overrides:
    kernel:
      parameters:
        - name: intel_iommu
          value: 'on'
        - name: iommu
          value: pt
        - name: video
          value: efifb:off
        - name: vfio-pci.ids
          value: 1002:6920,1002:aad8

    pci:
      rebinds:
        - description: AMD GPU
          id: 0000:01:00.0
          driver: vfio-pci

        - description: AMD GPU
          id: 0000:01:00.1
          driver: vfio-pci

        - description: WiFi Card
          id: 0000:03:00.0
          driver: vfio-pci

    talos:
      kernel:
        modules:
          - name: vfio-pci
          - name: dm_multipath
          - name: dm_round-robin
          - name: snd-usb-audio

      extensions:
        system:
          - intel-ucode
          - thunderbolt
          - amdgpu
          - nfsd
          - multipath-tools
          - mdadm
          - ctr
          - nfsrahead
          - uinput
          - nvme-cli
          - usb-audio-drivers
