

apiVersion: resolvemy.host/v1alpha1
kind: ClusterNode
metadata:
  name: laptop2.home1.yvr.resolvemy.host

  namespace: core-prod

  labels:
    argocd.argoproj.io/instance: dc1-k3s-node1-ops-cluster

spec:
  name: laptop2.home1.yvr.resolvemy.host

  description: home1.yvr.resolvemy.host XPS 9310

  danger:
    warningdonotdounlessyouknowwhatyouaredoing:
      wipeOnReboot: false

  type: worker

  clusterRef:
    group: resolvemy.host
    kind: Cluster
    name: core-home1-talos
    namespace: core-prod

  tenantRef:
    group: mylogin.space
    kind: Tenant
    name: core.mylogin.space
    namespace: core-prod

  environment: prod

  bgp:
    instances:
      - asn: 64512
        name: wan-gw
        peers:
          - address: 172.31.193.3
            asn: 64567
            name: wan-gw2.home2.yvr.resolvemy.host

          - address: 172.31.193.16
            asn: 64567
            name: cpe-sw1.home1.yvr.resolvemy.host

  nics:
    - macAddress: 00:e0:4c:79:61:d1

  networks:
    - macAddress: 00:e0:4c:79:61:d1
      bridge: true
      addresses:
        - 172.31.193.14/24

      routes:
        - network: 0.0.0.0/0
          gateway: 172.31.193.254
          metric: 600

      mtu: 9000

      model: new

      routing:
        ospf:
          area: 0.0.0.0
          enabled: true

      static: true
      dns:
        - 1.1.1.1
        - 1.0.0.1
        - 8.8.8.8

  watchdog:
    enabled: false

    devicePath: /dev/watchdog0

    timeout: 5m

  overrides:
    kernel:
      parameters:
        - name: intel_iommu
          value: 'on'

        - name: iommu
          value: 'pt'

        - name: i915.enable_guc
          value: '3'

        - name: i915.max_vfs
          value: '7'

    talos:
      extensions:
        system:
          - intel-ucode
          - i915
          - thunderbolt