apiVersion: resolvemy.host/v1alpha1
kind: ClusterNode
metadata:
  name: srv3.home1.yvr.resolvemy.host

  namespace: core-prod

spec:
  name: srv3.home1.yvr.resolvemy.host

  description: home2.yvr.resolvemy.host Rack mount server3

  type: worker

  danger:
    warningdonotdounlessyouknowwhatyouaredoing:
      wipeOnReboot: false

  clusterRef:
    group: resolvemy.host
    kind: Cluster
    name: core-home1-talos
    namespace: core-prod

  tenantRef:
    group: mylogin.space
    kind: Tenant
    name: core.mylogin.space
    namespace: core-prod

  environment: prod

  bgp:
    instances:
      - asn: 64512
        name: wan-gw
        type: cilium
        peers:
          - address: 172.31.193.16
            asn: 64567
            localAddress: 172.31.193.37
            name: cpe-sw1.home1.yvr.resolvemy.host

          - address: 2604:3d08:d174:2000::1C
            asn: 64567
            localAddress: 2604:3d08:d174:2000::25
            name: ipv6.cpe-sw1.home1.yvr.resolvemy.host

  networks:
    - macAddress: ec:f4:bb:ef:58:e8
      bridge: false
      model: new
      type: link


      addresses:
        - 172.31.193.37/24
        - 2604:3d08:d174:2000::25/122

      routing:
        ospf:
          enabled: false

          area: '0.0.0.0'

          type: broadcast

      routes:
        - network: 0.0.0.0/0
          gateway: 172.31.193.254
          metric: 1024

        - network: '::/0'
          gateway: 2604:3d08:d174:2000::1C
          metric: 600

      mtu: 9000

      static: true
      dns:
        - 172.31.193.254
        - 172.31.193.2
        - 172.31.193.3

    - addresses: []
      bridge: false
      dns:
        - 1.1.1.1
        - 1.0.0.1
        - 8.8.8.8
      macAddress: ec:f4:bb:ef:58:ea
      model: new
      mtu: 9000
      routing:
        ospf:
          area: 0.0.0.0
          enabled: false
          type: broadcast
      static: true
      type: link

  nics:
    - macAddress: ec:f4:bb:ef:58:e8
      rings:
        rx: 4096
        tx: 4096

  overrides:
    pci:
      rebinds:
        - description: eno2
          id: 0000:01:10.1
          driver: vfio-pci

    kernel:
      parameters:
        - name: intel_iommu
          value: 'on'

        - name: iommu
          value: pt

        - name: cpufreq.default_governor
          value: performance

        - name: numa_balancing
          value: enable
    talos:
      extensions:
        system:
          - intel-ucode
          - nfsd

  sysfs:
    - name: class.net.eno2.device.sriov_numvfs
      value: '4'