{{- if .Values.networks.rogers.enabled }}
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: rogers-network
  annotations:
    k8s.v1.cni.cncf.io/resourceName: {{ required "networks.rogers.sriov.device is required when the Rogers network is enabled" .Values.networks.rogers.sriov.device | squote }}
spec:
  config: |
    {{ dict "cniVersion" "1.0.0" "name" "rogers-net" "type" "sriov" "vlan" .Values.networks.rogers.sriov.vlan "spoofchk" "off" | toJson }}
{{- end }}
