
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-test-vms
  namespace: argocd

spec:
  goTemplate: true
  # goTemplateOptions:
  #   - 'missingkey=error'
  generators:
    - merge:
        mergeKeys:
          - name

        generators:
          - list:
              elements:
                - name: dc1-k3s-node1
                  values:
                    installing: false
                    networks:
                      - name: nic1-backend951
                        vlan: 951
                        mtu: 9216
                        sriov:
                          device: intel.com/intel_xxv710
                      - name: nic2-backend953
                        type: sriov
                        vlan: 953
                        mtu: 9216
                        sriov:
                          device: intel.com/intel_xxv710
                      - name: nic1-conntrack-sync
                        type: sriov
                        vlan: 1500
                        mtu: 1500
                        sriov:
                          device: intel.com/intel_xxv710
                    vms:
                      - disk:
                          enabled: true
                          size: 5Gi
                        installing: false
                        name: wan-rt1
                        networks:
                          - name: nic1-backend951
                            macAddress: 02:09:51:00:00:01
                          - name: nic2-backend953
                          - name: nic1-conntrack-sync
                        podNetwork:
                          enabled: false

                - name: core-dc1-talos-prod
                  values:
                    installing: true

                    vms:
                      - name: wan-rt2
                        installing: false

                        podNetwork:
                          enabled: false
                        
                        disk:
                          enabled: true

                          size: 5Gi

                        networks:
                          - name: intel-nic1-backend953
                            macAddress: 02:09:53:01:03:01

                          - name: intel-nic2-conntrack-sync
                            macAddress: 02:15:00:01:03:01

                      - name: wan-rt1
                        installing: false

                        podNetwork:
                          enabled: false
                        disk:
                          enabled: true

                          size: 5Gi

                        networks:
                          - name: mlx3-nic2-backend951

                          - name: mlx3-nic2-backend953

                          - name: mlx3-nic2-conntrack-sync

                    networks:
                      - name: mlx3-nic2-backend951
                        vlan: 951
                        mtu: 9216
                        sriov:
                          device: mellanox.com/mlx4_cx3_vfio

                      - name: mlx3-nic2-backend953
                        vlan: 953
                        mtu: 9216
                        sriov:
                          device: mellanox.com/mlx4_cx3_vfio

                      - name: mlx3-nic2-conntrack-sync
                        vlan: 1500
                        mtu: 9000
                        sriov:
                          device: mellanox.com/mlx4_cx3_vfio

                      - name: intel-nic1-backend951
                        vlan: 951
                        mtu: 9216
                        sriov:
                          device: intel.com/intel_i350_vfio

                      - name: intel-nic2-backend953
                        vlan: 951
                        mtu: 9216
                        sriov:
                          device: intel.com/intel_i350_vfio

                      - name: intel-nic2-conntrack-sync
                        vlan: 1500
                        mtu: 9000
                        sriov:
                          device: intel.com/intel_i350_vfio

                - name: core-home1-talos-prod
                  values:
                    installing: false

                    wan: true

          - clusters:
              selector:
                matchLabels:
                  mylogin.space/tenant: 'core.mylogin.space'
                  resolvemy.host/computetype: 'baremetal'
              values:
                clusterName: '{{ .name }}'
                environment: 'testing'
                clusterDomain: '{{ index .metadata.labels "cluster.kubernetes.io/domain" }}'
                tenant: '{{ index .metadata.labels "mylogin.space/tenant" }}'

  syncPolicy:
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: '{{ .values.clusterName }}-lab-vms'

      annotations:
        argocd.argoproj.io/manifest-generate-paths: .

    spec:
      project: core

      syncPolicy:
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true

      source:
        path: Lab/VMs
        repoURL: https://github.com/K-FOSS/CoRE-Backplane.git
        targetRevision: HEAD
        plugin:
          name: argocd-lovely-plugin
          env:
            - name: LOVELY_HELM_MERGE
              value: |- # yaml
                env: {{ .values.environment }}

                installing: {{ .values.installing }}

                {{- if .values.vms }}
                vms:
                {{ nindent 2 (toYaml .values.vms) }}
                {{- end }}
                
                {{- if .values.networks }}
                networks:
                {{ nindent 2 (toYaml .values.networks) }}
                {{- end }}

      destination:
        server: '{{ .server }}'
        namespace: core-{{ .values.environment }}

