
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-test-vms
  namespace: argocd

spec:
  goTemplate: true
  # goTemplateOptions:
  #   - 'missingkey=error'
  generators:
    - merge:
        mergeKeys:
          - name

        generators:
          - list:
              elements:
                - name: dc1-k3s-node1
                  values:
                    networks:
                      - name: nic1-backend951
                        vlan: 951
                        mtu: 9216
                        sriov:
                          device: intel.com/intel_xxv710_vfio_port0
                      - name: nic2-backend953
                        type: sriov
                        vlan: 953
                        mtu: 9216
                        sriov:
                          device: intel.com/intel_xxv710_vfio_port1
                      - name: nic1-conntrack-sync
                        type: sriov
                        vlan: 1500
                        mtu: 1500
                        sriov:
                          device: intel.com/intel_xxv710_vfio_port0
                    vms:
                      - disk:
                          enabled: true
                          size: 5Gi
                        installing: false
                        name: wan-rt1
                        networks:
                          - name: nic1-backend951
                            macAddress: 02:09:51:00:00:01
                          - name: nic2-backend953
                            macAddress: 02:09:53:00:00:01
                          - name: nic1-conntrack-sync
                            macAddress: 02:15:00:00:00:01
                        podNetwork:
                          enabled: false

                - name: core-dc1-talos-prod
                  values:
                    installers:
                      - name: vyos
                        url: https://github.com/vyos/vyos-nightly-build/releases/download/2026.07.11-0033-rolling/vyos-2026.07.11-0033-rolling-generic-amd64.iso
                        size: 30Gi

                      - name: debian
                        url: https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-13.6.0-amd64-netinst.iso
                        size: 2Gi

                      - name: flatcar
                        url: https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_kubevirt_image.qcow2
                        size: 30Gi

                    vms:
                      - name: wan-rt2
                        installing: false

                        podNetwork:
                          enabled: false
                        
                        disk:
                          enabled: true

                          size: 5Gi

                        networks:
                          - name: intel-nic1-backend953
                            macAddress: 02:09:53:01:03:01

                          - name: intel-nic2-conntrack-sync
                            macAddress: 02:15:00:01:03:01

                      - name: wan-rt1
                        installing: false

                        podNetwork:
                          enabled: false
                        disk:
                          enabled: true

                          size: 5Gi

                        networks:
                          - name: mlx3-nic2-backend951

                          - name: mlx3-nic2-backend953

                          - name: mlx3-nic2-conntrack-sync

                      - name: transit-lab1
                        installing: false

                        cpus:
                          cores: 2
                          sockets: 1
                          threads: 1

                        podNetwork:
                          enabled: false
                        
                        disk:
                          enabled: true

                          size: 5Gi

                        networks:
                          - name: mlx3-nic2-backend951

                      - name: transit-lab2
                        installing: false

                        cpus:
                          cores: 2
                          sockets: 1
                          threads: 1

                        podNetwork:
                          enabled: false
                        
                        disk:
                          enabled: true

                          size: 5Gi

                        networks:
                          - name: intel-nic1-backend951

                      - name: debian-lab1
                        installing: true
                        installer: debian

                        cpus:
                          cores: 2
                          sockets: 1
                          threads: 1

                        podNetwork:
                          enabled: true
                        
                        disk:
                          enabled: true

                          size: 5Gi

                    networks:
                      - name: mlx3-nic2-backend951
                        vlan: 951
                        mtu: 9216
                        sriov:
                          device: mellanox.com/mlx4_cx3_vfio

                      - name: mlx3-nic2-backend953
                        vlan: 953
                        mtu: 9216
                        sriov:
                          device: mellanox.com/mlx4_cx3_vfio

                      - name: mlx3-nic2-conntrack-sync
                        vlan: 1500
                        mtu: 9000
                        sriov:
                          device: mellanox.com/mlx4_cx3_vfio

                      - name: intel-nic1-backend951
                        vlan: 951
                        mtu: 9216
                        sriov:
                          device: intel.com/intel_i350_vfio

                      - name: intel-nic2-backend953
                        vlan: 951
                        mtu: 9216
                        sriov:
                          device: intel.com/intel_i350_vfio

                      - name: intel-nic2-conntrack-sync
                        vlan: 1500
                        mtu: 9000
                        sriov:
                          device: intel.com/intel_i350_vfio

                - name: core-home1-talos-prod
                  values:
                    networks:
                      - name: wan-home
                        vlan: 150
                        mtu: 1500
                        type: sriov
                        sriov:
                          trust: true
                          device: intel.com/intel_x540_dpdk

                      - name: home2-rt2
                        vlan: 20
                        mtu: 9000
                        type: sriov
                        sriov:
                          trust: true
                          device: intel.com/intel_x540_dpdk

                      - name: home2-rt2-alt1
                        vlan: 21
                        mtu: 9000
                        type: sriov
                        sriov:
                          trust: true
                          device: intel.com/intel_x540_dpdk

                      - name: home2-rt1
                        vlan: 30
                        mtu: 9000
                        type: sriov
                        sriov:
                          trust: true
                          device: intel.com/intel_x540_dpdk

                      - name: home2-rt1-alt1
                        vlan: 31
                        mtu: 9000
                        type: sriov
                        sriov:
                          trust: true
                          device: intel.com/intel_x540_dpdk

                      - name: conntrack-sync
                        vlan: 1000
                        mtu: 1500
                        type: sriov
                        sriov:
                          trust: true
                          device: intel.com/intel_x540_dpdk

                    installers:
                      - name: vyos
                        url: https://github.com/vyos/vyos-nightly-build/releases/download/2026.07.11-0033-rolling/vyos-2026.07.11-0033-rolling-generic-amd64.iso
                        size: 30Gi

                      - name: windows-11
                        url: http://10.1.1.84/Win11_25H2_English_x64.iso
                        size: 30Gi

                      - name: flatcar
                        url: https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_kubevirt_image.qcow2
                        size: 30Gi
                    vms:
                      - name: windows-lab
                        uefi: true
                        boot:
                          mode: uefi
                          secureBoot: true
                        tpm:
                          enabled: true
                        nodeSelector:
                          kubernetes.io/hostname: 'hpc3'
                        disk:
                          enabled: true
                          size: 128Gi
                        networks:
                          - name: wan-home

                      - name: wan-rt1
                        installing: false
                        disk:
                          enabled: true
                          size: 5Gi
                        networks:
                          - name: wan-home

                      - name: wan-rt2
                        installing: false
                        boot:
                          mode: uefi
                          secureBoot: false
                        podNetwork:
                          enabled: false
                        disk:
                          enabled: true
                          size: 5Gi
                        networks:
                          - name: wan-home
                            macAddress: '02:01:50:00:02:01'
                          - name: home2-rt2

                      - name: transit-lab1
                        installing: true
                        installer: vyos
                        cpus:
                          cores: 2
                          sockets: 1
                          threads: 1
                        podNetwork:
                          enabled: false
                        disk:
                          enabled: true
                          size: 10Gi
                        networks:
                          - name: wan-home

          - clusters:
              selector:
                matchLabels:
                  mylogin.space/tenant: 'core.mylogin.space'
                  resolvemy.host/computetype: 'baremetal'
              values:
                clusterName: '{{ .name }}'
                environment: 'testing'
                clusterDomain: '{{ index .metadata.labels "cluster.kubernetes.io/domain" }}'
                tenant: '{{ index .metadata.labels "mylogin.space/tenant" }}'

  syncPolicy:
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: '{{ .values.clusterName }}-lab-vms'

      annotations:
        argocd.argoproj.io/manifest-generate-paths: .

    spec:
      project: core

      syncPolicy:
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true

      source:
        path: Lab/VMs
        repoURL: https://github.com/K-FOSS/CoRE-Backplane.git
        targetRevision: HEAD
        plugin:
          name: argocd-lovely-plugin
          env:
            - name: LOVELY_HELM_MERGE
              value: |- # yaml
                env: {{ .values.environment }}

                {{- if .values.vms }}
                vms:
                {{ nindent 2 (toYaml .values.vms) }}
                {{- end }}

                {{- if .values.installers }}
                installers:
                {{ nindent 2 (toYaml .values.installers) }}
                {{- end }}

                {{- if .values.networks }}
                networks:
                {{ nindent 2 (toYaml .values.networks) }}
                {{- end }}

      destination:
        server: '{{ .server }}'
        namespace: core-{{ .values.environment }}

