---
global:
  # -- Set the entire name definition
  fullnameOverride: natpuncher

portRange:
  min: 15000
  max: 16000

coturn:
  enabled: false

UPNP:
  enabled: true

  dhcp:
    enabled: true
    timeoutSeconds: 30

  network:
    interfaces:
      - type: sriov
        mtu: 9000
        routing:
          ospf:
            enabled: false
        ipam:
          address: 10.7.7.61/24
          routes:
            - dst: 0.0.0.0/0
              gw: 10.7.7.1
        sriov:
          vlan: 666
          device: mellanox.com/mlx4_cx3_netdevice

  ports:
    - target: 10.0.0.19
      internalPort: 80
      externalPort: 80
      protocol: TCP
      duration: 8600

    - target: 10.0.0.19
      internalPort: 443
      externalPort: 443
      protocol: TCP
      duration: 8600

networking:
  expose: true

  publicAddress: 66.165.222.101 

