apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 'core-backplane-kafka'
  namespace: 'argocd'

  annotations:
    argocd.argoproj.io/sync-wave: '20'

spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'

  generators:
    - clusters:
        selector:
          matchLabels:
            mylogin.space/tenant: 'core.mylogin.space'
            resolvemy.host/env: 'prod'
            resolvemy.host/dc: 'home1'

  syncPolicy:
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: '{{ .name }}-kafka'

      annotations:
        argocd.argoproj.io/manifest-generate-paths: '.'

    spec:
      project: 'core'

      syncPolicy:
        syncOptions:
          - 'CreateNamespace=true'
          - 'ServerSideApply=true'

      source:
        path: 'EventStream/Kafka'
        repoURL: 'https://github.com/K-FOSS/CoRE-Backplane.git'
        targetRevision: 'HEAD'

        plugin:
          name: 'argocd-lovely-plugin'
          env:
            - name: 'LOVELY_HELM_MERGE'
              value: |-
                external:
                  enabled: true
                  hostname: 'kafka.{{ .name }}.{{ index .metadata.labels "resolvemy.host/dc" }}.{{ index .metadata.labels "topology.kubernetes.io/region" }}.mylogin.space'
                  brokerHostname: 'kafka-0.{{ .name }}.{{ index .metadata.labels "resolvemy.host/dc" }}.{{ index .metadata.labels "topology.kubernetes.io/region" }}.mylogin.space'
                  brokerHostnames:
                    - 'kafka-0.{{ .name }}.{{ index .metadata.labels "resolvemy.host/dc" }}.{{ index .metadata.labels "topology.kubernetes.io/region" }}.mylogin.space'
                    - 'kafka-1.{{ .name }}.{{ index .metadata.labels "resolvemy.host/dc" }}.{{ index .metadata.labels "topology.kubernetes.io/region" }}.mylogin.space'
                    - 'kafka-2.{{ .name }}.{{ index .metadata.labels "resolvemy.host/dc" }}.{{ index .metadata.labels "topology.kubernetes.io/region" }}.mylogin.space'
                ui:
                  hostname: 'kafka-ui.{{ .name }}.{{ index .metadata.labels "resolvemy.host/dc" }}.{{ index .metadata.labels "topology.kubernetes.io/region" }}.mylogin.space'
                kafka-ui:
                  envs:
                    config:
                      KAFKA_UI_PUBLIC_URL: 'https://kafka-ui.{{ .name }}.{{ index .metadata.labels "resolvemy.host/dc" }}.{{ index .metadata.labels "topology.kubernetes.io/region" }}.mylogin.space'

      destination:
        server: '{{ .server }}'
        namespace: 'core-prod'
