apiVersion: v2
appVersion: 0.3.0
description: Vault Autounseal takes Vault unseal tokens and automatically unseals Hashicorp Vault
name: vault-autounseal
version: 0.0.1

maintainers:
  - name: Entrapta
    email: entrapta@mylogin.space
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.4.0
