#
# This chart uses the bjw-s common library chart.

global: {}

controllers:
  main:
    type: deployment
    replicas: 3
    strategy: RollingUpdate
    rollingUpdate:
      unavailable: 2
    revisionHistoryLimit: 3

    containers:
      main:
        image:
          repository: ghcr.io/lrstanley/vault-unseal
          tag: 0.3.0
          pullPolicy: IfNotPresent

        env:
          TZ: UTC

        command:
          - /usr/local/bin/vault-unseal
        args:
          - --config=/etc/vault-unseal.yaml

        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false

vaultURLs:
  - http://dc1-k3s-node1-corevault-0.dc1-k3s-node1-corevault-internal.core-prod.svc.cluster.local:8200
  - http://dc1-k3s-node1-corevault-1.nuc1-home1-corevault-internal.core-prod.svc.cluster.local:8200
  - http://dc1-k3s-node1-corevault-2.nuc1-home1-corevault-internal.core-prod.svc.cluster.local:8200
  - http://core-dc1-talos-prod-core-corevault-prod-0.core-dc1-talos-prod-core-corevault-prod-internal.core-prod.svc.k3s.dc1.resolvemy.host:8200

externalSecret:
  name: corevault-rootsecrets
  kind: ClusterSecretStore

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    controller: main
    ports:
      http:
        port: 9000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  vault-autounseal-config:
    enabled: true
    type: secret
    name: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}-config'
    defaultMode: 0600
    advancedMounts:
      main:
        main:
          - path: /etc/vault-unseal.yaml
            subPath: unsealConfig.yaml
            readOnly: true
