tenant:
  name: example-tenant

pubgateway:
  name: main-gw
  namespace: core-prod
  sectionName: 'https-myloginspace'

authentik:
  autoconfigure: true
  application:
    displayName: 'Chaptarr'
    externalHost: 'https://books.mylogin.space'
    group: 'Media'
  accessGroups:
    - 'Media Consumers'
  route:
    enabled: true
    backend:
      name: 'aaa-myloginspace-proxy'
      namespace: core-prod
      port: 80

user:
  uid: 911
  gid: 911

global:
  timezone: 'America/Vancouver'

chaptarr:
  enabled: true
  image: 'docker.io/chaptarr/chaptarr'
  tag: 'latest'
  digest: 'sha256:ccbe157f88f33d085d12a3e5d7cfb9d5b15f89d69b6eba984f789064d21e1b85'
  volumes:
    config:
      enabled: true
    media:
      enabled: true
    downloads:
      enabled: true
