tenant:
  name: example-tenant

pubgateway:
  name: main-gw
  namespace: core-prod
  sectionName: 'https-myloginspace'

authentik:
  autoconfigure: true

  application:
    displayName: 'Lidarr'
    externalHost: 'https://music.mylogin.space'
    group: 'Media'

  accessGroups:
    - 'Media Consumers'

  route:
    enabled: true

    backend:
      name: 'aaa-myloginspace-proxy'
      namespace: 'core-prod'
      port: 80

user:
  uid: 911
  gid: 911

global:
  timezone: 'America/Vancouver'


lidarr:
  enabled: true

  image: ghcr.io/hotio/lidarr
  tag: pr-plugins

  volumes:
    config:
      enabled: true

      size: 5G

    downloads:
      enabled: true

      external: true

    media:
      enabled: true

      external: true

youtubeSessionGenerator:
  enabled: true

  image:
    repository: 'docker.io/brainicism/bgutil-ytdlp-pot-provider'
    tag: '1.3.2@sha256:9a96e6385ce1928da87dea07b1cab0413d2cf8c07a3b8a8bd419f53df2c3843c'

  port: 4416
