env: 'prod'

# Supplied by the owning ApplicationSet.
domain: ''

# Hostname advertised by ExternalDNS for the controller service.
hostname: 'unifi.mylogin.space'

unpoller:
  enabled: false

images:
  unpoller:
    repository: 'ghcr.io/unpoller/unpoller'
    tag: 'v5.2.4@sha256:e1fad2c2d897cd71e3aaebe32c6fa87b1b205b6ebfde5c8fc036bc62b1930731'
    pullPolicy: 'IfNotPresent'
