apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 'core-backplane-storage-s3-seaweedfs-yxl'
  namespace: 'argocd'
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - clusters:
        selector:
          matchLabels:
            mylogin.space/tenant: 'core.mylogin.space'
            resolvemy.host/computetype: 'baremetal'
            resolvemy.host/nodetype: 'infra'
            resolvemy.host/dc: 'dc1'
            topology.kubernetes.io/region: 'yxl'
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{ .name }}-core-storage-s3-seaweedfs-{{ index .metadata.labels "resolvemy.host/env" }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '.'
    spec:
      project: 'core'
      syncPolicy:
        syncOptions:
          - 'ServerSideApply=true'
          - 'CreateNamespace=true'
      source:
        path: 'Storage/S3/SeaweedFS'
        repoURL: 'https://slop.writemy.codes/CoRE/CoRE-Backplane.git'
        targetRevision: 'HEAD'
        plugin:
          name: 'argocd-lovely-plugin'
          env:
            - name: 'LOVELY_HELM_MERGE'
              value: |-
                cluster:
                  name: '{{ .name }}'
                  domain: '{{ index .metadata.labels "cluster.kubernetes.io/domain" }}'

                environment: '{{ index .metadata.labels "resolvemy.host/env" }}'
                datacenter: '{{ index .metadata.labels "resolvemy.host/dc" }}'
                region: '{{ index .metadata.labels "topology.kubernetes.io/region" }}'
                domain: 'mylogin.space'

      destination:
        server: '{{ .server }}'
        namespace: 'core-{{ index .metadata.labels "resolvemy.host/env" }}'
