apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-backplane-vault
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  goTemplate: true
  # goTemplateOptions:
  #   - 'missingkey=error'
  generators:
    - merge:
        mergeKeys:
          - name

        generators:
          - list:
              elements:
                - name: core-dc1-talos-prod
                  values:
                    hub: false

                - name: core-home1-talos-prod
                  values:
                    hub: false

          - clusters:
              selector:
                matchLabels:
                  mylogin.space/tenant: 'core.mylogin.space'
              values:
                clusterName: '{{ .name }}'
                environment: '{{ index .metadata.labels "resolvemy.host/env" }}'
                clusterDomain: '{{ index .metadata.labels "cluster.kubernetes.io/domain" }}'
                tenant: '{{ index .metadata.labels "mylogin.space/tenant" }}'
                datacenter: '{{ index .metadata.labels "resolvemy.host/dc" }}'
                domain: '{{ .name }}.{{ index .metadata.labels "resolvemy.host/dc" }}.{{ index .metadata.labels "topology.kubernetes.io/region" }}.mylogin.space'
                replicas: '1'

  template:
    metadata:
      name: '{{ .values.clusterName }}-core-vault-{{ .values.environment }}'

      annotations:
        argocd.argoproj.io/manifest-generate-paths: .

    spec:
      project: core


      source:
        path: Hashicorp/Vault
        repoURL: https://github.com/K-FOSS/CoRE-Backplane.git
        targetRevision: HEAD
        plugin:
          name: argocd-lovely-plugin

          env:
            - name: LOVELY_HELM_MERGE
              value: |-
                hub: {{ .values.hub }}

                vault:
                  server:
                    dataStorage:
                      enabled: true
                      size: '50Gi'
                      storageClass: 'vault-longhorn'
                    ha:
                      replicas: 1
                      raft:
                        enabled: true
                        setNodeId: true
                        config: |
                          ui = true

                          listener "tcp" {
                            tls_disable = 1
                            address = "[::]:8200"
                            cluster_address = "[::]:8201"
                          }

                          storage "raft" {
                            path = "/vault/data"
                            retry_join {
                              leader_api_addr = "http://core-home1-talos-prod-core-vault-prod-internal.core-prod.svc.cluster.local:8200"
                            }
                          }

                          disable_mlock = true

                          service_registration "kubernetes" {}

                          seal "transit" {
                            address = "http://corevault.{{ .values.domain }}:8200"
                            disable_renewal = "false"
                            key_name = "autounseal"
                            mount_path = "transit/"
                            tls_skip_verify = "true"
                          }
                    extraVolumes:
                      - name: 'storage-migration'
                        type: 'configMap'
                    extraInitContainers:
                      - name: 'vault-storage-migration'
                        image: 'hashicorp/vault:1.13.1'
                        imagePullPolicy: 'IfNotPresent'
                        command: ['/bin/sh', '-ec']
                        args:
                          - '/bin/vault operator migrate -config=/vault/storage-migration/migrate.hcl'
                        volumeMounts:
                          - name: 'data'
                            mountPath: '/vault/data'
                          - name: 'userconfig-storage-migration'
                            mountPath: '/vault/storage-migration'
                            readOnly: true

                global:
                  corevault:
                    address: 'http://corevault.{{ .values.domain }}:8200'

            - name: LOVELY_KUSTOMIZE_MERGE
              value: |-
                patches:
                  {{- if eq .values.clusterName "core-dc1-talos-prod" }}
                  - target:
                      group: apps
                      version: v1
                      kind: StatefulSet
                      name: core-dc1-talos-prod-core-vault-prod
                    patch: |-
                      - op: replace
                        path: /spec/replicas
                        value: 1
                  {{- end }}
                  - target:
                      kind: Service
                      name: {{ .values.clusterName }}-core-vault-{{ .values.environment }}

                    patch: |
                      - op: add
                        path: /metadata/labels/wan-mode
                        value: public

                      - op: add
                        path: /metadata/annotations
                        value:
                          external-dns.kubernetes.io/hostname: 'vault.{{ .values.domain }}'
                          # TODO(external-dns-014): Remove the legacy annotation after upgrading ExternalDNS.
                          external-dns.alpha.kubernetes.io/hostname: vault.{{ .values.domain }}

      destination:
        server: '{{ .server }}'
        namespace: core-{{ .values.environment }}
