{{ if .Values.renovate.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

  target:
    name: renovate-token
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: 'Forgejo/{{ .Values.cluster.name }}/Renovate'
        property: token
{{- end }}
