apiVersion: v2
name: 'core-storage-s3-seaweedfs-operator'
description: 'YXL SeaweedFS operator and CRDs'
type: application
version: 1.0.0
dependencies:
  - name: seaweedfs-operator
    version: '0.1.43'
    repository: 'https://seaweedfs.github.io/seaweedfs-operator/'
