seaweedfs-operator:
  fullnameOverride: 'core-s3-seaweedfs-operator'
  # Chart appVersion 1.0.40, released as chart version 0.1.43.
  image:
    registry: 'ghcr.io'
    repository: 'seaweedfs/seaweedfs-operator'
    tag: '1.0.40'
    pullPolicy: 'IfNotPresent'
  grafanaDashboard:
    enabled: false
  serviceMonitor:
    enabled: false
  csiDriver:
    enabled: false
  webhook:
    enabled: true
