
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-backplane-storage-cdn
  namespace: argocd

spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - clusterName: core-dc1-talos-prod
                  environment: prod
                  region: yxl
                  datacenter: dc1
                  sloEnabled: false

                - clusterName: core-home1-talos-prod
                  environment: prod
                  region: yvr
                  datacenter: home1
                  sloEnabled: true

          - list:
              elements:
                - site: idle
                  url: idle.snd.fyi
                  bucket: '<path:CORE0_SITE1/data/Storage/CDN/S3#Bucket>'
                  externalSecretStoreKind: ClusterSecretStore
                  externalSecretStoreName: mainvault-core
                  externalSecretAccessKeyPath: Storage/CDN/S3
                  externalSecretAccessKeyProperty: AccessKey
                  externalSecretSecretKeyPath: Storage/CDN/S3
                  externalSecretSecretKeyProperty: SecretKey


  syncPolicy:
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: '{{ .clusterName }}-cdn-{{ if ne .site "idle" }}{{ .site }}-{{ end }}{{ .environment }}'

      labels:
        resolvemy.host/env: '{{ .environment }}'

      annotations:
        argocd.argoproj.io/manifest-generate-paths: .

    spec:
      project: core

      syncPolicy:
        syncOptions:
          - ServerSideApply=true

      source:
        path: Storage/CDN
        repoURL: https://github.com/K-FOSS/CoRE-Backplane.git
        targetRevision: HEAD
        plugin:
          name: argocd-lovely-plugin
          env:
            - name: LOVELY_HELM_MERGE
              value: |- # yaml
                env: '{{ .environment }}'

                cdn:
                  name: '{{ .site }}'
                  url: '{{ .url }}'
                  externalSecret:
                    secretStoreRef:
                      kind: '{{ .externalSecretStoreKind }}'
                      name: '{{ .externalSecretStoreName }}'
                    accessKey:
                      key: '{{ .externalSecretAccessKeyPath }}'
                      property: '{{ .externalSecretAccessKeyProperty }}'
                    secretKey:
                      key: '{{ .externalSecretSecretKeyPath }}'
                      property: '{{ .externalSecretSecretKeyProperty }}'

                slo:
                  enabled: {{ .sloEnabled }}

                idle:
                  fullnameOverride: 'cdn-{{ .site }}'
                  existingSecret: 'cdn-{{ .site }}'
                  configFiles:
                    config.yaml:
                      authproviders:
                        basic:
                          idle:
                            realm: '{{ .url }}'
                      targets:
                        first-bucket:
                          bucket:
                            name: '{{ .bucket }}'
                            s3Endpoint: 'https://s3.{{ .clusterName }}.{{ .datacenter }}.{{ .region }}.mylogin.space'
      destination:
        name: '{{ .clusterName }}'
        namespace: core-{{ .environment }}
