---
{{- define "core.promRulefilesConfigMapName" -}}
{{- $base := printf "prometheus-%s" .Values.cluster.name -}}
{{- printf "%s-%s" $base "export-prometheus-rulefiles" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- include "bjw-s.common.loader.init" . }}

{{- define "app-template.hardcodedValues" -}}
# Set the nameOverride based on the release name if no override has been set
{{ if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"
{{ end }}

{{ if eq .Values.mimir.enabled true }}

controllers:
  mimir:
    # For Deployments, valid values are Recreate (default) and RollingUpdate.
    # For StatefulSets, valid values are OnDelete and RollingUpdate (default).
    # DaemonSets/CronJobs ignore this.
    strategy: RollingUpdate

    rollingUpdate:
      unavailable: 1
      surge: 1

    podDisruptionBudget:
      maxUnavailable: 1

    pod:
      terminationGracePeriodSeconds: 120

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: '{{ $.Release.Name }}'
                    app.kubernetes.io/controller: mimir
                topologyKey: kubernetes.io/hostname

      securityContext:
        fsGroup: 10001
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001

      {{- with .Values.mimir.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}

    replicas: {{ .Values.mimir.replicas }}

    containers:
      mimir:
        image:
          repository: {{ .Values.mimir.image.repository }}
          tag: {{ .Values.mimir.image.tag | quote }}
          pullPolicy: {{ .Values.mimir.image.pullPolicy }}

        resources:
          {{- toYaml .Values.mimir.resources | nindent 10 }}

        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true

        ports:
          - name: http
            containerPort: 8080
          - name: grpc
            containerPort: 9095

        args:
          - -config.file=/etc/mimir.yaml
          - -config.expand-env=true

        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ $.Release.Name }}-s3-creds
                key: AccessKey

          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ $.Release.Name }}-s3-creds
                key: SecretAccessKey

          - name: AWS_SESSION_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ $.Release.Name }}-s3-creds
                key: SessionToken

          - name: S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: {{ $.Release.Name }}-creds
                key: username

        probes:
          startup:
            enabled: true
            custom: false
            type: HTTP
            path: /ready
            port: http
            spec:
              periodSeconds: 5
              timeoutSeconds: 3
              failureThreshold: 60

          liveness:
            enabled: true
            custom: false
            type: TCP
            port: http
            spec:
              periodSeconds: 15
              timeoutSeconds: 5
              failureThreshold: 4

          readiness:
            enabled: true
            custom: false
            path: /ready
            port: http
            type: HTTP
            spec:
              failureThreshold: 3
              periodSeconds: 10
              timeoutSeconds: 5

service:
  mimir:
    # -- Enables or disables the service
    enabled: true

    # -- Configure which controller this service should target
    controller: mimir

    # -- Make this the primary service for this controller (used in probes, notes, etc...).
    # If there is more than 1 service targeting the controller, make sure that only 1 service is
    # marked as primary.
    primary: false

    suffix: main

    # -- Set the service type
    type: ClusterIP

    # -- Specify the externalTrafficPolicy for the service. Options: Cluster, Local
    # -- [[ref](https://kubernetes.io/docs/tutorials/services/source-ip/)]
    #externalTrafficPolicy: Local

    # -- Specify the ip policy. Options: SingleStack, PreferDualStack, RequireDualStack
    ipFamilyPolicy:
    # -- The ip families that should be used. Options: IPv4, IPv6
    ipFamilies: []

    # -- Provide additional annotations which may be required.
    annotations: {}

    # -- Provide additional labels which may be required.
    labels: {}

    # -- Allow adding additional match labels
    extraSelectorLabels: {}

    ports:
      http:
        # -- Enables or disables the port
        enabled: true

        # -- Make this the primary port (used in probes, notes, etc...)
        # If there is more than 1 service, make sure that only 1 port is marked as primary.
        primary: false

        # -- The port number
        port: 8080

        # -- Port protocol.
        # Support values are `HTTP`, `HTTPS`, `TCP` and `UDP`.
        # HTTP and HTTPS spawn a TCP service and get used for internal URL and name generation
        protocol: TCP

        # -- Specify the appProtocol value for the Service.
        # [[ref]](https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol)
        appProtocol:

  mimir-gossip:
    # -- Enables or disables the service
    enabled: true

    # -- Configure which controller this service should target
    controller: mimir

    # -- Make this the primary service for this controller (used in probes, notes, etc...).
    # If there is more than 1 service targeting the controller, make sure that only 1 service is
    # marked as primary.
    primary: false

    suffix: gossip

    nameOverride: mimir-stuff

    # -- Set the service type
    type: ClusterIP

    # -- Specify the externalTrafficPolicy for the service. Options: Cluster, Local
    # -- [[ref](https://kubernetes.io/docs/tutorials/services/source-ip/)]
    #externalTrafficPolicy: Local

    # -- Specify the ip policy. Options: SingleStack, PreferDualStack, RequireDualStack
    ipFamilyPolicy:
    # -- The ip families that should be used. Options: IPv4, IPv6
    ipFamilies: []

    clusterIP: None

    # -- Provide additional annotations which may be required.
    annotations: {}

    # -- Provide additional labels which may be required.
    labels: {}

    # -- Allow adding additional match labels
    extraSelectorLabels: {}

    publishNotReadyAddresses: true

    ports:
      gossip-tcp:
        # -- Enables or disables the port
        enabled: true

        # -- Make this the primary port (used in probes, notes, etc...)
        # If there is more than 1 service, make sure that only 1 port is marked as primary.
        primary: false

        # -- The port number
        port: 7946

        # -- Port protocol.
        # Support values are `HTTP`, `HTTPS`, `TCP` and `UDP`.
        # HTTP and HTTPS spawn a TCP service and get used for internal URL and name generation
        protocol: TCP

        # -- Specify the appProtocol value for the Service.
        # [[ref]](https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol)
        appProtocol:


configMaps:
  mimir-alertmanager-fallback:
    enabled: true

    data:
      alertmanager_fallback_config.yaml: |
        receivers:
            - name: default-receiver
        route:
          receiver: default-receiver

  mimir-configs:
    enabled: true

    data:
      mimir.yaml: |
        # Horizontally scaled monolithic mode: each replica runs all components.
        target: all,alertmanager,overrides-exporter

        activity_tracker:
          filepath: /data/metrics-activity.log

        multitenancy_enabled: false
        no_auth_tenant: core

        limits:
          max_global_series_per_user: 5000000
          ingestion_rate: 500000
          ingestion_burst_size: 1550000
          out_of_order_time_window: 24h
          compactor_blocks_retention_period: 24h

        # Configure Mimir to use Minio as object storage backend.
        common:
          storage:
            backend: s3
            s3:
              endpoint: s3.{{ .Values.cluster.name }}.{{ .Values.datacenter }}.{{ .Values.region }}.mylogin.space:443
              access_key_id: "${AWS_ACCESS_KEY_ID}"
              secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
              session_token: "${AWS_SESSION_TOKEN}"
              insecure: false
              bucket_name: ${S3_BUCKET}
              http:
                max_idle_connections: 200
                max_idle_connections_per_host: 200

        # Blocks storage requires a prefix when using a common object storage bucket.
        blocks_storage:
          storage_prefix: blocks
          s3:
            bucket_name: ${S3_BUCKET}
          bucket_store:
            sync_dir: /data/tsdb-sync
            tenant_sync_concurrency: 4
            block_sync_concurrency: 8
          tsdb:
            dir: /data/ingester
            ship_concurrency: 20

        querier:
          max_concurrent: 32

        query_scheduler:
          max_outstanding_requests_per_tenant: 1024

        compactor:
          data_dir: /data/compactor

        # Use memberlist, a gossip-based protocol, to enable the 3 Mimir replicas to communicate
        memberlist:
          join_members:
            - dns+{{ $.Release.Name }}-mimir-gossip.{{ .Release.Namespace }}.svc.{{ .Values.cluster.domain }}.:7946


        alertmanager_storage:
          s3:
            bucket_name: mimir-alertmanager
        
        ruler_storage:
          backend: local
          local:
            directory: /rules
          s3:
            bucket_name: mimir-ruler

        ruler:
          rule_path: /data/ruler
          alertmanager_url: http://127.0.0.1:8080/alertmanager

        alertmanager:
          data_dir: /data/alertmanager
          fallback_config_file: /etc/alertmanager-fallback-config.yaml
          external_url: http://localhost:9009/alertmanager

        server:
          log_level: warn
          grpc_server_max_concurrent_streams: 1000

persistence:
  mimir-data:
    enabled: true

    type: emptyDir

    medium: Memory

    sizeLimit: {{ .Values.mimir.dataVolume.sizeLimit }}

    advancedMounts:
      mimir:
        mimir:
          - path: /data

  mimir-tmp:
    enabled: true

    type: emptyDir

    medium: Memory

    sizeLimit: {{ .Values.mimir.tmpVolume.sizeLimit }}

    advancedMounts:
      mimir:
        mimir:
          - path: /tmp

  mimir-alertmanager:
    enabled: true

    type: configMap

    name: '{{ $.Release.Name }}-mimir-alertmanager-fallback'

    defaultMode: 0755

    advancedMounts:
      mimir: # the controller with the "main" identifier
        mimir: # the container with the "main" identifier
          - path: /etc/alertmanager-fallback-config.yaml
            readOnly: true
            subPath: alertmanager_fallback_config.yaml

  mimir-config:
    enabled: true

    type: configMap

    name: '{{ $.Release.Name }}-mimir-configs'

    defaultMode: 0755

    advancedMounts:
      mimir: # the controller with the "main" identifier
        mimir: # the container with the "main" identifier
          - path: /etc/mimir.yaml
            readOnly: true
            subPath: mimir.yaml


  mimir-rules:
    enabled: true

    type: configMap

    name: '{{ include "core.promRulefilesConfigMapName" $ }}'

    defaultMode: 0755

    advancedMounts:
      mimir: # the controller with the "main" identifier
        mimir: # the container with the "main" identifier
          - path: /rules/core


{{- end }}

{{- end -}}
{{- $_ := mergeOverwrite .Values (include "app-template.hardcodedValues" . | fromYaml) -}}

{{- if .Values.mimir.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: core-mimir

  labels:
    wan-mode: 'public'
    lan-mode: 'private'

spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: core-prod
      name: main-gw

  hostnames:
    - metrics.mylogin.space
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: '{{ ((include "bjw-s.common.lib.service.getByIdentifier" (dict "rootContext" . "id" "mimir")) | fromYaml).name }}'
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
{{- end }}
{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
