{{- if and (index .Values "mimir-distributed" "enabled") .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.gateway.routeName }}

  {{- with .Values.gateway.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  parentRefs:
    {{- toYaml .Values.gateway.parentRefs | nindent 4 }}

  hostnames:
    {{- toYaml .Values.gateway.hostnames | nindent 4 }}
  rules:
    {{ $chart := index $.Subcharts "mimir-distributed" }}
    {{ $values := index .Values "mimir-distributed" }}
    {{ range $v, $t := $values.ingress.paths }}
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ include "mimir.fullname" $chart }}-{{ regexReplaceAll "([[:upper:]])" $v  "-${1}" | lower }}
          port: {{ include "mimir.serverHttpListenPort" $chart }}
          weight: 1
      matches:
        {{- range $path := $t }}
        - path:
            type: PathPrefix
            value: {{ $path.path }}
        {{ end }}
    {{- end -}}
{{- end }}
