{{- if .Values.oidc.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ required "oidc.resourceName is required when OIDC is enabled" .Values.oidc.resourceName }}

spec:
  refreshInterval: 6h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: {{ required "oidc.secretStoreRef is required when OIDC is enabled" .Values.oidc.secretStoreRef }}

  selector:
    secret:
      name: {{ .Values.oidc.resourceName }}

  data:
    - match:
        secretKey: client_id
        remoteRef:
          remoteKey: {{ required "oidc.remoteKey is required when OIDC is enabled" .Values.oidc.remoteKey }}
          property: ClientID

    - match:
        secretKey: client-secret
        remoteRef:
          remoteKey: {{ .Values.oidc.remoteKey }}
          property: ClientSecret
{{- end }}
