{{- if .Values.securityPolicy.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ .Values.gateway.routeName }}

spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ .Values.gateway.routeName }}

  jwt:
    {{- toYaml .Values.securityPolicy.jwt | nindent 4 }}



  # extAuth:
  #   http:
  #     backendRefs:
  #       - name: authorino-authorino-authorization
  #         namespace: authorino-operator
  #         port: 5001
  #     headersToBackend: ["x-current-user"]

  # extAuth:
  #   type: HTTP
  #   http:
  #     host: authentik-outpost.kube-system.
  #     port: 80
  #     path: /outpost.goauthentik.io/auth/envoy
  #     headersToBackend:
  #       - x-authentik

  # authorization:
  #   defaultAction: Deny
  #   rules:
  #     - name: "allow"
  #       action: Allow
  #       principal:
  #         jwt:
  #           provider: grafana
  #           claims:
  #             - name: groups
  #               valueType: StringArray
  #               values: ["Metrics"]


  #     - name: "allow"
  #       action: Allow
  #       principal:
  #         jwt:
  #           provider: authentik
  #           claims:
  #             - name: groups
  #               valueType: StringArray
  #               values: ["Metrics"]
{{- end }}
