postgres-operator:
  # Site-specific operator behavior.
  enableJsonLogging: true

  configGeneral:
    docker_image: 'ghcr.io/zalando/spilo-18-dev:6a722f01'
    max_instances: 3

  configUsers:
    enable_password_rotation: true

  configMajorVersionUpgrade:
    major_version_upgrade_mode: 'full'
    minimal_major_version: '12'
    target_major_version: '16'

  configKubernetes:
    enable_owner_references: true
    enable_persistent_volume_claim_deletion: false
    enable_readiness_probe: true
    enable_secrets_deletion: false
    inherited_labels:
      - 'wan-mode'
      - 'lan-mode'
      - 'argocd.argoproj.io/instance'
    pod_environment_configmap: 'core-prod/psql-ops-override'
    pod_environment_secret: 'psql-ops-s3-backup'
    pod_management_policy: 'parallel'
    spilo_runasuser: 101
    spilo_runasgroup: 103
    spilo_fsgroup: 103

  configPostgresPodResources:
    default_cpu_limit: '4'
    default_memory_limit: '16G'
    default_memory_request: '1G'
    max_memory_request: '30G'
    min_memory_limit: '1G'

  configLoadBalancer:
    db_hosted_zone: 'mylogin.space'
    master_dns_name_format: '{cluster}.{hostedzone}'
    replica_dns_name_format: '{cluster}-repl.{hostedzone}'

  configAwsOrGcp:
    aws_region: 'us-east-1'

  configLogicalBackup:
    logical_backup_docker_image: 'ghcr.io/zalando/postgres-operator/logical-backup:v1.13.0'
    logical_backup_s3_region: 'us-east-1'
    logical_backup_s3_endpoint: 's3.mylogin.space'

  priorityClassName: 'tier2-priority'

  podPriorityClassName:
    create: false

  configDebug:
    debug_logging: false

  readinessProbe:
    periodSeconds: 30
