apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: psql-main

  labels:
    wan-mode: public
    lan-mode: private

  annotations:
    acid.zalan.do/controller: '{{ .Values.psql.controllerID }}'

spec:
  teamId: core

  numberOfInstances: {{ include "psql.mylogin.space/replicas" $ }}

  podPriorityClassName: 'tier2-priority'

  enableConnectionPooler: false

  {{- with .Values.psql.maintenanceWindows }}
  maintenanceWindows:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  masterServiceAnnotations:
    external-dns.alpha.kubernetes.io/hostname: 'psql-int.{{ .Values.cluster.name }}.{{ .Values.datacenter }}.{{ .Values.region }}.{{ .Values.tenant.domain }}{{ if .Values.psql.hub }},psql-int.{{ .Values.tenant.domain }}{{ end }}'

  replicaServiceAnnotations:
    external-dns.alpha.kubernetes.io/hostname: 'psql-int-rep.{{ .Values.cluster.name }}.{{ .Values.datacenter }}.{{ .Values.region }}.{{ .Values.tenant.domain }}{{ if .Values.psql.hub }},psql-int-rep.{{ .Values.tenant.domain }}{{ end }}'

  allowedSourceRanges:
    - 0.0.0.0/0

  users:
    opsadmin:
      - superuser
      - createdb
      - LOGIN

  databases:
    ops: opsadmin

  postgresql:
    version: '17'

    parameters:
      max_connections: {{ .Values.psql.tuning.maxConnections | quote }}
      max_prepared_transactions: '1000'
      max_locks_per_transaction: '256'
      shared_buffers: '2GB'
      work_mem: 5592kB
      effective_cache_size: 4022MB
      effective_io_concurrency: '2'
      maintenance_work_mem: 2047MB
      max_worker_processes: {{ .Values.psql.tuning.maxWorkerProcesses | quote }}
      max_parallel_workers: {{ .Values.psql.tuning.maxParallelWorkers | quote }}
      max_parallel_workers_per_gather: {{ .Values.psql.tuning.maxParallelWorkersPerGather | quote }}

  volume:
    size: 50Gi

  resources:
    requests:
      cpu: '100m'
      memory: 1Gi

    limits:
      cpu: '4'
      memory: 8Gi

  patroni:
    failsafe_mode: true
    initdb:
      encoding: 'UTF8'
      locale: 'en_US.UTF-8'
      data-checksums: 'true'

    pg_hba:
      - local all         all                  trust
      - local replication standby              md5
      - host replication  replicator 0.0.0.0/0 md5
      - host replication  standby    0.0.0.0/0 md5
      - host all          3dzxoCeJ1f 0.0.0.0/0 md5
      - host all          GR7Ctx7FGh 0.0.0.0/0 md5
      - host all          5dBrWBAYgF 0.0.0.0/0 md5
      - host all          le6VpU1g8Q 0.0.0.0/0 md5
      - host all          uwneOPXzji 0.0.0.0/0 md5
      - host all          bitwarden 0.0.0.0/0 md5
      - host all          pzyQC6iToI 0.0.0.0/0 md5
      - host all          hRCyPUlFYx 0.0.0.0/0 md5
      - host all          WNUoZH3HCm 0.0.0.0/0 md5
      - host all          postgres   0.0.0.0/0 md5
      - host all          pooler     0.0.0.0/0 md5
      - host all          opsadmin   0.0.0.0/0 md5
      - host all          DlzcnePHKR 0.0.0.0/0 md5
      - host all          N9zANOau1E 0.0.0.0/0 md5
      - host all          all        0.0.0.0/0 ldap ldapserver={{ .Values.ldap.server }} ldapport={{ .Values.ldap.port }} ldapbasedn="{{ .Values.ldap.baseDN }}" ldapbinddn="{{ .Values.ldap.bindDN }}" ldapbindpasswd="<path:CORE0_SITE1/data/PSQL/LDAP#Password>" ldapsearchattribute="{{ .Values.ldap.searchAttribute }}"

    ttl: 30

    loop_wait: 10

    retry_timeout: 10

    synchronous_mode: false

    synchronous_mode_strict: false

    synchronous_node_count: 1

    maximum_lag_on_failover: 33554432

  {{ if .Values.psql.standby }}
  standby:
    standby_host: {{ required "psql.standbyHost is required when psql.standby is true" .Values.psql.standbyHost | squote }}
    standby_port: '5432'
  {{ end }}


  tls:
    secretName: 'myloginspace-default-certificates'
    certificateFile: 'tls.crt'
    privateKeyFile: 'tls.key'
