{{ if .Values.restore -}}
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: psql-main-restore

  labels:
    wan-mode: public
    lan-mode: private

  annotations:
    acid.zalan.do/controller: '{{ .Values.psql.controllerID }}'

spec:
  teamId: core

  numberOfInstances: {{ include "psql.mylogin.space/replicas" $ }} 

  podPriorityClassName: 'tier2-priority'

  enableConnectionPooler: false

  allowedSourceRanges:
    - 0.0.0.0/0

  users:
    opsadmin:
      - superuser
      - createdb
      - LOGIN

  databases:
    ops: opsadmin

  postgresql:
    version: '16'

    parameters:
      fsync: 'off'

  volume:
    size: 25Gi

  resources:
    requests:
      cpu: '100m'
      memory: 1Gi

    limits:
      cpu: '4'
      memory: 8Gi

  patroni:
    failsafe_mode: true
    initdb:
      encoding: 'UTF8'
      locale: 'en_US.UTF-8'
      data-checksums: 'true'

    ttl: 30

    loop_wait: 10

    retry_timeout: 10

    synchronous_mode: false

    synchronous_mode_strict: false

    synchronous_node_count: 1

    maximum_lag_on_failover: 33554432
    
  clone:
    uid: 4ac8bb3a-72c7-4a05-8d20-15d5c835cca7
    cluster: "psql-main"
    timestamp: "2026-05-10T09:45:00-07:00"
{{ end }}