apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - target:
      kind: PodSecurityPolicy

    patch: |
      $patch: delete
      kind: PodSecurityPolicy
      metadata:
        name: DOES NOT MATTER

  - target:
      kind: StatefulSet

    patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: DOES NOT MATTER
      spec:
        template:
          spec:
            containers:
              - name: consul
                volumeMounts:
                  - name: consul-tmp
                    mountPath: /tmp
            volumes:
              - name: consul-tmp
                emptyDir:
                  medium: Memory
                  sizeLimit: 32Gi
