consul:
  global:
    logJSON: true
    domain: kjdev
    secretsBackend:
      vault:
        connectCA:
          additionalConfig: |
            {
              "performance": {
                "raft_multiplier": 5
              }
            }
    argocd:
      enabled: true

  server:
    enabled: true
    storage: 50Gi
    resources:
      requests:
        memory: 8G
        cpu: "1"
      limits:
        memory: 32G
        cpu: "8"
    exposeService:
      enabled: false

  externalServers:
    hosts:
      - consul.
  dns:
    enabled: false

  ui:
    enabled: true

  syncCatalog:
    toConsul: false
    toK8S: false

  connectInject:
    enabled: false
    namespaceSelector: |
      matchExpressions:
        - key: "kubernetes.io/metadata.name"
          operator: "NotIn"
          values: ["kube-system","local-path-storage","openebs"]
