apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

  target:
    name: pgadmin-envs

    template:
      engineVersion: v2
      data:{{`
        password: '{{ .Password }}'

        PGADMIN_CONFIG_AUTHENTICATION_SOURCES: |
          ['ldap']
        PGADMIN_CONFIG_LDAP_AUTO_CREATE_USER: 'True'

        PGADMIN_CONFIG_LDAP_SERVER_URI: |
          '`}}{{ .Values.ldap.pgadmin.serverURI }}{{`'

        PGADMIN_CONFIG_LDAP_USERNAME_ATTRIBUTE: |
          '`}}{{ .Values.ldap.pgadmin.usernameAttribute }}{{`'

        PGADMIN_CONFIG_LDAP_CONNECTION_TIMEOUT: '120'

        PGADMIN_CONFIG_LDAP_BASE_DN: |
          '`}}{{ .Values.ldap.pgadmin.baseDN }}{{`'

        PGADMIN_CONFIG_LDAP_IGNORE_MALFORMED_SCHEMA: 'True'

        PGADMIN_CONFIG_LDAP_SEARCH_BASE_DN: |
          '`}}{{ .Values.ldap.pgadmin.searchBaseDN }}{{`'

        PGADMIN_CONFIG_LDAP_SEARCH_FILTER: |
          '`}}{{ .Values.ldap.pgadmin.searchFilter }}{{`'

        PGADMIN_CONFIG_LDAP_BIND_USER: |
          '{{ .LDAPBIND }}' 

        PGADMIN_CONFIG_LDAP_BIND_PASSWORD: |
          '{{ .Password }}'

        PGADMIN_CONFIG_MAIL_SERVER: 'mail.mylogin.space'
        PGADMIN_CONFIG_MAIL_PORT: '587'
        PGADMIN_CONFIG_MAIL_USE_TLS: 'True'
        PGADMIN_CONFIG_MAIL_USERNAME: |
          '{{ .Username }}'
        PGADMIN_CONFIG_MAIL_PASSWORD: |
          '{{ .Password }}'
        PGADMIN_CONFIG_MAIL_DEFAULT_SENDER: 'pgadmin-`}}{{ .Values.region }}{{`-`}}{{ .Values.datacenter }}{{`@mail.mylogin.space'
        `}}

  data:
    - secretKey: LDAPBIND
      remoteRef:
        key: PSQL/PGAdmin/LDAP
        property: BindUser
      
    - secretKey: Password
      remoteRef:
        key: PSQL/PGAdmin/Credentials
        property: Password

    - secretKey: Username
      remoteRef:
        key: PSQL/PGAdmin/Credentials
        property: Username
