apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 'core-backplane-business-avoip'
  namespace: 'argocd'

  annotations:
    argocd.argoproj.io/sync-wave: '20'

spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'

  generators:
    - merge:
        mergeKeys:
          - 'name'

        generators:
          - matrix:
              generators:
                - list:
                    elements:
                      - tenant: 'core.mylogin.space'
                        clusters:
                          - name: 'core-dc1-talos-prod'
                            values:
                              type: 'hub'
                              hubCluster: 'core-dc1-talos-prod'
                              hubDatacenter: 'dc1'
                              hubRegion: 'yxl'
                              rtpengineMediaAddress: '66.165.222.103'
                              rtpengineMediaPortMin: 11000
                              rtpengineMediaPortMax: 11100
                              asteriskEnabled: true
                              freeswitchEnabled: true
                              externalIP: '66.165.222.103'
                              faxDID: '<path:CORE0_SITE1/data/AVoIP/YXL/DC1#FaxNumber>'
                              avoipDID: '<path:CORE0_SITE1/data/AVoIP/YXL/DC1#AVoIPNumber>'
                              egressIP: '66.165.222.103'
                              ciliumEgressGatewayEnabled: false
                              kamailio:
                                enabled: true
                          - name: 'core-home1-talos-prod'
                            values:
                              type: 'spoke'
                              hubCluster: 'core-dc1-talos-prod'
                              hubDatacenter: 'dc1'
                              hubRegion: 'yxl'
                              rtpengineMediaAddress: '24.86.197.63'
                              rtpengineMediaPortMin: 11000
                              rtpengineMediaPortMax: 11080
                              asteriskEnabled: true
                              freeswitchEnabled: true
                              faxDID: '<path:CORE0_SITE1/data/AVoIP/YVR/Home1#FaxNumber>'
                              avoipDID: '<path:CORE0_SITE1/data/AVoIP/YVR/Home1#AVoIPNumber>'
                              ciliumEgressGatewayEnabled: false
                              kamailio:
                                enabled: true
                                publicExposure:
                                  enabled: true
                                  sip:
                                    enabled: true
                                    udpEnabled: true
                                    tcpEnabled: true
                                    directService:
                                      enabled: true
                                    udpRoute:
                                      enabled: false
                              serviceOptions:
                                kamailio-pub:
                                  type: 'LoadBalancer'
                                  labels:
                                    wan-mode: 'public'
                                    lan-mode: 'private'
                                  annotations:
                                    kube-vip.io/forwardUPNP: 'true'
                                  loadBalancerClass: 'kube-vip.io/kube-vip-class'
                          - name: 'dc1-k3s-node1'
                            values:
                              type: 'spoke'
                              hubCluster: 'core-dc1-talos-prod'
                              hubDatacenter: 'dc1'
                              hubRegion: 'yxl'
                              rtpengineMediaAddress: '66.165.222.103'
                              rtpengineMediaPortMin: 11000
                              rtpengineMediaPortMax: 11050
                              asteriskEnabled: false
                              freeswitchEnabled: false
                              ciliumEgressGatewayEnabled: false

                - list:
                    elementsYaml: '{{ .clusters | toJson }}'

          - clusters:
              selector:
                matchLabels:
                  mylogin.space/tenant: 'core.mylogin.space'
                  resolvemy.host/env: 'prod'
              values:
                clusterName: '{{ .name }}'
                environment: '{{ index .metadata.labels "resolvemy.host/env" }}'
                clusterDomain: '{{ index .metadata.labels "cluster.kubernetes.io/domain" }}'
                tenant: '{{ index .metadata.labels "mylogin.space/tenant" }}'
                region: '{{ index .metadata.labels "topology.kubernetes.io/region" }}'
                zone: '{{ index .metadata.labels "topology.kubernetes.io/zone" }}'
                datacenter: '{{ index .metadata.labels "resolvemy.host/dc" }}'

  syncPolicy:
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: '{{ if eq .values.clusterName "dc1-k3s-node1" }}{{ .values.clusterName }}-business-avoip{{ else }}{{ .values.clusterName }}-business-avoip-{{ .values.environment }}{{ end }}'

      annotations:
        argocd.argoproj.io/manifest-generate-paths: '.'

      labels:
        resolvemy.host/env: '{{ .values.environment }}'

    spec:
      project: 'core'

      syncPolicy:
        syncOptions:
          - 'CreateNamespace=true'
          - 'ServerSideApply=true'

      source:
        repoURL: 'https://slop.writemy.codes/CoRE/CoRE-Business.git'
        path: 'AVoIP'
        targetRevision: 'HEAD'

        plugin:
          name: 'argocd-lovely-plugin'
          env:
            - name: 'LOVELY_HELM_MERGE'
              value: |- # yaml
                env: '{{ .values.environment }}'

                datacenter: '{{ .values.datacenter }}'

                region: '{{ .values.region }}'

                cluster:
                  name: '{{ .values.clusterName }}'
                  domain: '{{ .values.clusterDomain }}'
                  type: '{{ .values.type }}'

                asterisk:
                  enabled: {{ .values.asteriskEnabled }}

                freeswitch:
                  enabled: {{ .values.freeswitchEnabled }}

                {{- if hasKey .values "faxDID" }}
                fax:
                  did: '{{ .values.faxDID }}'
                {{- end }}

                {{- if hasKey .values "avoipDID" }}
                avoip:
                  did: '{{ .values.avoipDID }}'
                {{- end }}

                kamailio:
                {{- if hasKey .values "kamailio" }}
                {{- with .values.kamailio }}
                {{- toYaml . | nindent 2 }}
                {{- end }}
                {{- end }}
                  advertisedHost: 'sip.{{ .values.clusterName }}.{{ .values.datacenter }}.{{ .values.region }}.resolvemy.host'

                network:
                  ciliumEgressGateway:
                    enabled: {{ .values.ciliumEgressGatewayEnabled }}
                {{- if hasKey .values "externalIP" }}
                  externalIP: '{{ .values.externalIP }}'
                  egressIP: '{{ .values.egressIP }}'
                {{- end }}

                rtpengine:
                  media:
                    address: '{{ .values.rtpengineMediaAddress }}'
                    min: {{ .values.rtpengineMediaPortMin }}
                    max: {{ .values.rtpengineMediaPortMax }}

                serviceOptions:
                {{- if hasKey .values "serviceOptions" }}
                {{- with .values.serviceOptions }}
                {{- toYaml . | nindent 2 }}
                {{- end }}
                {{- end }}
                {{- if eq .values.region "yxl" }}
                {{- toYaml (dict "rtpengine-media" (dict "annotations" (dict "purelb.io/addresses" .values.rtpengineMediaAddress "purelb.io/allow-local" "true" "purelb.io/service-group" "core-public"))) | nindent 2 }}
                {{- else if eq .values.region "yvr" }}
                {{- toYaml (dict "rtpengine-media" (dict "loadBalancerClass" "kube-vip.io/kube-vip-class" "annotations" (dict "kube-vip.io/forwardUPNP" "true"))) | nindent 2 }}
                {{- end }}

                {{- if eq .values.type "spoke" }}
                hub:
                  cluster:
                    name: '{{ .values.hubCluster }}'
                    datacenter: '{{ .values.hubDatacenter }}'
                    region: '{{ .values.hubRegion }}'
                {{- end }}

                gateway:
                  name: 'main-gw'
                  namespace: 'core-{{ .values.environment }}'
                  sectionName: 'https-myloginspace'

                jitsi:
                  domain: 'meet.mylogin.space'
                  tls:
                    secretName: 'myloginspace-default-certificates'

      destination:
        server: '{{ .server }}'
        namespace: 'core-{{ .values.environment }}'
