apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 'core-backplane-business-avoip'
  namespace: 'argocd'

  annotations:
    argocd.argoproj.io/sync-wave: '20'

spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'

  generators:
    - merge:
        mergeKeys:
          - 'name'

        generators:
          - matrix:
              generators:
                - list:
                    elements:
                      - tenant: 'core.mylogin.space'
                        clusters:
                          - name: 'core-dc1-talos-prod'
                            values:
                              type: 'hub'
                              hubCluster: 'core-dc1-talos-prod'
                              hubDatacenter: 'dc1'
                              hubRegion: 'yxl'
                              rtpengineMediaAddress: '66.165.222.103'
                              rtpengineMediaPortMin: 11000
                              rtpengineMediaPortMax: 11300
                              asteriskEnabled: true
                              freeswitchEnabled: true
                              externalIP: '66.165.222.103'
                              faxDID: '<path:CORE0_SITE1/data/AVoIP/YXL/DC1#FaxNumber>'
                              avoipDID: '<path:CORE0_SITE1/data/AVoIP/YXL/DC1#AVoIPNumber>'
                              egressIP: '66.165.222.103'
                              ciliumEgressGatewayEnabled: false
                              kamailio:
                                enabled: true
                                publicExposure:
                                  enabled: true
                                  sip:
                                    enabled: true
                                    tcpEnabled: true
                                    udpEnabled: false
                                    directService:
                                      enabled: false
                                    udpRoute:
                                      enabled: false
                              serviceOptions:
                                kamailio-pub:
                                  type: 'LoadBalancer'
                                  labels:
                                    wan-mode: 'public'
                                    lan-mode: 'private'
                                  annotations:
                                    purelb.io/allow-local: 'true'
                                    purelb.io/service-group: 'core-public'
                                  loadBalancerClass: ''
                          - name: 'core-home1-talos-prod'
                            values:
                              type: 'spoke'
                              hubCluster: 'core-dc1-talos-prod'
                              hubDatacenter: 'dc1'
                              hubRegion: 'yxl'
                              rtpengineMediaAddress: '24.86.197.63'
                              rtpengineMediaPortMin: 11000
                              rtpengineMediaPortMax: 11280
                              asteriskEnabled: true
                              asterisk:
                                sipCore:
                                  enabled: true
                                  hostname: 'sipcore.mylogin.space'
                                  gatewaySectionName: 'https-myloginspace'

                                  allowedOrigins:
                                    - 'https://home.mylogin.space'

                                  httpPort: 8088
                                  kamailioInstance: 'internal'
                                  ingressKamailioInstance: 'internal-websocket'
                                  echoExtension: '9090'

                                  secretStoreRef:
                                    kind: 'ClusterSecretStore'
                                    name: 'corevault-rootsecrets'

                                  extensions:
                                    - number: '7101'
                                      maxContacts: 2
                                      secret:
                                        remoteKey: 'AVoIP/SIPCore/YVR/Home1/7101'
                                        property: 'Password'

                                      allowCallsTo:
                                        - '9090'
                                        - '66'
                                        - '1234'
                              freeswitchEnabled: true
                              faxDID: '<path:CORE0_SITE1/data/AVoIP/YVR/Home1#FaxNumber>'
                              avoipDID: '<path:CORE0_SITE1/data/AVoIP/YVR/Home1#AVoIPNumber>'
                              ciliumEgressGatewayEnabled: false
                              kamailio:
                                enabled: true
                                publicExposure:
                                  enabled: true

                                  sip:
                                    udpEnabled: true
                                    directService:
                                      enabled: true
                                instances:
                                  - name: 'carrier'
                                    enabled: true
                                    role: 'carrier-sbc'
                                    replicas: 3
                                    publicExposure:
                                      enabled: true
                                      sip:
                                        udpEnabled: false
                                        directService:
                                          enabled: false
                                  - name: 'internal'
                                    enabled: true
                                    role: 'private-sbc'
                                    replicas: 1
                                    registrar:
                                      database:
                                        enabled: true
                                        host: 'psql-int.core-home1-talos-prod.home1.yvr.mylogin.space'
                                        username: 'kamailio-internal'
                                        secretName: 'avoip-kamailio-internal-registrar-db'
                                    topology:
                                      redis:
                                        database: 52
                                        secretName: 'avoip-kamailio-internal-topos'
                                  - name: 'internal-websocket'
                                    enabled: true
                                    role: 'private-sbc'
                                    replicas: 3
                                    topology:
                                      redis:
                                        database: 53
                                        secretName: 'avoip-kamailio-internal-ws-topos'
                                    websocketHA:
                                      enabled: true
                                      pilot: true
                                      compatibility:
                                        lfOnlyHeartbeat:
                                          enabled: true
                                          image:
                                            repository: 'slop.writemy.codes/core/core-business/kamailio-lf-heartbeat'
                                            tag: '6.1.4-lf-heartbeat-5264324a63deaa38db2d0bba0d973d8296683899'
                                            digest: 'sha256:5eb5f47706f13edd4a9db90b1670c12c2354476d7eff8c08e748876cadec3545'
                              serviceOptions:
                                kamailio-pub:
                                  type: 'LoadBalancer'
                                  labels:
                                    wan-mode: 'public'
                                    lan-mode: 'private'
                                  annotations:
                                    kube-vip.io/forwardUPNP: 'true'
                                  loadBalancerClass: 'kube-vip.io/kube-vip-class'
                          - name: 'dc1-k3s-node1'
                            values:
                              type: 'spoke'
                              hubCluster: 'core-dc1-talos-prod'
                              hubDatacenter: 'dc1'
                              hubRegion: 'yxl'
                              rtpengineMediaAddress: '66.165.222.103'
                              rtpengineMediaPortMin: 11000
                              rtpengineMediaPortMax: 11250
                              asteriskEnabled: false
                              freeswitchEnabled: false
                              ciliumEgressGatewayEnabled: false

                - list:
                    elementsYaml: '{{ .clusters | toJson }}'

          - clusters:
              selector:
                matchLabels:
                  mylogin.space/tenant: 'core.mylogin.space'
                  resolvemy.host/env: 'prod'
              values:
                clusterName: '{{ .name }}'
                environment: '{{ index .metadata.labels "resolvemy.host/env" }}'
                clusterDomain: '{{ index .metadata.labels "cluster.kubernetes.io/domain" }}'
                tenant: '{{ index .metadata.labels "mylogin.space/tenant" }}'
                region: '{{ index .metadata.labels "topology.kubernetes.io/region" }}'
                zone: '{{ index .metadata.labels "topology.kubernetes.io/zone" }}'
                datacenter: '{{ index .metadata.labels "resolvemy.host/dc" }}'

  syncPolicy:
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: '{{ if eq .values.clusterName "dc1-k3s-node1" }}{{ .values.clusterName }}-business-avoip{{ else }}{{ .values.clusterName }}-business-avoip-{{ .values.environment }}{{ end }}'

      annotations:
        argocd.argoproj.io/manifest-generate-paths: '.'

      labels:
        resolvemy.host/env: '{{ .values.environment }}'

    spec:
      project: 'core'

      syncPolicy:
        syncOptions:
          - 'CreateNamespace=true'
          - 'ServerSideApply=true'

      source:
        repoURL: 'https://slop.writemy.codes/CoRE/CoRE-Business.git'
        path: 'AVoIP'
        targetRevision: 'HEAD'

        plugin:
          name: 'argocd-lovely-plugin'
          env:
            - name: 'LOVELY_HELM_MERGE'
              value: |- # yaml
                env: '{{ .values.environment }}'

                datacenter: '{{ .values.datacenter }}'

                region: '{{ .values.region }}'

                cluster:
                  name: '{{ .values.clusterName }}'
                  domain: '{{ .values.clusterDomain }}'
                  type: '{{ .values.type }}'

                asterisk:
                {{- if hasKey .values "asterisk" }}
                {{- with .values.asterisk }}
                {{- toYaml . | nindent 2 }}
                {{- end }}
                {{- end }}
                  enabled: {{ .values.asteriskEnabled }}

                freeswitch:
                  enabled: {{ .values.freeswitchEnabled }}
                  fax:
                    ident: '{{ upper .values.region }}-CoRE'
                    g711Only:
                      enabled: {{ eq .values.region "yvr" }}

                talkHpb:
                  enabled: {{ eq .values.region "yvr" }}
                  clusterName: '{{ .values.clusterName }}'

                livekit:
                  enabled: {{ eq .values.region "yvr" }}
                  hostname: 'livekit-{{ .values.region }}.mylogin.space'
                  redis:
                    remoteRef:
                      key: 'Storage/DragonFly/CoRE/{{ .values.region }}/{{ .values.datacenter }}/{{ .values.clusterName }}/Creds'
                  media:
                    service:
                      loadBalancerClass: '{{ if eq .values.region "yvr" }}kube-vip.io/kube-vip-class{{ end }}'
                      annotations:
                        kube-vip.io/forwardUPNP: 'true'

                livekit-server:
                  livekit:
                    redis:
                      address: 'dragonfly.{{ .values.clusterName }}.{{ .values.datacenter }}.{{ .values.region }}.mylogin.space:6379'
                      tls:
                        server_name: 'dragonfly.{{ .values.clusterName }}.{{ .values.datacenter }}.{{ .values.region }}.mylogin.space'

                {{- if hasKey .values "faxDID" }}
                fax:
                  did: '{{ .values.faxDID }}'
                {{- end }}

                {{- if hasKey .values "avoipDID" }}
                avoip:
                  did: '{{ .values.avoipDID }}'
                {{- end }}

                kamailio:
                {{- if hasKey .values "kamailio" }}
                {{- with .values.kamailio }}
                {{- toYaml . | nindent 2 }}
                {{- end }}
                {{- end }}
                  advertisedHost: 'sip.{{ .values.clusterName }}.{{ .values.datacenter }}.{{ .values.region }}.resolvemy.host'

                network:
                  ciliumEgressGateway:
                    enabled: {{ .values.ciliumEgressGatewayEnabled }}
                {{- if hasKey .values "externalIP" }}
                  externalIP: '{{ .values.externalIP }}'
                  egressIP: '{{ .values.egressIP }}'
                {{- end }}

                rtpengine:
                  media:
                    address: '{{ .values.rtpengineMediaAddress }}'
                    min: {{ .values.rtpengineMediaPortMin }}
                    max: {{ .values.rtpengineMediaPortMax }}

                serviceOptions:
                {{- if hasKey .values "serviceOptions" }}
                {{- with .values.serviceOptions }}
                {{- toYaml . | nindent 2 }}
                {{- end }}
                {{- end }}
                {{- if eq .values.region "yxl" }}
                {{- toYaml (dict "rtpengine-media" (dict "annotations" (dict "purelb.io/addresses" .values.rtpengineMediaAddress "purelb.io/allow-local" "true" "purelb.io/service-group" "core-public"))) | nindent 2 }}
                {{- else if eq .values.region "yvr" }}
                {{- toYaml (dict "rtpengine-media" (dict "loadBalancerClass" "kube-vip.io/kube-vip-class" "annotations" (dict "kube-vip.io/forwardUPNP" "true"))) | nindent 2 }}
                {{- end }}

                {{- if eq .values.type "spoke" }}
                hub:
                  cluster:
                    name: '{{ .values.hubCluster }}'
                    datacenter: '{{ .values.hubDatacenter }}'
                    region: '{{ .values.hubRegion }}'
                {{- end }}

                gateway:
                  name: 'main-gw'
                  namespace: 'core-{{ .values.environment }}'
                  sectionName: 'https-myloginspace'

                jitsi:
                  domain: 'meet.mylogin.space'
                  tls:
                    secretName: 'myloginspace-default-certificates'

      destination:
        server: '{{ .server }}'
        namespace: 'core-{{ .values.environment }}'
