global:
  timezone: 'America/Vancouver'
  nameOverride: 'photos'
  fullnameOverride: 'photos'

mlrunners:
  - name: 'cuda'
    type: 'cuda'
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: 'nvidia.com/gpu.count'
                  operator: 'Gt'
                  values:
                    - '0'
    tolerations:
      - operator: 'Exists'
    resources:
      limits:
        'nvidia.com/gpu': '1'
  - name: 'intel'
    type: 'intel'
    nodeSelector:
      'kubernetes.io/hostname': 'laptop2'

pubgateway:
  name: 'main-gw'
  namespace: 'core-prod'
  sectionName: 'https-myloginspace'

authentik:
  autoconfigure: true

  application:
    displayName: 'Immich Photos'
    externalHost: 'https://photos.mylogin.space'
    group: 'Media'

  accessGroups:
    - 'Media Consumers'

  route:
    enabled: true
    backend:
      name: 'aaa-myloginspace-proxy'
      namespace: 'core-prod'
      port: 80

immich:
  version: 'v3.2.2'
  smartSearch:
    modelName: 'ViT-B-16-SigLIP2__webli'
  persistence:
    library:
      existingClaim: 'photos-library'
