apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-config
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
spec:
  refreshInterval: 1800s
  secretStoreRef:
    {{- toYaml .Values.externalSecret | nindent 4 }}

  target:
    name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-config
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-config
            items:
              - key: unsealConfig.yaml

  data:
    - secretKey: UNSEAL1
      remoteRef:
        key: COREVAULT_KEYS
        property: UNSEALKEY-1
 
    - secretKey: UNSEAL2
      remoteRef:
        key: COREVAULT_KEYS
        property: UNSEALKEY-2

    - secretKey: UNSEAL3
      remoteRef:
        key: COREVAULT_KEYS
        property: UNSEALKEY-3

    - secretKey: UNSEAL4
      remoteRef:
        key: COREVAULT_KEYS
        property: UNSEALKEY-4
