apiVersion: v1
kind: Namespace
metadata:
  name: k8gb
  annotations:
    argocd.argoproj.io/sync-wave: '-2'
  labels:
    app.kubernetes.io/part-of: core-network-global
    kubernetes.io/metadata.name: k8gb
spec:
  finalizers:
    - kubernetes
