{{- if .Values.harbor.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 'harbor-redis-config'
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: 'corevault-rootsecrets'
    kind: ClusterSecretStore
  target:
    name: 'harbor-redis-config'
    template:
      engineVersion: 'v2'
      data:
        REDIS_PASSWORD: '{{ `{{ .password }}` }}'
        _REDIS_URL_CORE: 'rediss://default:{{ `{{ .password }}` }}@{{ .Values.harbor.redis.external.addr }}/{{ .Values.harbor.redis.external.coreDatabaseIndex }}?idle_timeout_seconds=30'
        _REDIS_URL_REG: 'rediss://default:{{ `{{ .password }}` }}@{{ .Values.harbor.redis.external.addr }}/{{ .Values.harbor.redis.external.registryDatabaseIndex }}?idle_timeout_seconds=30'
        _REDIS_URL_HARBOR: 'rediss://default:{{ `{{ .password }}` }}@{{ .Values.harbor.redis.external.addr }}/{{ .Values.harbor.redis.external.harborDatabaseIndex }}?idle_timeout_seconds=30'
        _REDIS_URL_CACHE_LAYER: 'rediss://default:{{ `{{ .password }}` }}@{{ .Values.harbor.redis.external.addr }}/{{ .Values.harbor.redis.external.cacheLayerDatabaseIndex }}?idle_timeout_seconds=30'
        HARBOR_REDIS_URL: 'rediss://default:{{ `{{ .password }}` }}@{{ .Values.harbor.redis.external.addr }}/{{ .Values.harbor.redis.external.jobserviceDatabaseIndex }}'
        config.yml: |
          protocol: 'http'
          port: 8080
          worker_pool:
            workers: 10
            backend: 'redis'
            redis_pool:
              redis_url: 'rediss://default:{{ `{{ .password }}` }}@{{ .Values.harbor.redis.external.addr }}/{{ .Values.harbor.redis.external.jobserviceDatabaseIndex }}'
              namespace: 'harbor_job_service_namespace'
              idle_timeout_second: 3600
          job_loggers:
            - name: 'STD_OUTPUT'
              level: 'INFO'
          metric:
            enabled: false
            path: '/metrics'
            port: 8001
          loggers:
            - name: 'STD_OUTPUT'
              level: 'INFO'
          reaper:
            max_update_hours: 24
            max_dangling_hours: 168
  data:
    - secretKey: 'password'
      remoteRef:
        key: 'Storage/DragonFly/CoRE/{{ .Values.region }}/{{ .Values.datacenter }}/{{ .Values.cluster.name }}/Creds'
        property: 'Password'
{{- end }}
