{{- if .Values.harbor.enabled }}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: 'harbor-oidc'
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  length: 64
  digits: 12
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 'harbor-oidc'
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshPolicy: 'CreatedOnce'
  target:
    name: 'harbor-oidc'
    template:
      engineVersion: 'v2'
      data:
        client_id: 'harbor-{{ .Values.cluster.name }}'
        client_secret: '{{ `{{ .password }}` }}'
        terraform.tfvars.json: |-
          {
            "client_secret": "{{ `{{ .password }}` }}"
          }
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: 'harbor-oidc'
{{- end }}
