{{- if and .Values.harbor.enabled .Values.harbor.adminCredential.vaultKey }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 'harbor-admin'
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: 'mainvault-core'
    kind: ClusterSecretStore
  target:
    name: 'harbor-admin'
  data:
    - secretKey: 'password'
      remoteRef:
        key: {{ .Values.harbor.adminCredential.vaultKey | quote }}
        property: 'Password'
{{- end }}
