apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: 'ha-core-dev-{{ .Values.env }}'
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  dataEngine: 'v1'
  dataLocality: 'disabled'
  disableRevisionCounter: 'true'
  fsType: 'ext4'
  migratable: 'false'
  numberOfReplicas: '2'
  staleReplicaTimeout: '30'
