apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 'core-backplane-business-vaultwarden'
  namespace: 'argocd'

  labels:
    resolvemy.host/env: 'prod'

spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'

  generators:
    - merge:
        mergeKeys:
          - 'name'

        generators:
          - list:
              elements:
                - name: 'dc1-k3s-node1'
                  values:
                    hub: true
                    psqlProvider: 'psql-dc1-yxl'

                - name: 'core-dc1-talos-prod'
                  values:
                    hub: false
                    psqlProvider: 'psql-dc1-yxl'

                - name: 'core-home1-talos-prod'
                  values:
                    hub: false
                    psqlProvider: 'psql-home1-yvr'

          - clusters:
              selector:
                matchLabels:
                  mylogin.space/tenant: 'core.mylogin.space'
                  resolvemy.host/env: 'prod'

              values:
                clusterName: '{{ .name }}'
                environment: '{{ index .metadata.labels "resolvemy.host/env" }}'
                region: '{{ index .metadata.labels "topology.kubernetes.io/region" }}'
                datacenter: '{{ index .metadata.labels "resolvemy.host/dc" }}'

  syncPolicy:
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: '{{ .values.clusterName }}-business-passwords-vaultwarden'

      annotations:
        argocd.argoproj.io/manifest-generate-paths: '.'

      labels:
        resolvemy.host/env: '{{ .values.environment }}'
        resolvemy.host/priority: 'critical'

    spec:
      project: 'core'

      syncPolicy:
        syncOptions:
          - 'ServerSideApply=true'

      source:
        repoURL: 'https://github.com/K-FOSS/CoRE-Business.git'
        path: 'Passwords/VaultWarden'
        targetRevision: 'HEAD'

        plugin:
          name: 'argocd-lovely-plugin'
          env:
            - name: 'LOVELY_HELM_MERGE'
              value: |- # yaml
                env: '{{ .values.environment }}'

                cluster:
                  name: '{{ .values.clusterName }}'

                datacenter: '{{ .values.datacenter }}'

                region: '{{ .values.region }}'

                vaultwarden:
                  enabled: true

                  psql:
                    host: 'psql.{{ .values.clusterName }}.{{ .values.datacenter }}.{{ .values.region }}.mylogin.space'
                    crossplaneProvider: '{{ .values.psqlProvider }}'
                    terraformProvider: '{{ .values.psqlProvider }}'

                  user:
                    enabled: {{ .values.hub }}
                    hubCluster: 'dc1-k3s-node1'

      destination:
        server: '{{ .server }}'
        namespace: 'core-{{ .values.environment }}'
