apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 'photos-dragonfly-password'
spec:
  refreshPolicy: 'Periodic'
  refreshInterval: '1h'
  secretStoreRef:
    kind: ClusterSecretStore
    name: 'corevault-rootsecrets'
  target:
    creationPolicy: 'Owner'
    name: 'dragonfly-core-password'
  data:
    - secretKey: 'password'
      remoteRef:
        key: 'Storage/DragonFly/CoRE/{{ .Values.region }}/{{ .Values.datacenter }}/{{ .Values.cluster.name }}/Creds'
        property: 'Password'
