apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 'photos-library'
spec:
  accessModes:
    - 'ReadWriteMany'
  storageClassName: 'photos-library'
  resources:
    requests:
      storage: '50Gi'
