apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: 'photos-oidc'
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  length: 64
  digits: 12
  symbols: 0
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 'photos-oidc'
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  refreshPolicy: 'CreatedOnce'
  target:
    name: 'photos-oidc'
    template:
      engineVersion: 'v2'
      data:
        client_secret: '{{ `{{ .password }}` }}'
        terraform.tfvars.json: |-
          {
            "client_secret": "{{ `{{ .password }}` }}"
          }
        immich-config.yaml: |-
          oauth:
            enabled: true
            issuerUrl: 'https://idp.mylogin.space/application/o/photos-oidc/'
            clientId: 'photos'
            clientSecret: '{{ `{{ .password }}` }}'
            scope: 'openid email profile'
            tokenEndpointAuthMethod: 'client_secret_post'
            signingAlgorithm: 'RS256'
            profileSigningAlgorithm: 'none'
            autoRegister: true
            autoLaunch: false
            buttonText: 'Sign in with Authentik'
            storageLabelClaim: 'preferred_username'
            roleClaim: 'immich_role'
            mobileOverrideEnabled: false
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: 'photos-oidc'
