apiVersion: v2
version: 1.0.0
name: core-media-comics

dependencies:
  # Common library documentation: https://bjw-s-labs.github.io/helm-charts/docs/common-library/introduction/
  - name: common
    version: 5.0.1
    repository: https://bjw-s-labs.github.io/helm-charts/
