apiVersion: v2
name: 'core-storage-s3-garage-operator'
description: 'YXL Garage Kubernetes operator and CRDs'
type: application
version: 1.0.0
dependencies:
  - name: garage-operator
    version: 0.8.1
    repository: 'oci://ghcr.io/rajsinghtech/charts'
    condition: garage-operator.enabled
