cert-manager:
  fullnameOverride: cert-manager

  crds:
    enabled: true

  enableCertificateOwnerRef: true

  config:
    apiVersion: controller.config.cert-manager.io/v1alpha1
    kind: ControllerConfiguration
    logging:
      verbosity: 2
      format: json
    featureGates:
      AdditionalCertificateOutputFormats: true
      ExperimentalGatewayAPISupport: true
      ServerSideApply: true

  prometheus:
    enabled: false

  webhook:
    config:
      apiVersion: webhook.config.cert-manager.io/v1alpha1
      kind: WebhookConfiguration
      featureGates:
        AdditionalCertificateOutputFormats: true
