apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: natpuncher-turn-auth
spec:
  length: 42
  digits: 5
  symbols: 5
  symbolCharacters: '-_$'
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: natpuncher-turn-auth
spec:
  refreshPolicy: CreatedOnce
  target:
    name: natpuncher-turn-auth

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: natpuncher-turn-auth
