apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: natpuncher-turn-auth

spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: corevault-rootsecrets
      kind: ClusterSecretStore

  selector:
    secret:
      name: natpuncher-turn-auth

  data:
    - match:
        secretKey: 'secret'
        remoteRef:
          remoteKey: 'Network/NATPuncher/{{ .Values.region }}/{{ .Values.datacenter }}/{{ .Values.cluster.name }}/TurnAuth'
          property: 'Secret'
