apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: core-kafka
  annotations:
    argocd.argoproj.io/sync-wave: '10'

spec:
  kafka:
    replicas: 3
    template:
      pod:
        metadata:
          annotations:
            secret.reloader.stakater.com/reload: 'core-kafka-oidc'
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: 'strimzi.io/name'
                      operator: 'In'
                      values:
                        - 'core-kafka-kafka'
                topologyKey: 'kubernetes.io/hostname'
    resources:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    listeners:
      {{- if .Values.oidc.enabled }}
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: oauth
          enablePlain: true
          tokenEndpointUri: '{{ .Values.oidc.authentikUrl }}/application/o/token/'
          accessTokenIsJwt: true
          checkAccessTokenType: false
          clientId: core-kafka
          clientScope: openid profile email
          validIssuerUri: '{{ .Values.oidc.authentikUrl }}/application/o/{{ .Values.oidc.applicationSlug }}/'
          jwksEndpointUri: '{{ .Values.oidc.authentikUrl }}/application/o/{{ .Values.oidc.applicationSlug }}/jwks/'
          userNameClaim: 'preferred_username'
          maxSecondsWithoutReauthentication: 3600
          connectTimeoutSeconds: 10
          readTimeoutSeconds: 10
          httpRetries: 3
          httpRetryPauseMs: 500
      {{- if .Values.external.enabled }}
      - name: external
        port: 9094
        type: 'cluster-ip'
        tls: true
        authentication:
          type: oauth
          enablePlain: true
          tokenEndpointUri: '{{ .Values.oidc.authentikUrl }}/application/o/token/'
          accessTokenIsJwt: true
          checkAccessTokenType: false
          clientId: core-kafka
          clientScope: openid profile email
          validIssuerUri: '{{ .Values.oidc.authentikUrl }}/application/o/{{ .Values.oidc.applicationSlug }}/'
          jwksEndpointUri: '{{ .Values.oidc.authentikUrl }}/application/o/{{ .Values.oidc.applicationSlug }}/jwks/'
          userNameClaim: 'preferred_username'
          maxSecondsWithoutReauthentication: 3600
          connectTimeoutSeconds: 10
          readTimeoutSeconds: 10
          httpRetries: 3
          httpRetryPauseMs: 500
        configuration:
          brokerCertChainAndKey:
            secretName: '{{ .Values.external.tls.secretName }}'
            certificate: '{{ .Values.external.tls.certificate }}'
            key: '{{ .Values.external.tls.key }}'
          bootstrap:
            annotations:
              external-dns.alpha.kubernetes.io/hostname: '{{ .Values.external.hostname }}'
            labels:
              wan-mode: 'public'
          brokers:
            - broker: 0
              advertisedHost: '{{ index .Values.external.brokerHostnames 0 }}'
              advertisedPort: 9094
              annotations:
                external-dns.alpha.kubernetes.io/hostname: '{{ index .Values.external.brokerHostnames 0 }}'
              labels:
                wan-mode: 'public'
            - broker: 1
              advertisedHost: '{{ index .Values.external.brokerHostnames 1 }}'
              advertisedPort: 9094
              annotations:
                external-dns.alpha.kubernetes.io/hostname: '{{ index .Values.external.brokerHostnames 1 }}'
              labels:
                wan-mode: 'public'
            - broker: 2
              advertisedHost: '{{ index .Values.external.brokerHostnames 2 }}'
              advertisedPort: 9094
              annotations:
                external-dns.alpha.kubernetes.io/hostname: '{{ index .Values.external.brokerHostnames 2 }}'
              labels:
                wan-mode: 'public'
      {{- end }}
      {{- else }}
      - name: plain
        port: 9092
        type: internal
        tls: false
      {{- end }}

    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 10G
          deleteClaim: false

    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      unclean.leader.election.enable: false
      auto.create.topics.enable: false
  zookeeper:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    storage:
      type: persistent-claim
      size: 10G
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
