{{- if and .Values.oidc.enabled .Values.oidc.secretSync.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: 'core-kafka-oidc-vault'
  annotations:
    argocd.argoproj.io/sync-wave: '6'
spec:
  updatePolicy: 'Replace'
  deletionPolicy: 'None'
  refreshInterval: '5m'
  secretStoreRefs:
    - name: {{ .Values.oidc.secretSync.secretStoreName | squote }}
      kind: 'ClusterSecretStore'
  selector:
    secret:
      name: 'core-kafka-oidc'
  data:
    - match:
        secretKey: 'client_id'
        remoteRef:
          remoteKey: {{ .Values.oidc.secretSync.remoteKey | squote }}
          property: 'client_id'
    - match:
        secretKey: 'client_secret'
        remoteRef:
          remoteKey: {{ .Values.oidc.secretSync.remoteKey | squote }}
          property: 'client_secret'
    - match:
        secretKey: 'issuer_url'
        remoteRef:
          remoteKey: {{ .Values.oidc.secretSync.remoteKey | squote }}
          property: 'issuer_url'
    - match:
        secretKey: 'jwks_url'
        remoteRef:
          remoteKey: {{ .Values.oidc.secretSync.remoteKey | squote }}
          property: 'jwks_url'
{{- end }}
{{- if and .Values.oidc.enabled .Values.ui.enabled .Values.ui.oidc.secretSync.enabled }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: 'core-kafka-ui-oidc-vault'
  annotations:
    argocd.argoproj.io/sync-wave: '6'
spec:
  updatePolicy: 'Replace'
  deletionPolicy: 'None'
  refreshInterval: '5m'
  secretStoreRefs:
    - name: {{ .Values.ui.oidc.secretSync.secretStoreName | squote }}
      kind: 'ClusterSecretStore'
  selector:
    secret:
      name: 'core-kafka-ui-oidc'
  data:
    - match:
        secretKey: 'client_id'
        remoteRef:
          remoteKey: {{ .Values.ui.oidc.secretSync.remoteKey | squote }}
          property: 'client_id'
    - match:
        secretKey: 'client_secret'
        remoteRef:
          remoteKey: {{ .Values.ui.oidc.secretSync.remoteKey | squote }}
          property: 'client_secret'
    - match:
        secretKey: 'issuer_url'
        remoteRef:
          remoteKey: {{ .Values.ui.oidc.secretSync.remoteKey | squote }}
          property: 'issuer_url'
{{- end }}
