apiVersion: v2
version: 1.0.0
name: core-media-common

dependencies:
  # Common library documentation: https://bjw-s-labs.github.io/helm-charts/docs/common-library/introduction/
  # 5.0.1 release notes: https://github.com/bjw-s-labs/helm-charts/releases/tag/common-5.0.1
  - name: common
    version: 5.0.1
    repository: https://bjw-s-labs.github.io/helm-charts/
