k8gb:
  k8gb:
    deployCrds: true
    installLegacyCrds: false
    dnsZones: []
    extGslbClustersGeoTags: ''
    exposeMetrics: true
    serviceMonitor:
      enabled: true
    resources:
      requests:
        cpu: '100m'
        memory: '64Mi'
      limits:
        cpu: '500m'
        memory: '256Mi'

  extdns:
    enabled: false

  coredns:
    serviceType: 'ClusterIP'

  istio:
    enabled: false

  gatewayapi:
    enabled: true
