apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "talos-image-factory.name" . }}'
  labels:
    {{- include "talos-image-factory.labels" . | nindent 4 }}
data:
  config.yaml: |-
    artifacts:
      core:
        registry: '{{ .Values.imageFactory.artifacts.registry }}'
        namespace: '{{ .Values.imageFactory.artifacts.namespace }}'
        insecure: {{ .Values.imageFactory.artifacts.insecure }}
        components:
          installerBase: '{{ .Values.imageFactory.artifacts.components.installerBase }}'
          installer: '{{ .Values.imageFactory.artifacts.components.installer }}'
          imager: '{{ .Values.imageFactory.artifacts.components.imager }}'
          extensionManifest: '{{ .Values.imageFactory.artifacts.components.extensionManifest }}'
          overlayManifest: '{{ .Values.imageFactory.artifacts.components.overlayManifest }}'
          talosctl: '{{ .Values.imageFactory.artifacts.components.talosctl }}'
      schematic:
        registry: '{{ .Values.imageFactory.artifacts.registry }}'
        namespace: '{{ .Values.imageFactory.artifacts.namespace }}'
        repository: '{{ .Values.imageFactory.artifacts.schematic.repository }}'
        insecure: {{ .Values.imageFactory.artifacts.insecure }}
      installer:
        internal:
          registry: '{{ .Values.imageFactory.artifacts.registry }}'
          namespace: '{{ .Values.imageFactory.artifacts.namespace }}'
          repository: '{{ .Values.imageFactory.artifacts.installer.internalRepository }}'
          insecure: {{ .Values.imageFactory.artifacts.insecure }}
        external:
          registry: '{{ .Values.imageFactory.artifacts.registry }}'
          namespace: '{{ .Values.imageFactory.artifacts.namespace }}'
          repository: '{{ .Values.imageFactory.artifacts.installer.externalRepository }}'
          insecure: {{ .Values.imageFactory.artifacts.insecure }}
    cache:
      s3:
        enabled: true
        bucket: '{{ .Values.imageFactory.s3.bucket }}'
        region: '{{ .Values.imageFactory.s3.region }}'
        endpoint: 's3.{{ .Values.cluster.name }}.{{ .Values.datacenter }}.{{ .Values.region }}.mylogin.space'
        insecure: false
      signingKeyPath: '/etc/image-factory/keys/cache-signing.key'
    http:
      externalURL: 'https://tfactory.{{ .Values.cluster.name }}.{{ .Values.datacenter }}.{{ .Values.region }}.writemy.codes/'
      externalPXEURL: 'https://tfactory.{{ .Values.cluster.name }}.{{ .Values.datacenter }}.{{ .Values.region }}.writemy.codes/'
      httpListenAddr: '0.0.0.0:8080'
