apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 'talos-image-factory-registry'
spec:
  refreshPolicy: 'Periodic'
  refreshInterval: '1h'
  secretStoreRef:
    kind: 'ClusterSecretStore'
    name: 'corevault-rootsecrets'
  target:
    creationPolicy: 'Owner'
    name: 'talos-image-factory-registry'
    template:
      type: 'kubernetes.io/dockerconfigjson'
      engineVersion: 'v2'
      data:
        .dockerconfigjson: |-
          {
            "auths": {
              "{{ .Values.imageFactory.artifacts.registry }}": {
                "auth": {{`{{ printf "%s:%s" .Username .Token | b64enc | quote }}`}}
              }
            }
          }
  data:
    - secretKey: 'Username'
      remoteRef:
        key: 'Talos/ImageFactory/Registry'
        property: 'Username'
    - secretKey: 'Token'
      remoteRef:
        key: 'Talos/ImageFactory/Registry'
        property: 'Token'
