apiVersion: v1
kind: Service
metadata:
  name: '{{ include "talos-image-factory.name" . }}'
  labels:
    {{- include "talos-image-factory.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: '{{ include "talos-image-factory.name" . }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
  ports:
    - name: 'http'
      port: 8080
      targetPort: 'http'
      protocol: TCP
