pxc-db:
  finalizers:
    - 'delete-pxc-pods-in-order'

  allowUnsafeConfigurations: true
  updateStrategy: 'RollingUpdate'

  upgradeOptions:
    apply: 'disabled'

  tls:
    SANs:
      - 'mysql.mylogin.space'
    issuerConf:
      name: 'kjdev-cluster'
      kind: ClusterIssuer
      group: 'cert-manager.io'

  pxc:
    expose:
      enabled: false
    priorityClassName: 'tier2-priority'
    configuration: |
      [mysqld]
      plugin-load-add=authentication_ldap_simple.so
      authentication_ldap_simple_server_host='ldap.mylogin.space'
      authentication_ldap_simple_bind_root_dn='cn=mysql,ou=users,dc=ldap,dc=mylogin,dc=space'
      authentication_ldap_simple_bind_root_pwd='<path:CORE0_SITE1/data/MySQL/Credentials#Password>'
      authentication_ldap_simple_bind_base_dn='dc=ldap,dc=mylogin,dc=space'
      authentication_ldap_simple_tls=1
      authentication_ldap_simple_user_search_attr='cn'
    persistence:
      size: '20Gi'
    certManager: true

  haproxy:
    enabled: false

  proxysql:
    serviceType: 'LoadBalancer'
    loadBalancerSourceRanges:
      - '10.0.0.0/8'
    loadBalancerIP: '127.0.0.1'
    serviceAnnotations:
      purelb.io/allow-local: 'true'
      purelb.io/addresses: '10.1.1.37'
      external-dns.alpha.kubernetes.io/hostname: 'mysql.mylogin.space'
    serviceLabels:
      wan-mode: 'public'

  logcollector:
    enabled: false

  backup:
    pitr:
      enabled: true
      storageName: 's3-minio'
      timeBetweenUploads: 60
    storages:
      s3-minio:
        type: 's3'
        s3:
          bucket: 'mysql-backups'
          credentialsSecret: 'mysql-core-minio-s3'
          region: 'us-east-1'
          endpointUrl: 'https://s3.mylogin.space'
