tenant:
  name: example-tenant

volumes:
  enabled: true

  downloads:
    enabled: true

    size: '200001191936'

  media:
    enabled: true

    size: '300001787904'

flaresolverr:
  enabled: true

  image: ghcr.io/flaresolverr/flaresolverr
  tag: latest

  volumes:
    config:
      enabled: true

      size: 5G

bazarr:
  enabled: true

  image: 'lscr.io/linuxserver/bazarr'
  tag: 'latest@sha256:a20fb11a440d704a9d61c283aa26462aad33dc63223b173f8d8c77d33e8e9d59'

  volumes:
    config:
      enabled: true

      size: 5G
