apiVersion: v2
version: 1.1.0

name: core-eventstream

dependencies:
  #
  # Kafka
  #

  - name: strimzi-kafka-operator
    version: 0.45.2
    repository: https://strimzi.io/charts
    condition: strimzi-kafka-operator.enabled

  # Kafka web UI
  - name: kafka-ui
    version: 1.6.5
    repository: https://kafbat.github.io/helm-charts
    condition: kafka-ui.enabled



  
