{{- range $backendIndex, $backend := .Values.backends }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: {{ $backend.name }}
spec:
  type: Endpoints
  {{- with $backend.appProtocols }}
  appProtocols:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  endpoints:
    {{- toYaml (list $backend.endpoint) | nindent 4 }}
---
{{- end }}