apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: quic-window-tuning
  namespace: core-prod
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: main-gw
  type: JSONPatch
  jsonPatches:
    - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
      name: "core-prod/main-gw/https-myloginspace-quic"
      operation:
        op: add
        path: "/udp_listener_config"
        value:
          downstream_socket_config:
            prefer_gro: true
          quic_options: {}
          udp_packet_packet_writer_config:
            name: envoy.udp_packet_writer.gso
            typed_config:
              '@type': >-
                type.googleapis.com/envoy.extensions.udp_packet_writer.v3.UdpGsoBatchWriterFactory