apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: quic-window-tuning
  namespace: core-prod
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: main-gw
  type: JSONPatch
  jsonPatches:
    - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
      name: "core-prod/main-gw/https-myloginspace-quic"
      operation:
        op: add
        path: "/udp_listener_config/downstream_socket_config/prefer_gro"
        value: true