apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: maingw-traffic
  namespace: core-prod

spec:
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
      matchLabels:
        resolvemy.host/gw: 'main-gw'
        resolvemy.host/security: 'public'
        resolvemy.host/env: 'prod'

  connection:
    connectionLimit:
      value: 10000
      closeDelay: 1s
    bufferLimit: 1Mi

  http2:
    initialConnectionWindowSize: 64Mi
    initialStreamWindowSize: 8Mi
    maxConcurrentStreams: 200

  http3: {}

  tls:
    alpnProtocols:
      - h2
      - http/1.1
    ciphers:
      - ECDHE-ECDSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA384
    maxVersion: '1.3'
    minVersion: '1.2'

  path:
    disableMergeSlashes: true
    escapedSlashesAction: KeepUnchanged

  tcpKeepalive:
    idleTime: 5m
    interval: 15s
    probes: 9

  timeout:
    http:
      idleTimeout: 1800s
