apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-{{ .Values.tenant }}
spec:
  shutdown:
    drainTimeout: '120s'
    minDrainDuration: '30s'

  logging:
    level:
      default: error

  mergeGateways: false

  routingType: Service

  provider:
    kubernetes:
      envoyDeployment:
        replicas: 3
        container:
          resources:
            limits:
              cpu: '2'
              memory: '4Gi'
            requests:
              cpu: 16m
              memory: 256Mi
        pod:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: app.kubernetes.io/name
                          operator: In
                          values:
                            - envoy
                    topologyKey: kubernetes.io/hostname
          labels:
            logs: loki-myloginspace

      envoyPDB:
        maxUnavailable: 25%

      envoyService:
        externalTrafficPolicy: Local
        type: LoadBalancer
        loadBalancerClass: purelb.io/purelbv2
        patch:
          type: StrategicMerge
          value:
            spec:
              sessionAffinity: ClientIP
              sessionAffinityConfig:
                clientIP:
                  timeoutSeconds: 21600


    type: Kubernetes

  telemetry:
    accessLog:
      disable: true
    #   settings:
    #     - format:
    #         json:
    #           message: '%LOCAL_REPLY_BODY%'
    #           status: '%RESPONSE_CODE%'
    #         type: JSON
    #       sinks:
    #         - openTelemetry:
    #             backendRefs:
    #               - group: ''
    #                 kind: Service
    #                 name: {{ .Values.cluster.name }}-collectors-alloy
    #                 namespace: core-prod
    #                 port: 4317
    #           type: OpenTelemetry
    # tracing:
    #   provider:
    #     backendRefs:
    #       - group: ''
    #         kind: Service
    #         name: {{ .Values.cluster.name }}-collectors-alloy
    #         namespace: core-prod
    #         port: 4317
    #     type: OpenTelemetry
    #   samplingRate: 10
