apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: main-gw
spec:
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
      matchLabels:
        resolvemy.host/gw: 'main-gw'
        resolvemy.host/security: 'public'
        resolvemy.host/env: 'prod'

  compressor:
    - type: Zstd
      zstd: {}
      minContentLength: 1024
    - type: Brotli
      brotli: {}
      minContentLength: 1024
    - type: Gzip
      gzip: {}
      minContentLength: 1024

  connection:
    bufferLimit: 32Mi

  dns:
    dnsRefreshRate: 3m
    respectDnsTtl: true

  http2:
    initialConnectionWindowSize: 8Mi
    initialStreamWindowSize: 1Mi
    maxConcurrentStreams: 200
    onInvalidMessage: TerminateStream

  tcpKeepalive:
    idleTime: 5m
    interval: 15s
    probes: 9

  timeout:
    tcp:
      connectTimeout: 3s
    http:
      connectionIdleTimeout: 120s
      maxConnectionDuration: 3600s