{{- if .Values.garage.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-bootstrap" .Values.garage.name | squote }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshInterval: '1h'
  secretStoreRef:
    kind: {{ .Values.garage.secretStoreRef.kind | squote }}
    name: {{ .Values.garage.secretStoreRef.name | squote }}
  target:
    name: {{ printf "%s-bootstrap" .Values.garage.name | squote }}
    creationPolicy: 'Owner'
    template:
      type: 'Opaque'
  data:
    - secretKey: 'admin-token'
      remoteRef:
        key: {{ .Values.garage.remoteKey | squote }}
        property: {{ .Values.garage.adminTokenProperty | squote }}
    - secretKey: 'rpc-secret'
      remoteRef:
        key: {{ .Values.garage.remoteKey | squote }}
        property: {{ .Values.garage.rpcSecretProperty | squote }}
{{- end }}
