frr:
  defaultVersion: v8.3.1

routeservers:
  rs0:
    ipAddress: 1.1.1.1

    networking:
      egressGW:
        enabled: false
      interfaces:
        - type: sriov
          mtu: 9000
          routing:
            ospf:
              enabled: true
              area: 0.0.0.0
              type: point-to-point
          ipam:
            address: 10.7.7.61/24
            routes:
              - dst: 0.0.0.0/0
                gw: 10.7.7.1
          sriov:
            vlan: 666
            device: mellanox.com/mlx4_cx3_netdevice

    ospf:
      enabled: true

      autocost:
        refBandwidth: 100000

    bgp:
      enabled: true

      asn: 64567

      clusterId: 172.31.255.1

      afi:
        ipv4:
          unicast:
            neighbor:
              - name: frr-gw
                action: activate

      peers:
        - address: 172.31.192.16
          # remoteASN: ''

          eBGPMultihop: 6

          softReconfiguration: true

          peerGroup: frr-gw

      peerGroups:
        - name: frr-gw
          asn: 64567
          ebgpmultihop: 6
          ipv4:
            enabled: true
            softReconfiguration: true


    frr:
      version: 10.5.1