{{- if .Values.vector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: '{{ include "alloy.fullname" $.Subcharts.alloy }}-syslog'
  annotations:
    {{- toYaml .Values.vector.syslogService.annotations | nindent 4 }}
spec:
  ports:
    {{- toYaml .Values.vector.syslogService.ports | nindent 4 }}
  selector:
    {{- include "vector.selectorLabels" $.Subcharts.vector | nindent 4 }}
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  type: LoadBalancer
{{- end }}
