{{- if .Values.unpoller.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}-unpoller'

spec:
  refreshInterval: '1h'
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

  target:
    name: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}-unpoller'

  data:
    - secretKey: 'username'
      remoteRef:
        key: 'Unifi/Monitoring'
        property: 'Username'
    - secretKey: 'password'
      remoteRef:
        key: 'Unifi/Monitoring'
        property: 'Password'
{{- end }}
