apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}

spec:
  refreshInterval: '1h'
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

  target:
    name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
    template:
      engineVersion: v2
      data:
        DB_MONGO_URI: '{{`mongodb://{{ .Username | urlquery }}:{{ .Password | urlquery }}@core-home1-talos-prod-rs0-0.core-home1-talos-prod-rs0.core-prod.svc.cluster.local:27017,core-home1-talos-prod-rs0-1.core-home1-talos-prod-rs0.core-prod.svc.cluster.local:27017,core-home1-talos-prod-rs0-2.core-home1-talos-prod-rs0.core-prod.svc.cluster.local:27017/unifi?replicaSet=rs0&authMechanism=PLAIN&authSource=external&readPreference=primary`}}'
        STATDB_MONGO_URI: '{{`mongodb://{{ .Username | urlquery }}:{{ .Password | urlquery }}@core-home1-talos-prod-rs0-0.core-home1-talos-prod-rs0.core-prod.svc.cluster.local:27017,core-home1-talos-prod-rs0-1.core-home1-talos-prod-rs0.core-prod.svc.cluster.local:27017,core-home1-talos-prod-rs0-2.core-home1-talos-prod-rs0.core-prod.svc.cluster.local:27017/unifi_stat?replicaSet=rs0&authMechanism=PLAIN&authSource=external&readPreference=primary`}}'
  data:
    - secretKey: Username
      remoteRef:
        key: Unifi/Database
        property: Username
 
    - secretKey: Password
      remoteRef:
        key: Unifi/Database
        property: Password
