{{- if .Values.unpoller.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: '{{ .Release.Name }}-unifi'
  labels:
    app.kubernetes.io/name: '{{ .Release.Name }}-unifi'
    app.kubernetes.io/component: 'monitoring'
spec:
  namespaceSelector:
    matchNames:
      - '{{ .Release.Namespace }}'
  selector:
    matchLabels:
      app.kubernetes.io/component: 'unifi-metrics'
  endpoints:
    - port: 'metrics'
      path: '/metrics'
      interval: '30s'
      scrapeTimeout: '10s'
{{- end }}
