apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}

spec:
  name: Unifi Controller

  username: unifi
 
  psql:
    enabled: false

  mysql:
    enabled: false

  mongodb:
    enabled: true
    replicaSet: 'rs0'
    crossplane:
      terraformProvider: 'mongodb-prod-tf'

    databases:
      - unifi
      - unifi_stat
      - unifi_audit
      - unifi_restore

  groups:
    - LDAPService

  writeConnectionSecretToRef:
    name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-creds
