---
{{- include "bjw-s.common.loader.init" . }}

{{- define "app-template.hardcodedValues" -}}
# Set the nameOverride based on the release name if no override has been set
{{ if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"

{{ end }}

controllers:

{{/* $. is the top-level context.
     $name  -> "rs0", "rs1", ...
     $rs    -> the whole rs0/rs1 map (ipAddress, peers, peerGroups …) */}}
{{- range $name, $rs := .Values.routeservers }}
  {{ $name }}-routeserver:
    # For Deployments, valid values are Recreate (default) and RollingUpdate.
    # For StatefulSets, valid values are OnDelete and RollingUpdate (default).
    # DaemonSets/CronJobs ignore this.
    strategy: RollingUpdate

    nameOverride: {{ $name }}

    {{- $mtuUsed := false -}}
    {{- $sriovUsed := false -}}
    {{- $sriovResources := dict -}}
    {{- range $netID, $netInterface := $rs.networking.interfaces }}
    {{ if .mtu }}
    {{- $mtuUsed = true }}
    {{- end }}
    {{- if eq $netInterface.type "sriov" }}
    {{ $sriovUsed = true }}
    {{- 
      $device := required
          (printf "routeservers.%s.interfaces.%d: sriov.device is required for SR-IOV interfaces" $name $netID)
          $netInterface.sriov.device
    }}
    {{- $currentCount := get $sriovResources $device | default 0 }}
    {{- $_ := set $sriovResources $device (add $currentCount 1) }}
    {{- end }}
    {{- end }}

    {{- if eq $mtuUsed true }}
    initContainers:
      linkconf:
        image:
          repository: alpine
          #
          # TODO: Get Renovate or similar managing this
          #
          tag: '3.20'
          pullPolicy: IfNotPresent

        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: false
          readOnlyRootFilesystem: false
          capabilities:
            add:
              - NET_ADMIN
        
        command:
          - /bin/sh
          - -c
          - |
            {{- range $netID, $netInterface := $rs.networking.interfaces }}
            {{- if $netInterface.mtu }}
            ip link set dev eth{{ $netID }} mtu {{ $netInterface.mtu }}
            ip link show eth{{ $netID }}
            {{- end }}
            {{- end }}
    {{- end }}


    {{- if and $rs.networking $rs.networking.interfaces }}
    pod:
      dnsPolicy: None

      automountServiceAccountToken: false
      
      dnsConfig:
        nameservers:
          - 1.1.1.1
        options:
          - name: ndots
            value: '0'
          - name: edns0
      annotations:
        v1.multus-cni.io/default-network: '{{ $.Release.Namespace }}/{{ include "bjw-s.common.lib.chart.names.fullname" $ }}-0'
    {{- end }}

    containers:
      frr:
        image:
          repository: quay.io/frrouting/frr
          #
          # TODO: Get Renovate or similar managing this
          #
          tag: {{ if and $rs.frr $rs.frr.version }}{{ $rs.frr.version }}{{ else }}{{ $.Values.frr.defaultVersion }}{{ end }}
          pullPolicy: IfNotPresent

        {{- if $sriovUsed }}
        resources:
          limits:
            {{- range $device, $count := $sriovResources }}
            {{ $device }}: {{ $count | quote }}
            {{- end }}
        {{- end }}

        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: false
          readOnlyRootFilesystem: false
          {{- if $rs.ospf.enabled }}
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - SYS_ADMIN
              - NET_BIND_SERVICE
          {{- end }}
          seccompProfile:
            type: "RuntimeDefault"

        # -- Probe configuration
        # -- [[ref]](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)
        # @default -- See below
        probes:
          # -- Liveness probe configuration
          # @default -- See below
          liveness:
            # -- Enable the liveness probe
            enabled: false
            # -- Set this to `true` if you wish to specify your own livenessProbe
            custom: false
            # -- sets the probe type when not using a custom probe
            # @default -- "TCP"
            type: TCP
            # -- The spec field contains the values for the default livenessProbe.
            # If you selected `custom: true`, this field holds the definition of the livenessProbe.
            # @default -- See below
            spec:
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3

          # -- Redainess probe configuration
          # @default -- See below
          readiness:
            # -- Enable the readiness probe
            enabled: false
            # -- Set this to `true` if you wish to specify your own readinessProbe
            custom: false
            # -- sets the probe type when not using a custom probe
            # @default -- "TCP"
            type: TCP
            # -- The spec field contains the values for the default readinessProbe.
            # If you selected `custom: true`, this field holds the definition of the readinessProbe.
            # @default -- See below
            spec:
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3

          # -- Startup probe configuration
          # @default -- See below
          startup:
            # -- Enable the startup probe
            enabled: false
            # -- Set this to `true` if you wish to specify your own startupProbe
            custom: false
            # -- sets the probe type when not using a custom probe
            # @default -- "TCP"
            type: TCP
            # -- The spec field contains the values for the default startupProbe.
            # If you selected `custom: true`, this field holds the definition of the startupProbe.
            # @default -- See below
            spec:
              initialDelaySeconds: 0
              timeoutSeconds: 1
              ## This means it has a maximum of 5*30=150 seconds to start up before it fails
              periodSeconds: 5
              failureThreshold: 30

{{- end }}


service:
  {{- range $name, $rs := .Values.routeservers }}
  {{ $name }}-bgp:
    # -- Enables or disables the service
    enabled: true

    # -- Configure which controller this service should target
    controller: {{ $name }}-routeserver

    # -- Make this the primary service for this controller (used in probes, notes, etc...).
    # If there is more than 1 service targeting the controller, make sure that only 1 service is
    # marked as primary.
    primary: false

    # -- Set the service type
    type: LoadBalancer

    # -- Specify the externalTrafficPolicy for the service. Options: Cluster, Local
    # -- [[ref](https://kubernetes.io/docs/tutorials/services/source-ip/)]
    externalTrafficPolicy:

    # -- Specify the ip policy. Options: SingleStack, PreferDualStack, RequireDualStack
    ipFamilyPolicy:
    # -- The ip families that should be used. Options: IPv4, IPv6
    ipFamilies: []

    # # -- Provide additional annotations which may be required.
    annotations:
      purelb.io/allow-local: 'true'
      purelb.io/addresses: '{{ $rs.ipAddress }}'

    # -- Allow adding additional match labels
    extraSelectorLabels: {}

    ports:
      turn-tcp:
        # -- Enables or disables the port
        enabled: true

        # -- Make this the primary port (used in probes, notes, etc...)
        # If there is more than 1 service, make sure that only 1 port is marked as primary.
        primary: false

        # -- The port number
        port: 179

        # -- Port protocol.
        # Support values are `HTTP`, `HTTPS`, `TCP` and `UDP`.
        # HTTP and HTTPS spawn a TCP service and get used for internal URL and name generation
        protocol: TCP

        # -- Specify the appProtocol value for the Service.
        # [[ref]](https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol)
        appProtocol:
  {{- end }}

configMaps:
configMaps:
{{- range $name, $rs := .Values.routeservers }}
  {{ $name }}-config:
    enabled: true

    data:
      daemons: |
        bgpd={{ if and $rs.bgp $rs.bgp.enabled }}{{ $rs.bgp.enabled }}{{ else }}false{{ end }}
        ospfd={{ if and $rs.ospf $rs.ospf.enabled }}{{ $rs.ospf.enabled }}{{ else }}false{{ end }}
        ospf6d=no
        ripd=no
        ripngd=no
        isisd=no
        pimd=no
        ldpd=no
        nhrpd=no
        eigrpd=no
        babeld=no
        sharpd=no
        pbrd=no
        bfdd=no
        fabricd=no
        vrrpd=no
        pathd=no

        #
        # If this option is set the /etc/init.d/frr script automatically loads
        # the config via "vtysh -b" when the servers are started.
        # Check /etc/pam.d/frr if you intend to use "vtysh"!
        #
        vtysh_enable=yes
        zebra_options="  -A 127.0.0.1 -s 90000000"
        bgpd_options="--no_kernel --skip_runas -A 127.0.0.1"
        ospfd_options="  -A 127.0.0.1"
        ospf6d_options=" -A ::1"
        ripd_options="   -A 127.0.0.1"
        ripngd_options=" -A ::1"
        isisd_options="  -A 127.0.0.1"
        pimd_options="   -A 127.0.0.1"
        ldpd_options="   -A 127.0.0.1"
        nhrpd_options="  -A 127.0.0.1"
        eigrpd_options=" -A 127.0.0.1"
        babeld_options=" -A 127.0.0.1"
        sharpd_options=" -A 127.0.0.1"
        pbrd_options="   -A 127.0.0.1"
        staticd_options="-A 127.0.0.1"
        bfdd_options="   -A 127.0.0.1"
        fabricd_options="-A 127.0.0.1"
        vrrpd_options="  -A 127.0.0.1"
        pathd_options="  -A 127.0.0.1"
        frr_profile="datacenter"
        MAX_FDS=1024
      vtysh.conf: |
        service integrated-vtysh-config
      frr.conf: |
        log syslog informational
        !
        debug bgp neighbor-events
        !
        ip nht resolve-via-default
        !
        router-id {{ $rs.ipAddress }}
        !
        {{- range $netID, $netInterface := $rs.networking.interfaces }}
        {{- if $netInterface.routing }}
        !
        interface eth{{ $netID }}
          {{- with $ospf := $netInterface.routing.ospf }}
          {{- if $ospf.enabled }}
          ip ospf area {{ $ospf.area }}
          ip ospf network {{ default "broadcast" $ospf.type }}
          
          {{- with $ospf.priority }}
          ip ospf priority {{ . }}
          {{- end }}

          {{- with $ospf.hello }}
          ip ospf hello-interval {{ . }}
          {{- end }}

          {{- with $ospf.dead }}
          ip ospf dead-interval {{ . }}
          {{- end }}

          {{- if $ospf.passive }}
          ip ospf passive
          {{- end }}
          {{- end }}
          {{- end }}
        exit
        {{- end }}
        {{- end }}
        !
        {{- if and $rs.ospf $rs.ospf.enabled }}
        router ospf
          {{- with $rs.ospf.autocost.refBandwidth }}
          auto-cost reference-bandwidth {{ . }}
          {{- end }}
        exit
        !
        {{- end }}
        router bgp {{ $rs.bgp.asn }}
          no bgp ebgp-requires-policy
          bgp cluster-id {{ default $rs.ipAddress $rs.bgp.clusterId }}
          bgp disable-ebgp-connected-route-check
          bgp bestpath peer-type multipath-relax
          bgp graceful-restart stalepath-time 300
          {{- range $peerGroupIndex, $peerGroup := $rs.bgp.peerGroups }}
          neighbor {{ $peerGroup.name }} peer-group
          {{- with $peerGroup.ebgpmultihop }}
          neighbor {{ $peerGroup.name }} ebgp-multihop {{ . }}
          {{- end }}
          neighbor {{ $peerGroup.name }} remote-as {{ $peerGroup.asn }}
          {{- end }}

          {{- range $peerIndex, $peer := $rs.bgp.peers }}
          {{- with $peer.remoteASN }}
          neighbor {{ $peer.address }} remote-as {{ . }}
          {{- end }}

          {{- with $peer.ebgpmultihop }}
          neighbor {{ $peer.address }} ebgp-multihop {{ . }}
          {{- end }}

          {{- with $peer.peerGroup }}
          neighbor {{ $peer.address }} peer-group {{ . }}
          {{- end }}

          {{- end }}
          !
          {{- range $afiIndex, $afi := $rs.bgp.afi }}
          {{- range $safiIndex, $safi := $afi }}
          address-family {{ $afiIndex }} {{ $safiIndex }}
            {{- range $safiKeyIndex, $safiKey := $safi }}
            {{- range $safiSubKeyIndex, $safiSubKey := $safiKey }}
            
            {{- if kindIs "map" $safiSubKey }}
            {{ $safiKeyIndex }} {{ $safiSubKey.name }} {{ $safiSubKey.action }} 
            {{- else }}
            {{ $safiKeyIndex }} {{ if eq $safiSubKeyIndex "base" }}{{ $safiSubKey }}{{ else }}{{ $safiSubKeyIndex }} {{ $safiSubKey }}{{ end }}

            {{- end }}
            {{- end }}
            {{- end }}
          exit-address-family
          !
          {{- end }}
          {{- end }}
        exit
        !
        end
{{- end }}

persistence:
  {{- range $name, $rs := .Values.routeservers }}
  {{ $name }}-config:
    enabled: true

    type: configMap

    name: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}-{{ $name }}-config'

    defaultMode: 0755

    advancedMounts:
      {{ $name }}-routeserver: # the controller with the "main" identifier
        frr: # the container with the "main" identifier
          - path: /etc/frr/frr.conf
            readOnly: true
            subPath: frr.conf

          - path: /etc/frr/vtysh.conf
            readonly: true
            subPath: vtysh.conf

          - path: /etc/frr/daemons
            readOnly: true
            subPath: daemons
  {{- end }}


{{- end -}}
{{- $_ := mergeOverwrite .Values (include "app-template.hardcodedValues" . | fromYaml) -}}

{{- $testingGlob := . -}}
{{- range $name, $rs := .Values.routeservers }}
{{- if and $rs.networking $rs.networking.egressGW $rs.networking.egressGW.enabled }}
{{- $controllerName := printf "%s-routeserver" $name }}
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" $ }}-{{ $name }}-ext-traffic
    
spec:
  # Specify which pods should be subject to the current policy.
  # Multiple pod selectors can be specified.
  selectors:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: {{ $controllerName }}
          {{- include "bjw-s.common.lib.metadata.selectorLabels" $ | nindent 10 }}

  # Specify which destination CIDR(s) this policy applies to.
  # Multiple CIDRs can be specified.
  destinationCIDRs:
    - '0.0.0.0/0'

  # Configure the gateway node.
  egressGateway:
    # Specify which node should act as gateway for this policy.
    nodeSelector:
      matchLabels:
        kubernetes.io/os: linux

    # Specify the IP address used to SNAT traffic matched by the policy.
    # It must exist as an IP associated with a network interface on the instance.
    egressIP: 10.1.1.179
---
{{- end }}
{{- if and $rs.networking $rs.networking.interfaces }}
{{- range $netID, $netInterface := $rs.networking.interfaces -}}
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" $ }}-{{ $netID }}


  {{- if eq $netInterface.type "sriov" }}
  annotations:
    k8s.v1.cni.cncf.io/resourceName: {{ $netInterface.sriov.device }}
  {{- end }}
spec:
  config: |
    {
      "cniVersion": "1.0.0",
      "name": "vlan{{ $netInterface.sriov.vlan }}",
      "type": "{{ $netInterface.type }}",
      {{- if eq $netInterface.type "sriov" }}
      "spoofchk": "off",
      {{- end }}
      {{- with $netInterface.mtu }}
      "mtu": {{ . }},
      {{- end }}
      "vlan": {{ $netInterface.sriov.vlan }},
      {{- if $netInterface.ipam }}
      "ipam": {
        "type": "static",
        {{- if $netInterface.ipam.routes }}
        "routes": {{ toJson $netInterface.ipam.routes }},
        {{- end }}
        "addresses": [
          {
            "address": "{{ $netInterface.ipam.address }}"
          }
        ]
      }
      {{- end }}
    }
---
{{- end }}
{{- end }}
{{- end }}
---


{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}

---
