apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi

  namespace: cdi
spec:
  config:
    featureGates:
      - HonorWaitForFirstConsumer
    podResourceRequirements:
      requests:
        cpu: '100m'
        memory: '60M'
      limits:
        cpu: '4'
        memory: '600M'
  imagePullPolicy: IfNotPresent
  
  infra:
    nodeSelector:
      kubernetes.io/os: linux
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
  
  workload:
    nodeSelector:
      kubernetes.io/os: linux
