{{- range .Values.backupTargets }}
{{- if not .local }}
apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: '{{ .name }}'
  namespace: longhorn-system
spec:
  backupTargetURL: 's3://{{ .bucket }}@{{ .s3Region }}/'
  credentialSecret: 'longhorn-backup-{{ .targetCluster }}-credentials'
  pollInterval: '5m0s'
---
{{- end }}
{{- end }}
