allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-storage
parameters:
  dataEngine: v1
  datalocality: strict-local
  diskSelector: ssd
  fsType: xfs
  numberOfReplicas: '1'
  stalereplicatimeout: '30'
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
