apiVersion: v1
kind: ConfigMap
metadata:
  name: aaa-authentik-environment
data:
  CLUSTER_NAME: '{{ .Values.cluster.name }}'
  DATACENTER: '{{ .Values.datacenter }}'
  REGION: '{{ .Values.region }}'
  DOMAIN_NAME: '{{ .Values.domainName }}'
