hub: false

env: prod

cluster:
  name: k8s
  domain: cluster.local

# Public DNS suffix used for externally routed service hostnames.
domain: resolvemy.host

gateway:
  name: main-gw
  namespace: core-prod
  sectionName: https-myloginspace

datacenter: dc1

region: yxl

authentik:
  autoconfigure: true

  route:
    enabled: true

tenant:
  name: core

oidc:
  enabled: true

  indexKey: argocd-dev

  scopes:
    - openid
    - profile
    - email

  groups:
    - Server Admins
    - Developers

  authentik:
    urlBase: https://idp.mylogin.space

goldilocks:
  # Use the upstream defaults except for installing the bundled VPA dependency.
  vpa:
    enabled: true

descheduler:
  kind: Deployment

  resources:
    requests:
      cpu: 32m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi

  # deschedulerPolicy contains the policies the descheduler will execute.
  deschedulerPolicy:
    # nodeSelector: "key1=value1,key2=value2"
    # maxNoOfPodsToEvictPerNode: 10
    # maxNoOfPodsToEvictPerNamespace: 10
    # metricsProviders:
    # - source: KubernetesMetrics
    # tracing:
    #   collectorEndpoint: otel-collector.observability.svc.cluster.local:4317
    #   transportCert: ""
    #   serviceName: ""
    #   serviceNamespace: ""
    #   sampleRate: 1.0
    #   fallbackToNoOpProviderOnError: true
    profiles:
      - name: default
        pluginConfig:
          - name: DefaultEvictor
            args:
              podProtections:
                defaultDisabled:
                - "PodsWithLocalStorage"
                extraEnabled:
                - "PodsWithPVC"
          - name: RemoveDuplicates
          - name: RemovePodsHavingTooManyRestarts
            args:
              podRestartThreshold: 100
              includingInitContainers: true
          - name: RemovePodsViolatingNodeAffinity
            args:
              nodeAffinityType:
              - requiredDuringSchedulingIgnoredDuringExecution
          - name: RemovePodsViolatingNodeTaints
          - name: RemovePodsViolatingInterPodAntiAffinity
          - name: RemovePodsViolatingTopologySpreadConstraint
          - name: LowNodeUtilization
            args:
              thresholds:
                cpu: 30
                memory: 20
                pods: 20
              targetThresholds:
                cpu: 65
                memory: 75
                pods: 70
        plugins:
          balance:
            enabled:
              - RemoveDuplicates
              - RemovePodsViolatingTopologySpreadConstraint
              - LowNodeUtilization
          deschedule:
            enabled:
              - RemovePodsHavingTooManyRestarts
              - RemovePodsViolatingNodeTaints
              - RemovePodsViolatingNodeAffinity
              - RemovePodsViolatingInterPodAntiAffinity

  priorityClassName: system-cluster-critical
