---
hub: true

librespeed:
  enabled: false

iperf3:
  enabled: false

domain: speed.mylogin.space

# persistence:
#   config:
#     enabled: true
#     mountPath: /etc/pdns/pdns.conf
#     subPath: pnds.conf
#     type: custom
#     volumeSpec:
#       configMap:
#         name: 'ns-core-config'

#     advancedMounts:
#       main: # the controller with the "main" identifier
#         main: # the container with the "main" identifier
#           - path: /etc/pdns/pdns.conf
#             readOnly: true
#             subPath: pdns.conf


#   configs:
#     enabled: true
#     mountPath: /etc/pdns/conf.d
#     type: custom
#     volumeSpec:
#       secret:
#         secretName: 'ns-core-secrets'

#         items:
#           - key: web.conf
#             path: web.conf

#     advancedMounts:
#       main: # the controller with the "main" identifier
#         main: # the container with the "main" identifier
#           - path: /etc/pdns/conf.d/web.conf
#             subPath: web.conf


# configMaps:
#   config:
#     # -- Enables or disables the configMap
#     enabled: true
#     # -- Labels to add to the configMap
#     labels: {}
#     # -- Annotations to add to the configMap
#     annotations: {}
#     # -- configMap data content. Helm template enabled.
#     data:
#       pdns.conf: |
