apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
      "resourceList": [
        {
          "resourceName": "intel_i350_vfio",
          "selectors": {
            "vendors": ["8086"],
            "devices": ["1520"],
            "drivers": ["vfio-pci"],
            "pfNames": ["eno2"]
          }
        },
        {
          "resourceName": "mlx4_cx3_netdevice",
          "resourcePrefix": "mellanox.com",
          "deviceType": "netDevice",
          "selectors": [
            {
              "vendors": ["15b3"],
              "devices": ["1004"],
              "drivers": ["mlx4_core"],
              "pfNames": ["enp4s0d1#0-3"],
              "linkTypes": ["ether"]
            }
          ]
        }
      ]
    }