apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cdn-{{ required "cdn.name is required" .Values.cdn.name }}

  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  secretStoreRef:
    kind: {{ required "cdn.externalSecret.secretStoreRef.kind is required" .Values.cdn.externalSecret.secretStoreRef.kind | quote }}
    name: {{ required "cdn.externalSecret.secretStoreRef.name is required" .Values.cdn.externalSecret.secretStoreRef.name | quote }}

  target:
    name: cdn-{{ .Values.cdn.name }}

  data:
    - secretKey: AccessKey
      remoteRef:
        key: {{ required "cdn.externalSecret.accessKey.key is required" .Values.cdn.externalSecret.accessKey.key | quote }}
        property: {{ required "cdn.externalSecret.accessKey.property is required" .Values.cdn.externalSecret.accessKey.property | quote }}

    - secretKey: SecretKey
      remoteRef:
        key: {{ required "cdn.externalSecret.secretKey.key is required" .Values.cdn.externalSecret.secretKey.key | quote }}
        property: {{ required "cdn.externalSecret.secretKey.property is required" .Values.cdn.externalSecret.secretKey.property | quote }}
