tenant:
  name: example-tenant

pubgateway:
  name: main-gw
  namespace: core-prod
  sectionName: mylogin-https

authentik:
  autoconfigure: true

  application:
    displayName: 'Radarr'
    externalHost: 'https://movies.mylogin.space'
    group: 'Media'

  accessGroups:
    - 'Media Consumers'

  route:
    enabled: true

    backend:
      name: 'aaa-myloginspace-proxy'
      namespace: 'core-prod'
      port: 80

radarr:
  enabled: true

  image: linuxserver/radarr

  tag: latest

  volumes:
    config:
      enabled: true

      size: 2G

    downloads:
      enabled: true

      external: true

    media:
      enabled: true

      external: true
