apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-backplane-network-dns
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - merge:
        mergeKeys:
          - name
        generators:
          - list:
              elements:
                - name: core-home1-talos-prod
                  values:
                    dnsdistEnabled: true
                    nameserver:
                      domain: 'ns2.resolvemy.host'
                      dnsTarget: <path:CORE0_SITE1/data/Network/Public/YVR#PublicHostname>
                      loadBalancerClass: 'kube-vip.io/kube-vip-class'
                      ipv4: '10.0.0.40'
                      serviceGroup: ''
                      serviceType: 'LoadBalancer'
                - name: core-dc1-talos-prod
                  values:
                    dnsdistEnabled: true
                    nameserver:
                      domain: 'ns4.resolvemy.host'
                      dnsTarget: ''
                      ipv4: '66.165.222.105'
                      serviceGroup: 'anycast'
                      serviceType: 'LoadBalancer'
          - clusters:
              selector:
                matchLabels:
                  mylogin.space/tenant: 'core.mylogin.space'
                  resolvemy.host/computetype: 'baremetal'
                  resolvemy.host/nodetype: 'infra'
              values:
                clusterName: '{{ .name }}'
                environment: '{{ index .metadata.labels "resolvemy.host/env" }}'
                clusterDomain: '{{ index .metadata.labels "cluster.kubernetes.io/domain" }}'
                datacenter: '{{ index .metadata.labels "resolvemy.host/dc" }}'
                region: '{{ index .metadata.labels "topology.kubernetes.io/region" }}'
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{ .values.clusterName }}-network-dns-{{ .values.environment }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
    spec:
      project: core
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
      source:
        repoURL: https://github.com/K-FOSS/CoRE-Backplane.git
        path: Network/DNS
        targetRevision: HEAD
        plugin:
          name: argocd-lovely-plugin
          env:
            - name: LOVELY_HELM_MERGE
              value: |-
                cluster:
                  name: '{{ .values.clusterName }}'
                  domain: '{{ .values.clusterDomain }}'
                  kubernetesDomain: '{{ .values.clusterDomain }}'
                  environment: '{{ .values.environment }}'
                  datacenter: '{{ .values.datacenter }}'
                  region: '{{ .values.region }}'
                dnsdist:
                  enabled: {{ .values.dnsdistEnabled }}
                  authoritative:
                    zones:
                      - 'resolvemy.host.'
                      - 'syncmy.date.'
                      - 'mylogin.social.'
                      - '222.165.66.in-addr.arpa.'
                  k8gb:
                    healthCheckName: 'gslb.mylogin.space'
                    zones:
                      - 'gslb.mylogin.space'
                  service:
                    type: '{{ .values.nameserver.serviceType }}'
                    loadBalancerClass: '{{ .values.nameserver.loadBalancerClass }}'
                    annotations:
                      external-dns.kubernetes.io/hostname: '{{ .values.nameserver.domain }}'
                      external-dns.alpha.kubernetes.io/hostname: '{{ .values.nameserver.domain }}'
                      {{ if .values.nameserver.dnsTarget }}
                      external-dns.kubernetes.io/target: '{{ .values.nameserver.dnsTarget }}'
                      external-dns.alpha.kubernetes.io/target: '{{ .values.nameserver.dnsTarget }}'
                      {{ end }}
                      {{ if eq .values.nameserver.loadBalancerClass "kube-vip.io/kube-vip-class" }}
                      kube-vip.io/loadbalancerIPs: '{{ .values.nameserver.ipv4 }}'
                      {{ end }}
                      {{ if eq .values.region "yxl" }}
                      purelb.io/addresses: '{{ .values.nameserver.ipv4 }}'
                      purelb.io/allow-local: 'true'
                      purelb.io/service-group: '{{ .values.nameserver.serviceGroup }}'
                      {{ end }}
      destination:
        server: '{{ .server }}'
        namespace: k8gb
