apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-backplane-network-global
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - merge:
        mergeKeys:
          - name
        generators:
          - list:
              elements:
                - name: core-home1-talos-prod
                  values:
                    clusterGeoTag: 'home1'
                    extGslbClustersGeoTags: 'dc1'
                    dnsdistExternalAddress: '10.0.0.40'
                    externalNameserver: 'ns2.resolvemy.host'
                    hostmasterEmail: 'augy@mail.mylogin.space'
                - name: core-dc1-talos-prod
                  values:
                    clusterGeoTag: 'dc1'
                    extGslbClustersGeoTags: 'home1'
                    dnsdistExternalAddress: '66.165.222.105'
                    externalNameserver: 'ns4.resolvemy.host'
                    hostmasterEmail: 'augy@mail.mylogin.space'
          - clusters:
              selector:
                matchLabels:
                  mylogin.space/tenant: 'core.mylogin.space'
                  resolvemy.host/computetype: 'baremetal'
                  resolvemy.host/nodetype: 'infra'
              values:
                clusterName: '{{ .name }}'
                environment: '{{ index .metadata.labels "resolvemy.host/env" }}'
                clusterDomain: '{{ index .metadata.labels "cluster.kubernetes.io/domain" }}'
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{ .values.clusterName }}-network-global-{{ .values.environment }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
    spec:
      project: core
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
      source:
        repoURL: https://slop.writemy.codes/CoRE/CoRE-Backplane.git
        path: Network/Global
        targetRevision: HEAD
        plugin:
          name: argocd-lovely-plugin
          env:
            - name: LOVELY_HELM_MERGE
              value: |-
                k8gb:
                  k8gb:
                    clusterGeoTag: '{{ .values.clusterGeoTag }}'
                    extGslbClustersGeoTags: '{{ .values.extGslbClustersGeoTags }}'
                    clusterExposedIPs:
                      - '{{ .values.dnsdistExternalAddress }}'
                    dnsZones:
                      - parentZone: 'mylogin.space'
                        loadBalancedZone: 'gslb.mylogin.space'
                        dnsZoneNegTTL: 30
            - name: LOVELY_KUSTOMIZE_MERGE
              value: |-
                patches:
                  - target:
                      version: 'v1'
                      kind: ConfigMap
                      name: '{{ .values.clusterName }}-network-global-{{ .values.environment }}-coredns'
                      namespace: 'k8gb'
                    patch: |-
                      - op: 'replace'
                        path: '/data/Corefile'
                        value: |
                          .:5353 {
                            health
                            reload 30s 15s
                            ready
                          }
                          (k8gbplugins) {
                              errors
                              health
                              reload 30s 15s
                              ready
                              prometheus 0.0.0.0:9153
                              forward . /etc/resolv.conf
                              template IN NS gslb.mylogin.space {
                                  match ^gslb[.]mylogin[.]space[.]$
                                  answer "gslb.mylogin.space. 30 IN NS {{ .values.externalNameserver }}."
                                  fallthrough
                              }
                              template IN SOA gslb.mylogin.space {
                                  match ^gslb[.]mylogin[.]space[.]$
                                  answer "gslb.mylogin.space. 30 IN SOA {{ .values.externalNameserver }}. {{ .values.hostmasterEmail | replace "@" "." }}. 1 7200 1800 86400 30"
                                  fallthrough
                              }
                              k8s_crd {
                                  filter k8gb.io/dnstype=local
                                  negttl 30
                                  loadbalance weight
                              }
                          }
                          import ../dynamic/*.conf
      destination:
        server: '{{ .server }}'
        namespace: k8gb
