apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 'core-backplane-network-insight'
  namespace: 'argocd'
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'

  generators:
    - merge:
        mergeKeys:
          - 'name'
        generators:
          - list:
              elements:
                - name: 'core-dc1-talos-prod'
                  values:
                    opennms:
                      enabled: false
                    minion:
                      enabled: true
                      nodeSelector: {}
                      image:
                        repository: 'docker.io/opennms/minion'
                        tag: '35.0.0'
                        digest: 'sha256:3456699d74e2a0b67bfe3049e560eba7d21de4180726a8c16294f3416178462e'
                        pullPolicy: 'IfNotPresent'
                      id: 'core-dc1-talos-prod-minion'
                      location: 'core-dc1-talos-prod'
                      coreUrl: ''
                      kafka:
                        bootstrapServers: 'kafka.core-home1-talos-prod.home1.yvr.mylogin.space:9094'
                - name: 'core-home1-talos-prod'
                  values:
                    opennms:
                      enabled: true
                    minion:
                      enabled: true
                      nodeSelector:
                        core.resolvemy.host/x86-64-v3: 'true'
                      image:
                        repository: 'docker.io/opennms/minion'
                        tag: '36.0.3'
                        digest: 'sha256:6652c8d52a7ad8d2f89cfb7a39ba3205d6f340b5fd9bcac444553d7b8c106457'
                        pullPolicy: 'IfNotPresent'
                      id: 'core-home1-talos-prod-minion'
                      location: 'core-home1-talos-prod'
                      coreUrl: ''
                      kafka:
                        bootstrapServers: 'kafka.core-home1-talos-prod.home1.yvr.mylogin.space:9094'
          - clusters:
              selector:
                matchLabels:
                  mylogin.space/tenant: 'core.mylogin.space'
                  resolvemy.host/computetype: 'baremetal'
                  resolvemy.host/nodetype: 'infra'
              values:
                clusterName: '{{ .name }}'
                environment: '{{ index .metadata.labels "resolvemy.host/env" }}'
                clusterDomain: '{{ index .metadata.labels "cluster.kubernetes.io/domain" }}'
                tenant: '{{ index .metadata.labels "mylogin.space/tenant" }}'
                region: '{{ index .metadata.labels "topology.kubernetes.io/region" }}'
                zone: '{{ index .metadata.labels "topology.kubernetes.io/zone" }}'
                datacenter: '{{ index .metadata.labels "resolvemy.host/dc" }}'

  syncPolicy:
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: '{{ .values.clusterName }}-network-insight-{{ .values.environment }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '.'
      labels:
        resolvemy.host/env: '{{ .values.environment }}'

    spec:
      project: 'core'
      syncPolicy:
        syncOptions:
          - 'CreateNamespace=true'
          - 'ServerSideApply=true'

      source:
        path: 'Network/Insight'
        repoURL: 'https://github.com/K-FOSS/CoRE-Backplane.git'
        targetRevision: 'HEAD'
        plugin:
          name: 'argocd-lovely-plugin'
          env:
            - name: 'LOVELY_HELM_MERGE'
              value: |-
                env: '{{ .values.environment }}'

                datacenter: '{{ .values.datacenter }}'

                region: '{{ .values.region }}'

                cluster:
                  name: '{{ .values.clusterName }}'
                  domain: '{{ .values.clusterDomain }}'

                postgresql:
                  host: 'psql-local.{{ .values.clusterName }}.{{ .values.datacenter }}.{{ .values.region }}.mylogin.space'
                  adminSecretName: 'opsadmin.psql-{{ .values.datacenter }}-{{ .values.region }}.credentials.postgresql.acid.zalan.do'
                  adminSecretSourceNamespace: 'core-{{ .values.environment }}'
                  secretSync:
                    remoteKeyPrefix: 'Network/Insight/{{ .values.clusterName }}'
                  providers:
                    crossplane: 'psql-{{ .values.datacenter }}-{{ .values.region }}'
                    terraform: 'psql-{{ .values.datacenter }}-{{ .values.region }}'

                timeseries:
                  enabled: true
                  writeUrl: 'http://{{ .values.clusterName }}-collectors-alloy.core-{{ .values.environment }}.svc.{{ .values.clusterDomain }}:9090/api/v1/metrics/write'
                  readUrl: 'http://core-mimir.core-{{ .values.environment }}.svc.{{ .values.clusterDomain }}:8080/prometheus/api/v1'

                kafka:
                  instanceId: 'OpenNMS'
                  enabled: true
                  bootstrapServers: 'kafka.{{ .values.clusterName }}.{{ .values.datacenter }}.{{ .values.region }}.mylogin.space:9094'

                serviceGlobal:
                  global:
                    enabled: {{ .values.opennms.enabled }}

                opennms:
                  enabled: {{ .values.opennms.enabled }}

                minion:
                  enabled: {{ .values.minion.enabled }}
                  id: '{{ .values.minion.id }}'
                  location: '{{ .values.minion.location }}'
                  coreUrl: '{{ if .values.minion.coreUrl }}{{ .values.minion.coreUrl }}{{ else }}http://core-home1-talos-prod-network-insight-prod.core-net-{{ .values.environment }}.svc.{{ .values.clusterDomain }}/opennms{{ end }}'
                  nodeSelector: {{ .values.minion.nodeSelector | toJson }}
                  image:
                    repository: '{{ .values.minion.image.repository }}'
                    tag: '{{ .values.minion.image.tag }}'
                    digest: '{{ .values.minion.image.digest }}'
                    pullPolicy: '{{ .values.minion.image.pullPolicy }}'
                  kafka:
                    bootstrapServers: '{{ .values.minion.kafka.bootstrapServers }}'

      destination:
        server: '{{ .server }}'
        namespace: 'core-net-{{ .values.environment }}'
