
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-backplane-net-natpuncher
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  goTemplate: true
  # goTemplateOptions:
  #   - 'missingkey=error'
  generators:
    - merge:
        mergeKeys:
          - name

        generators:
          - list:
              elements:
                - name: core-dc1-talos-prod
                  values:
                    hub: false
                    UPNP:
                      enabled: false
                    CoTurn:
                      hub: false
                    Tunneler:
                      hub: true

                - name: core-home1-talos-prod
                  values:
                    hub: false
                    UPNP:
                      enabled: true

                      network:
                        interfaces:
                          - type: sriov
                            mtu: 1500
                            ipam:
                              address: 10.0.0.10
                              routes:
                                - dst: 0.0.0.0/0
                                  gw: 10.0.0.1
                            sriov:
                              vlan: 150
                              device: mellanox.com/mlx4_cx3_netdevice

                      ports:
                        - target: 10.0.0.19
                          internalPort: 53
                          externalPort: 53
                          protocol: TCP
                          duration: 8600

                        - target: 10.0.0.19
                          internalPort: 53
                          externalPort: 53
                          protocol: UDP
                          duration: 8600

                        - target: 10.0.0.19
                          internalPort: 80
                          externalPort: 80
                          protocol: TCP
                          duration: 8600

                        - target: 10.0.0.19
                          internalPort: 443
                          externalPort: 443
                          protocol: TCP
                          duration: 8600

                        - target: 10.0.0.19
                          internalPort: 443
                          externalPort: 443
                          protocol: UDP
                          duration: 8600

                        - target: 10.0.0.19
                          internalPort: 8443
                          externalPort: 8443
                          protocol: TCP
                          duration: 8600

                        - target: 10.0.0.19
                          internalPort: 8080
                          externalPort: 8080
                          protocol: TCP
                          duration: 8600

                        - target: 10.0.0.11
                          internalPort: 4763
                          externalPort: 4763
                          protocol: UDP
                          duration: 8600

                        - target: 10.0.0.12
                          internalPort: 4764
                          externalPort: 4764
                          protocol: UDP
                          duration: 8600

                        - target: 10.0.0.11
                          internalPort: 2010
                          externalPort: 2010
                          protocol: UDP
                          duration: 8600

                        - target: 10.0.0.12
                          internalPort: 2012
                          externalPort: 2012
                          protocol: UDP
                          duration: 8600

                        - target: 10.0.0.11
                          internalPort: 1010
                          externalPort: 1010
                          protocol: UDP
                          duration: 8600

                        - target: 10.0.0.11
                          internalPort: 1011
                          externalPort: 1011
                          protocol: UDP
                          duration: 8600

                        - target: 10.0.0.12
                          internalPort: 1112
                          externalPort: 1112
                          protocol: UDP
                          duration: 8600

                        - target: 10.0.0.11
                          internalPort: 50101
                          externalPort: 50101
                          protocol: UDP
                          duration: 8600

                        - target: 10.0.0.12
                          internalPort: 51010
                          externalPort: 51010
                          protocol: UDP
                          duration: 8600

                        - target: 10.0.0.12
                          internalPort: 51011
                          externalPort: 51011
                          protocol: UDP
                          duration: 8600
                    CoTurn:
                      hub: false
                    Tunneler:
                      hub: true
          - clusters:
              selector:
                matchLabels:
                  mylogin.space/tenant: 'core.mylogin.space'
                  resolvemy.host/computetype: 'baremetal'
                  resolvemy.host/nodetype: 'infra'
              values:
                clusterName: '{{ .name }}'
                environment: 'prod'
                clusterDomain: '{{ index .metadata.labels "cluster.kubernetes.io/domain" }}'
                tenant: '{{ index .metadata.labels "mylogin.space/tenant" }}'
                region: '{{ index .metadata.labels "topology.kubernetes.io/region" }}'
                zone: '{{ index .metadata.labels "topology.kubernetes.io/zone" }}'
                datacenter: '{{ index .metadata.labels "resolvemy.host/dc" }}'

  syncPolicy:
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: '{{ .values.clusterName }}-natpuncher-{{ .values.environment }}'

      annotations:
        argocd.argoproj.io/manifest-generate-paths: .

    spec:
      project: core
      syncPolicy:
        syncOptions:
          - ServerSideApply=true

      source:
        path: Network/NATPuncher
        repoURL: https://github.com/K-FOSS/CoRE-Backplane.git
        targetRevision: HEAD
        plugin:
          name: argocd-lovely-plugin
          env:
            - name: LOVELY_HELM_MERGE
              value: |-
                env: {{ .values.environment }}

                hub: {{ .values.hub }}

                cluster:
                  name: {{ .values.clusterName }}
                  domain: {{ .values.clusterDomain }}

                UPNP:
                  {{ nindent 2 (toYaml .values.UPNP) }}

                datacenter: {{ .values.datacenter }}

                region: {{ .values.region }}

      destination:
        server: '{{ .server }}'
        namespace: core-{{ .values.environment }}
