apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-backplane-network-ns
  namespace: argocd
spec:
  goTemplate: true
  # goTemplateOptions:
  #   - 'missingkey=error'
  generators:
    - merge:
        mergeKeys:
          - name

        generators:
          - list:
              elements:
                - name: core-dc1-talos-prod
                  values:
                    hub: false
                    powerdnsAdmin:
                      hostname: 'nsadmin.core-dc1-talos-prod.dc1.yxl.resolvemy.host'
                    nameserver:
                      domain: 'ns4.resolvemy.host'
                      serviceType: 'LoadBalancer'
                      address:
                        ipv4: 66.165.222.100
                        serviceGroup: anycast

                - name: core-home1-talos-prod
                  values:
                    hub: false
                    powerdnsAdmin:
                      hostname: 'nsadmin.core-home1-talos-prod.home1.yvr.resolvemy.host'
                    nameserver:
                      domain: 'ns2.resolvemy.host'
                      serviceType: 'ClusterIP'
                      dns:
                        target: <path:CORE0_SITE1/data/Network/Public/YVR#PublicHostname>
          - clusters:
              selector:
                matchLabels:
                  mylogin.space/tenant: 'core.mylogin.space'
                  resolvemy.host/computetype: 'baremetal'
                  resolvemy.host/nodetype: 'infra'
              values:
                clusterName: '{{ .name }}'
                environment: 'prod'
                clusterDomain: '{{ index .metadata.labels "cluster.kubernetes.io/domain" }}'
                tenant: '{{ index .metadata.labels "mylogin.space/tenant" }}'
                region: '{{ index .metadata.labels "topology.kubernetes.io/region" }}'
                zone: '{{ index .metadata.labels "topology.kubernetes.io/zone" }}'
                datacenter: '{{ index .metadata.labels "resolvemy.host/dc" }}'

  template:
    metadata:
      name: '{{ .values.clusterName }}-network-ns-{{ .values.environment }}'

      annotations:
        argocd.argoproj.io/manifest-generate-paths: .

    spec:
      project: core

      source:
        repoURL: https://github.com/K-FOSS/CoRE-Backplane.git
        path: Network/NS
        targetRevision: main
        plugin:
          name: argocd-lovely-plugin
          env:
            - name: LOVELY_HELM_MERGE
              value: |-
                env: {{ .values.environment }}

                hub: {{ .values.hub }}

                cluster:
                  name: {{ .values.clusterName }}
                  domain: {{ .values.clusterDomain }}


                datacenter: {{ .values.datacenter }}

                region: {{ .values.region }}

                powerdns:
                  database:
                    host: psql.core-{{ .values.environment }}.svc.{{ .values.clusterDomain }}

                psql:
                  hostname: 'psql-local.{{ .values.clusterName }}.{{ .values.datacenter }}.{{ .values.region }}.mylogin.space'
                  crossplaneProvider: 'psql-{{ .values.datacenter }}-{{ .values.region }}'
                  terraformProvider: 'psql-{{ .values.datacenter }}-{{ .values.region }}'

                service:
                  main:
                    type: '{{ .values.nameserver.serviceType }}'
                    {{ if and (eq .values.nameserver.serviceType "LoadBalancer") .values.nameserver.address.loadBalancerClass }}
                    loadBalancerClass: '{{ .values.nameserver.address.loadBalancerClass }}'
                    {{ end }}
                    annotations:
                      consul.hashicorp.com/service-name: ns-core
                      {{ if .values.nameserver.dns.target }}
                      external-dns.kubernetes.io/target: '{{ .values.nameserver.dns.target }}'
                      # TODO(external-dns-016): Remove the legacy annotation after upgrading ExternalDNS.
                      external-dns.alpha.kubernetes.io/target: '{{ .values.nameserver.dns.target }}'
                      {{ end }}
                      external-dns.kubernetes.io/hostname: '{{ .values.nameserver.domain }}'
                      # TODO(external-dns-017): Remove the legacy annotation after upgrading ExternalDNS.
                      external-dns.alpha.kubernetes.io/hostname: '{{ .values.nameserver.domain }}'
                      {{ if and (eq .values.nameserver.serviceType "LoadBalancer") (eq .values.nameserver.address.loadBalancerClass "kube-vip.io/kube-vip-class") }}
                      kube-vip.io/forwardUPNP: 'true'
                      {{ end }}
                      {{ if and (eq .values.nameserver.serviceType "LoadBalancer") (not .values.nameserver.address.loadBalancerClass) }}
                      purelb.io/addresses: '{{ .values.nameserver.address.ipv4 }}'
                      purelb.io/allow-local: 'true'
                      {{ if .values.nameserver.address.sharedIP.enabled }}
                      purelb.io/allow-shared-ip: '{{ .values.nameserver.address.sharedIP.key }}'
                      {{ end }}
                      purelb.io/service-group: '{{ .values.nameserver.address.serviceGroup }}'
                      {{ end }}

                powerdnsAdmin:
                  route:
                    hostnames:
                      - '{{ .values.powerdnsAdmin.hostname }}'

      destination:
        server: '{{ .server }}'
        namespace: core-{{ .values.environment }}
