apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgpool-config

spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

  target:
    name: pgpool-config
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          configMap:
            name: pgpool-config
            items:
              - key: readiness.sh
              - key: pgpool.conf
              - key: pool_hba.conf
              - key: pool_passwd
  data:
    - secretKey: Username
      remoteRef:
        key: PSQL/Operator
        property: username

    - secretKey: Password
      remoteRef:
        key: PSQL/Operator
        property: password

    # Authentik database credentials.
    - secretKey: AAAUsername
      remoteRef:
        key: AAA/Authentik/Database
        property: Username
    - secretKey: AAAPassword
      remoteRef:
        key: AAA/Authentik/Database
        property: Password

    # PostgreSQL operator administration credentials.
    - secretKey: OPSUsername
      remoteRef:
        key: PSQL/Operator
        property: username
    - secretKey: OPSPassword
      remoteRef:
        key: PSQL/Operator
        property: password
