---
{{- include "bjw-s.common.loader.init" . }}

{{- define "db-psql.pgpool.workload" -}}
global:
  nameOverride: pgpool
  fullnameOverride: pgpool

defaultPodOptions:
  labels:
    app.kubernetes.io/name: pgpool
    logs: loki-myloginspace
  securityContext:
    runAsUser: 70
    runAsGroup: 70
    fsGroup: 70
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: pgpool

controllers:
  main:
    type: deployment
    replicas: 3
    revisionHistoryLimit: 3
    strategy: RollingUpdate
    containers:
      main:
        enabled: false
      pgpool:
        image:
          repository: kristianfjones/pgpool
          digest: sha256:b101c0e0a33c4aa8fd9641f4e6a112851735e62bcd494e8c741a31086b7eba6b
          pullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 128m
            memory: 256Mi
          limits:
            cpu: 4019m
            memory: 4G
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        ports:
          - name: psql
            containerPort: 5432
            protocol: TCP
        env:
          PGPOOL_CONF_VOLUME: /config
          PGPOOL_INSTALL_DIR: /opt/pgpool-II
          CHECK_PGCONNECT_TIMEOUT: '2'
          POSTGRES_USERNAME:
            valueFrom:
              secretKeyRef:
                name: opsadmin.psql-main.credentials.postgresql.acid.zalan.do
                key: username
          POSTGRES_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: opsadmin.psql-main.credentials.postgresql.acid.zalan.do
                key: password
          CHECK_USER:
            valueFrom:
              secretKeyRef:
                name: opsadmin.psql-main.credentials.postgresql.acid.zalan.do
                key: username
          CHECK_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: opsadmin.psql-main.credentials.postgresql.acid.zalan.do
                key: password
          PGPOOL_PCP_USER:
            valueFrom:
              secretKeyRef:
                name: opsadmin.psql-main.credentials.postgresql.acid.zalan.do
                key: username
          PGPOOL_PCP_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: opsadmin.psql-main.credentials.postgresql.acid.zalan.do
                key: password
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/sh
                - -ec
                - /opt/pgpool-II/bin/pcp_stop_pgpool -m smart --host localhost --user opsadmin
        probes:
          startup:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: psql
              periodSeconds: 2
              timeoutSeconds: 1
              failureThreshold: 30
          readiness:
            enabled: true
            custom: true
            spec:
              exec:
                command:
                  - /bin/sh
                  - /config/readiness.sh
              periodSeconds: 5
              timeoutSeconds: 3
              failureThreshold: 3
          liveness:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: psql
              periodSeconds: 10
              timeoutSeconds: 2
              failureThreshold: 3

service:
  main:
    enabled: false

persistence:
  pgpool-runtime:
    type: emptyDir
    medium: Memory
    sizeLimit: 128Mi
    advancedMounts:
      main:
        pgpool:
          - path: /tmp/pgpool

  tmp:
    type: emptyDir
    medium: Memory
    sizeLimit: 256Mi
    advancedMounts:
      main:
        pgpool:
          - path: /tmp

  shared-memory:
    type: emptyDir
    medium: Memory
    sizeLimit: 256Mi
    advancedMounts:
      main:
        pgpool:
          - path: /dev/shm

  runtime:
    type: emptyDir
    medium: Memory
    sizeLimit: 16Mi
    advancedMounts:
      main:
        pgpool:
          - path: /var/run/postgresql

  config:
    type: secret
    name: pgpool-config
    defaultMode: 420
    items:
      - key: readiness.sh
        path: readiness.sh
        mode: 420
      - key: pgpool.conf
        path: pgpool.conf
        mode: 420
      - key: pool_hba.conf
        path: pool_hba.conf
        mode: 420
      - key: pool_passwd
        path: pool_passwd
    advancedMounts:
      main:
        pgpool:
          - path: /config
            readOnly: true
          - path: /tmp/pgpool/pool_passwd
            subPath: pool_passwd
            readOnly: true

  tls:
    type: secret
    name: myloginspace-default-certificates
    defaultMode: 416
    advancedMounts:
      main:
        pgpool:
          - path: /config/tls
            readOnly: true
{{- end -}}

{{- $_ := mergeOverwrite .Values (include "db-psql.pgpool.workload" . | fromYaml) -}}
{{ include "bjw-s.common.loader.generate" . }}
