apiVersion: v1
kind: Namespace
metadata:
  name: kepler-operator

  labels:
    kubernetes.io/metadata.name: kepler-operator
    pod-security.kubernetes.io/enforce: privileged

  annotations:
    argocd.argoproj.io/sync-wave: '-1'

spec:
  finalizers:
    - kubernetes