
apiVersion: v2

version: 1.0.0

name: core-backplane-k8s-system

dependencies:
  # Metrics Server
  - name: metrics-server
    version: 3.13.1
    repository: https://kubernetes-sigs.github.io/metrics-server/


