{{- if .Values.jellystat.enabled }}
apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: 'jellystat'
  namespace: '{{ .Release.Namespace }}'
spec:
  name: 'Jellystat'
  username: 'jellystat'
  psql:
    enabled: true
    createUserDatabase: true
    crossplane:
      terraformProvider: 'psql-{{ default "datacenter" .Values.datacenter }}-{{ default "region" .Values.region }}'
      crossplaneProvider: 'psql-{{ default "datacenter" .Values.datacenter }}-{{ default "region" .Values.region }}'
  writeConnectionSecretToRef:
    name: 'jellystat'
{{- end }}
