{{- if and .Values.authentik.ldap.enabled .Values.authentik.ldap.clusterMesh.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: test-ldap-global
    app.kubernetes.io/name: myloginspace-ldap
    lan-mode: 'private'
    wan-mode: 'public'

  annotations:
    {{- with .Values.authentik.ldap.additionalExternalDNSHostname }}
    external-dns.alpha.kubernetes.io/hostname: '{{ . }}'
    {{- end }}
    service.cilium.io/affinity: 'local'
    service.cilium.io/global: 'true'
    service.cilium.io/global-sync-endpoint-slices: 'true'

  name: myloginspace-ldap-global

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: myloginspace-ldap

  ports:
    # Plaintext LDAP
    - name: tcp-ldap
      protocol: TCP
      appProtocol: ldap
      targetPort: 3389
      port: 389

    - name: udp-ldap
      protocol: UDP
      appProtocol: ldap
      targetPort: 3389
      port: 389

    # TLS LDAP
    - name: tcp-ldaps
      protocol: TCP
      appProtocol: ldaps
      targetPort: 6636
      port: 636

    - name: udp-ldaps
      protocol: UDP
      appProtocol: ldaps
      targetPort: 6636
      port: 636

    # Prometheus Metrics
    - name: http-metrics
      protocol: TCP
      appProtocol: ldaps
      targetPort: 9300
      port: 9300

  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
{{- end }}
