env: prod

persistence:
  accessModes:
    - 'ReadWriteMany'
  size: '5Gi'

requestWriter:
  image: 'docker.io/library/busybox@sha256:9db7b59979c38555a39def84a31fb98b5296952f9e3afd4f6f11f05b07adfab0'
  mountPath: '/data'
  port: 8080
  replicas: 1

fileBrowser:
  image: 'docker.io/library/nginx@sha256:a8b39bd9cf0f83869a2162827a0caf6137ddf759d50a171451b335cecc87d236'
  mountPath: '/usr/share/nginx/html'
  port: 8080
  replicas: 1
