env: prod

persistence:
  accessModes:
    - 'ReadWriteMany'
  size: '5Gi'

requestWriter:
  image: 'docker.io/library/busybox@sha256:9db7b59979c38555a39def84a31fb98b5296952f9e3afd4f6f11f05b07adfab0'
  mountPath: '/data'
  port: 8080
  replicas: 1
