tenant:
  name: example-tenant

pubgateway:
  name: main-gw
  namespace: core-prod
  sectionName: mylogin-https

authentik:
  autoconfigure: true

  application:
    displayName: 'MeTube'
    externalHost: 'https://metube.mylogin.space'
    group: 'Media'

  accessGroups:
    - 'Media Consumers'

  route:
    enabled: true

    backend:
      name: 'aaa-myloginspace-proxy'
      namespace: 'core-prod'
      port: 80

whisparr:
  enabled: true

  image: ghcr.io/hotio/whisparr

  tag: v3

  userId: 911
  groupId: 911

  volumes:
    config:
      enabled: true

      size: 5G

    downloads:
      enabled: true

      external: true

    media:
      enabled: true

      external: true

metube:
  enabled: true

  image: ghcr.io/alexta69/metube

  tag: '2025.12.05'

  userId: 911
  groupId: 911

  volumes:
    config:
      enabled: false

      size: 5G

    media:
      enabled: true

      external: true
