apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: dragonfly-core-secret

spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: corevault-rootsecrets
      kind: ClusterSecretStore

  selector:
    secret:
      name: dragonfly-core-password

  data:
    - match:
        secretKey: 'password'
        remoteRef:
          remoteKey: 'Storage/DragonFly/CoRE/{{ .Values.region }}/{{ .Values.datacenter }}/{{ .Values.cluster.name }}/Creds'
          property: 'Password'
    {{- if and (eq .Values.region "yvr") (eq .Values.datacenter "home1") }}
    - match:
        secretKey: 'password'
        remoteRef:
          remoteKey: 'Storage/DragonFly/CoRE/Creds'
          property: 'Password'
    {{- end }}
