{{- if .Values.kafka.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: '{{ .Release.Name }}-kafka-oidc'
  namespace: '{{ .Release.Namespace }}'
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  refreshInterval: '5m'
  secretStoreRef:
    name: {{ .Values.kafka.secretStoreName | squote }}
    kind: 'ClusterSecretStore'
  target:
    name: {{ .Values.kafka.credentialsSecretName | squote }}
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
    template:
      engineVersion: 'v2'
      data:
        kafka.properties: |-
          org.opennms.activemq.broker.disable=true
          org.opennms.core.ipc.strategy=kafka
          org.opennms.core.ipc.sink.initialSleepTime=60000
          org.opennms.core.ipc.kafka.bootstrap.servers={{ required "kafka.bootstrapServers is required when Kafka is enabled" .Values.kafka.bootstrapServers }}
          org.opennms.core.ipc.kafka.security.protocol=SASL_SSL
          org.opennms.core.ipc.kafka.sasl.mechanism=OAUTHBEARER
          org.opennms.core.ipc.kafka.sasl.login.callback.handler.class=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler
          org.opennms.core.ipc.kafka.sasl.oauthbearer.token.endpoint.url=https://idp.mylogin.space/application/o/token/
          org.opennms.core.ipc.kafka.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required clientId="{{`{{ .client_id }}`}}" clientSecret="{{`{{ .client_secret }}`}}" scope="openid profile email";
  data:
    - secretKey: 'client_id'
      remoteRef:
        key: {{ .Values.kafka.remoteKey | squote }}
        property: 'client_id'
    - secretKey: 'client_secret'
      remoteRef:
        key: {{ .Values.kafka.remoteKey | squote }}
        property: 'client_secret'
{{- end }}
