{{- if .Values.kafka.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: '{{ .Release.Name }}-kafka-oidc'
  namespace: '{{ .Release.Namespace }}'
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: {{ .Values.kafka.secretStoreName | squote }}
    kind: 'ClusterSecretStore'
  target:
    name: {{ .Values.kafka.credentialsSecretName | squote }}
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
  data:
    - secretKey: 'client_id'
      remoteRef:
        key: {{ .Values.kafka.remoteKey | squote }}
        property: 'client_id'
    - secretKey: 'client_secret'
      remoteRef:
        key: {{ .Values.kafka.remoteKey | squote }}
        property: 'client_secret'
{{- end }}
