{{- if .Values.minion.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: '{{ .Release.Name }}-minion-kafka'
  namespace: '{{ .Release.Namespace }}'
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  refreshInterval: '5m'
  secretStoreRef:
    name: {{ required "minion.secretStoreName is required" .Values.minion.secretStoreName | squote }}
    kind: 'ClusterSecretStore'
  target:
    name: {{ required "minion.kafka.credentialsSecretName is required" .Values.minion.kafka.credentialsSecretName | squote }}
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
    template:
      engineVersion: 'v2'
      data:
        minion-config.yaml: |-
          http-url: {{ .Values.minion.coreUrl | squote }}
          id: {{ .Values.minion.id | squote }}
          location: {{ .Values.minion.location | squote }}
          {{- if .Values.minion.traps.enabled }}
          netmgt:
            traps:
              trapd.listen.interface: {{ .Values.minion.traps.listenInterface | squote }}
              trapd.listen.port: {{ .Values.minion.traps.listenPort }}
          {{- end }}
          org.opennms.instance.id: {{ .Values.kafka.instanceId | squote }}
          ipc:
            kafka:
              bootstrap.servers: {{ .Values.minion.kafka.bootstrapServers | squote }}
              security.protocol: 'SASL_SSL'
              ssl.truststore.type: 'PEM'
              ssl.truststore.location: '/etc/ssl/certs/ca-bundle.crt'
              ssl.endpoint.identification.algorithm: 'https'
              sasl.mechanism: 'OAUTHBEARER'
              sasl.login.callback.handler.class: 'org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler'
              sasl.oauthbearer.token.endpoint.url: 'https://idp.mylogin.space/application/o/token/'
              sasl.jaas.config: 'org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required clientId="{{`{{ .client_id }}`}}" clientSecret="{{`{{ .client_secret }}`}}" scope="openid profile email";'
            rpc:
              kafka:
                bootstrap.servers: {{ .Values.minion.kafka.bootstrapServers | squote }}
                security.protocol: 'SASL_SSL'
                ssl.truststore.type: 'PEM'
                ssl.truststore.location: '/etc/ssl/certs/ca-bundle.crt'
                ssl.endpoint.identification.algorithm: 'https'
                sasl.mechanism: 'OAUTHBEARER'
                sasl.login.callback.handler.class: 'org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler'
                sasl.oauthbearer.token.endpoint.url: 'https://idp.mylogin.space/application/o/token/'
                sasl.jaas.config: 'org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required clientId="{{`{{ .client_id }}`}}" clientSecret="{{`{{ .client_secret }}`}}" scope="openid profile email";'
            sink:
              kafka:
                bootstrap.servers: {{ .Values.minion.kafka.bootstrapServers | squote }}
                security.protocol: 'SASL_SSL'
                ssl.truststore.type: 'PEM'
                ssl.truststore.location: '/etc/ssl/certs/ca-bundle.crt'
                ssl.endpoint.identification.algorithm: 'https'
                sasl.mechanism: 'OAUTHBEARER'
                sasl.login.callback.handler.class: 'org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler'
                sasl.oauthbearer.token.endpoint.url: 'https://idp.mylogin.space/application/o/token/'
                sasl.jaas.config: 'org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required clientId="{{`{{ .client_id }}`}}" clientSecret="{{`{{ .client_secret }}`}}" scope="openid profile email";'
            twin:
              kafka:
                bootstrap.servers: {{ .Values.minion.kafka.bootstrapServers | squote }}
                security.protocol: 'SASL_SSL'
                ssl.truststore.type: 'PEM'
                ssl.truststore.location: '/etc/ssl/certs/ca-bundle.crt'
                ssl.endpoint.identification.algorithm: 'https'
                sasl.mechanism: 'OAUTHBEARER'
                sasl.login.callback.handler.class: 'org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler'
                sasl.oauthbearer.token.endpoint.url: 'https://idp.mylogin.space/application/o/token/'
                sasl.jaas.config: 'org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required clientId="{{`{{ .client_id }}`}}" clientSecret="{{`{{ .client_secret }}`}}" scope="openid profile email";'
        disable-jms.boot: |-
          !minion-jms
          !opennms-core-ipc-jms
  data:
    - secretKey: 'client_id'
      remoteRef:
        key: {{ required "minion.kafka.remoteKey is required" .Values.minion.kafka.remoteKey | squote }}
        property: 'client_id'
    - secretKey: 'client_secret'
      remoteRef:
        key: {{ .Values.minion.kafka.remoteKey | squote }}
        property: 'client_secret'
{{- end }}
