{{- if .Values.minion.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: '{{ .Release.Name }}-minion-credentials'
  namespace: '{{ .Release.Namespace }}'
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  refreshInterval: '5m'
  secretStoreRef:
    name: {{ required "minion.secretStoreName is required" .Values.minion.secretStoreName | squote }}
    kind: 'ClusterSecretStore'
  target:
    name: {{ required "minion.credentialsSecretName is required" .Values.minion.credentialsSecretName | squote }}
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
    template:
      engineVersion: 'v2'
      data:
        org.opennms.core.ipc.kafka.cfg: |-
          bootstrap.servers={{ required "minion.kafka.bootstrapServers is required" .Values.minion.kafka.bootstrapServers }}
          security.protocol=SASL_SSL
          sasl.mechanism=OAUTHBEARER
          sasl.login.callback.handler.class=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler
          sasl.oauthbearer.token.endpoint.url=https://idp.mylogin.space/application/o/token/
          sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required clientId="{{`{{ .client_id }}`}}" clientSecret="{{`{{ .client_secret }}`}}" scope="openid profile email";
        org.opennms.core.ipc.rpc.kafka.cfg: |-
          bootstrap.servers={{ required "minion.kafka.bootstrapServers is required" .Values.minion.kafka.bootstrapServers }}
          security.protocol=SASL_SSL
          sasl.mechanism=OAUTHBEARER
          sasl.login.callback.handler.class=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler
          sasl.oauthbearer.token.endpoint.url=https://idp.mylogin.space/application/o/token/
          sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required clientId="{{`{{ .client_id }}`}}" clientSecret="{{`{{ .client_secret }}`}}" scope="openid profile email";
        org.opennms.core.ipc.sink.kafka.cfg: |-
          bootstrap.servers={{ required "minion.kafka.bootstrapServers is required" .Values.minion.kafka.bootstrapServers }}
          security.protocol=SASL_SSL
          sasl.mechanism=OAUTHBEARER
          sasl.login.callback.handler.class=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler
          sasl.oauthbearer.token.endpoint.url=https://idp.mylogin.space/application/o/token/
          sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required clientId="{{`{{ .client_id }}`}}" clientSecret="{{`{{ .client_secret }}`}}" scope="openid profile email";
        org.opennms.core.ipc.twin.kafka.cfg: |-
          bootstrap.servers={{ required "minion.kafka.bootstrapServers is required" .Values.minion.kafka.bootstrapServers }}
          security.protocol=SASL_SSL
          sasl.mechanism=OAUTHBEARER
          sasl.login.callback.handler.class=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler
          sasl.oauthbearer.token.endpoint.url=https://idp.mylogin.space/application/o/token/
          sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required clientId="{{`{{ .client_id }}`}}" clientSecret="{{`{{ .client_secret }}`}}" scope="openid profile email";
  data:
    - secretKey: 'username'
      remoteRef:
        key: {{ required "minion.remoteKey is required" .Values.minion.remoteKey | squote }}
        property: 'username'
    - secretKey: 'password'
      remoteRef:
        key: {{ .Values.minion.remoteKey | squote }}
        property: 'password'
    - secretKey: 'client_id'
      remoteRef:
        key: {{ required "minion.kafka.remoteKey is required" .Values.minion.kafka.remoteKey | squote }}
        property: 'client_id'
    - secretKey: 'client_secret'
      remoteRef:
        key: {{ .Values.minion.kafka.remoteKey | squote }}
        property: 'client_secret'
{{- end }}
