apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}'
  labels:
    app.kubernetes.io/name: 'opennms'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
spec:
  type: 'ClusterIP'
  selector:
    app.kubernetes.io/name: 'opennms'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
  ports:
    - name: 'http'
      port: 80
      targetPort: 'http'
      protocol: 'TCP'
