apiVersion: v2
version: 1.0.0
name: db-psql

dependencies:
  - name: common
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts/

  - name: pgadmin4
    version: 1.65.0
    repository: https://helm.runix.net/
