env: 'prod'
datacenter: 'example-dc'
region: 'example-region'

cluster:
  name: 'example-cluster'
  domain: 'cluster.local'

global:
  timezone: 'America/Vancouver'
  createDefaultServiceAccount: false

image:
  repository: 'docker.io/opennms/horizon'
  tag: '36.0.3'
  digest: 'sha256:d5ab66e2f5b24a799b8d15a6d8cc07d2c0b7a0d91bbef67828c37876e32602fe'
  pullPolicy: 'IfNotPresent'

postgresql:
  host: ''
  port: 5432
  database: 'opennms-insight'
  username: 'opennms-insight'
  credentialsSecretName: 'opennms-creds'
  adminSecretName: ''
  adminSecretSourceNamespace: 'core-prod'
  secretSync:
    enabled: true
    storeName: 'mainvault-core'
    remoteKeyPrefix: 'Network/Insight/example-cluster'
  providers:
    crossplane: 'psql-main'
    terraform: 'psql'

ldap:
  enabled: true
  baseDn: 'dc=ldap,dc=mylogin,dc=space'
  userSearchBase: 'ou=users'
  userSearchFilter: '(cn={0})'
  groupSearchBase: 'ou=groups'
  groupSearchFilter: '(member={0})'

storage:
  config:
    size: '2Gi'
  data:
    size: '100Gi'

timeseries:
  enabled: false
  writeUrl: ''
  readUrl: ''
  plugin:
    url: 'https://repo1.maven.org/maven2/org/opennms/plugins/timeseries/org.opennms.plugins.timeseries.prometheus.remotewrite.assembly.kar/2.1.0/org.opennms.plugins.timeseries.prometheus.remotewrite.assembly.kar-2.1.0.kar'
    sha256: 'e7a6d0bf07487ebac00244c9002c6b0410d48c0ff27c92e475dd24ee11826686'
    resources:
      requests:
        cpu: '10m'
        memory: '32Mi'
      limits:
        cpu: '100m'
        memory: '128Mi'
  maxConcurrentHttpConnections: 100
  writeTimeoutInMs: 5000
  readTimeoutInMs: 5000
  metricCacheSize: 1000
  externalTagsCacheSize: 1000
  maxSeriesLookback: 7776000

migration:
  replaceStatefulSet: false

resources:
  requests:
    cpu: '1'
    memory: '4Gi'
  limits:
    cpu: '2'
    memory: '8Gi'

gateway:
  hostname: 'insight.mylogin.space'
  name: 'main-gw'
  namespace: 'core-prod'
  sectionName: 'https-myloginspace'

authentik:
  autoconfigure: true
  proxyAuth:
    enabled: true
    userHeader: 'X-Authentik-Username'
    authoritiesHeader: 'X-OpenNMS-Roles'
    authorities:
      - 'ROLE_USER'
      - 'ROLE_ADMIN'
      - 'ROLE_REST'
      - 'ROLE_PROVISION'
    failOnError: false
  application:
    displayName: 'OpenNMS'
    externalHost: 'https://insight.mylogin.space'
    group: 'Infrastructure'
  accessGroups:
    - 'Server Admins'
  route:
    enabled: true
    backend:
      name: 'aaa-myloginspace-proxy'
      namespace: 'core-prod'
      port: 80

networkPolicy:
  enabled: true
  gateway:
    namespace: 'kube-system'
    podLabels:
      app.kubernetes.io/name: 'envoy'
      gateway.envoyproxy.io/owning-gateway-name: 'main-gw'
      gateway.envoyproxy.io/owning-gateway-namespace: 'core-prod'
