{{- range $installerIndex, $installer := .Values.installers }}
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ $installer.name }}

spec:
  {{- with $installer.contentType }}
  contentType: {{ . }}
  {{- end }}
  {{- with $installer.preallocation }}
  preallocation: {{ . }}
  {{- end }}
  {{- with $installer.priorityClassName }}
  priorityClassName: {{ . }}
  {{- end }}
  pvc:
    accessModes: {{ toYaml (default (list "ReadWriteOnce") $installer.accessModes) | nindent 6 }}
    {{- with $installer.storageClassName }}
    storageClassName: {{ . | quote }}
    {{- end }}
    {{- with $installer.volumeMode }}
    volumeMode: {{ . }}
    {{- end }}
    resources:
      requests:
        storage: {{ $installer.size }}
  {{- if $installer.sourceRef }}
  sourceRef: {{ toYaml $installer.sourceRef | nindent 4 }}
  {{- else if $installer.source }}
  source: {{ toYaml $installer.source | nindent 4 }}
  {{- else }}
  source:
    http:
      url: {{ $installer.url }}
      {{- with $installer.secretRef }}
      secretRef: {{ . }}
      {{- end }}
      {{- with $installer.certConfigMap }}
      certConfigMap: {{ . }}
      {{- end }}
      {{- with $installer.extraHeaders }}
      extraHeaders: {{ toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
---
{{- end }}
