apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan666-srv7
  annotations:
    k8s.v1.cni.cncf.io/resourceName: mellanox.com/mlx4_cx3_netdevice
spec:
  config: |
    {
      "cniVersion": "1.0.0",
      "name": "vlan666",
      "type": "sriov",
      "spoofchk": "off",
      "mtu": 9000,
      "vlan": 666,
      "ipam": {}
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan666-infra1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_xxv710
spec:
  config: |
    {
      "cniVersion": "1.0.0",
      "name": "vlan666",
      "type": "sriov",
      "spoofchk": "off",
      "trust": "on",
      "mtu": 9000,
      "vlan": 666,
      "ipam": {}
    }