apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-vlan953-knt-privwan
spec:
  config: |
    {
      "cniVersion": "1.0.0",
      "name": "sriov-vlan953-knt-privwan",
      "type": "host-device",
      "device": "enp5s0f1np1v0",
      "ipam": {}
    }