---
{{ $networks := dict }}
{{- range $networkIndex, $network := .Values.networks }}
{{- $nicType := (default "sriov" $network.type) }}
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: '{{ $network.name }}'

  {{- if eq $nicType "sriov" }}
  {{ $_ := set $networks $network.name (
      merge
        (dict "type" $nicType)
        (deepCopy $network)
      ) 
  }}
  annotations:
    k8s.v1.cni.cncf.io/resourceName: '{{ $network.sriov.device }}'
  {{- end }}
spec:
  config: |
    {
      "cniVersion": "1.0.0",
      {{- if $network.mtu }}
      "mtu": {{ $network.mtu }},
      {{- end }}

      {{- with $network.vlan }}
      "vlan": {{ . }},
      {{- if eq $nicType "bridge" }}
      "preserveDefaultVlan": false,
      {{- end }}
      {{- end }}

      {{- if eq $nicType "bridge" }}
      "bridge": "{{ $network.bridge }}",
      {{- end }}
      
      "type": "{{ $nicType }}"
    }
---
{{ end }}
{{- range $vmIndex, $vm := .Values.vms }}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ $vm.name }}
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: {{ $vm.name }}
    spec:
      networks:
        {{- if and $vm.podNetwork $vm.podNetwork.enabled }}
        - name: default
          pod: {} # Stock pod network
        {{- end }}

        {{- range $networkIndex, $vmNetwork := $vm.networks }}
        {{- $network := index $networks $vmNetwork.name }}
        - name: {{ $vmNetwork.name }}
          multus:
            networkName: {{ $vmNetwork.name }}
        {{- end }}

      priorityClassName: system-cluster-critical

      domain:
        cpu:
          cores: 2
          threads: 4
          sockets: 1
        machine:
          type: q35
        features:
          smm:
            enabled: true
        {{- if and $vm.boot $vm.boot.secureBoot }}
        firmware:
          bootloader:
            efi:
              secureBoot: true
        {{- end }}
        devices:
          autoattachPodInterface: true
          {{- if and $vm.tpm $vm.tpm.enabled }}
          tpm: {}
          {{- end }}

          disks:
            {{- if $vm.installing }}
            - name: installer
              bootOrder: 1
              cdrom:
                bus: sata
            {{- end }}

            - name: data-disk
              bootOrder: {{ if $vm.installing }}2{{ else }}1{{ end }}
              disk:
                bus: virtio

          interfaces:
            {{- range $networkIndex, $vmNetwork := $vm.networks }}
            {{- $network := index $networks $vmNetwork.name }}
            - name: {{ $vmNetwork.name }}
              {{ default "sriov" $network.type }}: {}
              {{- with $vmNetwork.macAddress }}
              macAddress: '{{ . }}'
              {{- end }}
            {{- end }}


            {{- if and $vm.podNetwork  $vm.podNetwork.enabled }}
            - name: default
              masquerade: {}
              {{- if $vm.ports }}
              ports:
                {{- range $portIndex, $port := $vm.ports }}
                - name: {{ $port.name }}
                  port: {{ $port.port }}
                  {{- with $port.protocol }}
                  protocol: {{ . }}
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}

        resources:
          requests:
            memory: 4Gi
            cpu: '100m'
          limits:
            memory: 4Gi
            cpu: 4
      volumes:
        {{- if $vm.installing }}
        - name: installer
          dataVolume:
            name: {{ $vm.installer }}
        {{ end }}
        - dataVolume:
            name: {{ $vm.name }}
          name: data-disk

  dataVolumeTemplates:
    - metadata:
        name: {{ $vm.name }}
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
        source:
          blank: {}
---
{{- end }}