---
{{ $networks := dict }}
{{- range $networkIndex, $network := .Values.networks }}
{{- $nicType := (default "sriov" $network.type) }}
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: '{{ $network.name }}'

  {{- if eq $nicType "sriov" }}
  {{ $_ := set $networks $network.name (
      merge
        (dict "type" $nicType)
        (deepCopy $network)
      ) 
  }}
  annotations:
    k8s.v1.cni.cncf.io/resourceName: '{{ $network.sriov.device }}'
  {{- end }}
spec:
  config: |
    {
      "cniVersion": "1.0.0",
      {{- if $network.mtu }}
      "mtu": {{ $network.mtu }},
      {{- end }}

      {{- with $network.vlan }}
      "vlan": {{ . }},
      {{- if eq $nicType "bridge" }}
      "preserveDefaultVlan": false,
      {{- end }}
      {{- end }}

      {{- if eq $nicType "bridge" }}
      "bridge": "{{ $network.bridge }}",
      {{- end }}
      
      "type": "{{ $nicType }}"
    }
---
{{ end }}
{{- range $vmIndex, $vm := .Values.vms }}
{{- $disk := default (dict) $vm.disk }}
{{- $diskEnabled := or (not (hasKey $disk "enabled")) $disk.enabled }}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ $vm.name }}
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: {{ $vm.name }}
    spec:
      networks:
        {{- if and $vm.podNetwork $vm.podNetwork.enabled }}
        - name: default
          pod: {} # Stock pod network
        {{- end }}

        {{- range $networkIndex, $vmNetwork := $vm.networks }}
        {{- $network := index $networks $vmNetwork.name }}
        - name: {{ $vmNetwork.name }}
          multus:
            networkName: {{ $vmNetwork.name }}
        {{- end }}

      priorityClassName: system-cluster-critical

      domain:
        cpu:
          cores: 2
          threads: 2
          sockets: 1
          model: host-passthrough
        machine:
          type: q35
        features:
          smm:
            enabled: true
        {{- if and $vm.boot $vm.boot.secureBoot }}
        firmware:
          bootloader:
            efi:
              secureBoot: true
        {{- end }}
        devices:
          autoattachPodInterface: {{ if and $vm.podNetwork $vm.podNetwork.enabled }}true{{ else }}false{{ end }}
          {{- if and $vm.tpm $vm.tpm.enabled }}
          tpm: {}
          {{- end }}

          disks:
            {{- if $vm.installing }}
            - name: installer
              bootOrder: 1
              cdrom:
                bus: sata
            {{- end }}

            {{- if $diskEnabled }}
            - name: data-disk
              bootOrder: {{ if $vm.installing }}2{{ else }}1{{ end }}
              disk:
                bus: {{ default "virtio" $disk.bus }}
            {{- end }}

          interfaces:
            {{- range $networkIndex, $vmNetwork := $vm.networks }}
            {{- $network := index $networks $vmNetwork.name }}
            - name: {{ $vmNetwork.name }}
              {{ default "sriov" $network.type }}: {}
              {{- with $vmNetwork.macAddress }}
              macAddress: '{{ . }}'
              {{- end }}
            {{- end }}


            {{- if and $vm.podNetwork  $vm.podNetwork.enabled }}
            - name: default
              masquerade: {}
              {{- with $vm.podNetwork.macAddress }}
              macAddress: {{ . | quote }}
              {{- end }}
              {{- if $vm.ports }}
              ports:
                {{- range $portIndex, $port := $vm.ports }}
                - name: {{ $port.name }}
                  port: {{ $port.port }}
                  {{- with $port.protocol }}
                  protocol: {{ . }}
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}

        resources:
          requests:
            memory: 4Gi
            cpu: '100m'
          limits:
            memory: 4Gi
            cpu: 4
      {{- if or $vm.installing $diskEnabled }}
      volumes:
        {{- if $vm.installing }}
        - name: installer
          dataVolume:
            name: {{ $vm.installer }}
        {{ end }}
        {{- if $diskEnabled }}
        - dataVolume:
            name: {{ $vm.name }}
          name: data-disk
        {{- end }}
      {{- end }}

  {{- if $diskEnabled }}
  dataVolumeTemplates:
    - metadata:
        name: {{ $vm.name }}
      spec:
        {{- with $disk.contentType }}
        contentType: {{ . }}
        {{- end }}
        {{- with $disk.preallocation }}
        preallocation: {{ . }}
        {{- end }}
        {{- with $disk.priorityClassName }}
        priorityClassName: {{ . }}
        {{- end }}
        pvc:
          accessModes: {{ toYaml (default (list "ReadWriteOnce") $disk.accessModes) | nindent 12 }}
          {{- with $disk.storageClassName }}
          storageClassName: {{ . | quote }}
          {{- end }}
          {{- with $disk.volumeMode }}
          volumeMode: {{ . }}
          {{- end }}
          resources:
            requests:
              storage: {{ default "20Gi" $disk.size }}
        {{- if $disk.sourceRef }}
        sourceRef: {{ toYaml $disk.sourceRef | nindent 10 }}
        {{- else if $disk.source }}
        source: {{ toYaml $disk.source | nindent 10 }}
        {{- else if $disk.url }}
        source:
          http:
            url: {{ $disk.url }}
            {{- with $disk.secretRef }}
            secretRef: {{ . }}
            {{- end }}
            {{- with $disk.certConfigMap }}
            certConfigMap: {{ . }}
            {{- end }}
            {{- with $disk.extraHeaders }}
            extraHeaders: {{ toYaml . | nindent 14 }}
            {{- end }}
        {{- else }}
        source:
          blank: {}
        {{- end }}
  {{- end }}
---
{{- end }}
