apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Release.Name }}'
spec:
  resources:
    requests:
      storage: '{{ .Values.persistence.size }}'
  volumeMode: Filesystem
  storageClassName: longhorn-rwx
  accessModes:
{{- toYaml .Values.persistence.accessModes | nindent 4 }}
