apiVersion: resolvemy.host/v1alpha1
kind: ClusterNode
metadata:
  name: srv1.dc1.yxl.resolvemy.host

  namespace: core-prod

  labels:
    argocd.argoproj.io/instance: dc1-k3s-node1-ops-cluster

spec:
  name: core-dc1-talos

  description: Main cluster

  type: controlplane

  danger:
    warningdonotdounlessyouknowwhatyouaredoing:
      wipeOnReboot: false

  clusterRef:
    group: resolvemy.host
    kind: Cluster
    name: core-dc1-talos
    namespace: core-prod

  tenantRef:
    group: mylogin.space
    kind: Tenant
    name: core.mylogin.space
    namespace: core-prod

  environment: prod

  bgp:
    instances:
      - asn: 64512
        name: wan-gw
        type: cilium
        peers:
          - address: 172.31.241.93
            localAddress: 172.31.241.94
            asn: 64567
            name: vlan123.spine-sw1.dc1.yxl.resolvemy.host#

  nics:
    - macAddress: b8:ca:3a:6e:f3:b8
      rings:
        rx: 2048
        tx: 2048

#   storage:
#     longhornDisks:
#       - maxSize: 500GB
#         selector:
#           wwid: naa.5000cca072403d08

  networks:
    - macAddress: b8:ca:3a:6e:f3:b8
      bridge: false
      model: new
      type: link
      addresses:
        - 172.31.241.94/30

      routes:
        - network: 0.0.0.0/0
          gateway: 172.31.241.93
          metric: 1024

      mtu: 3000

      routing:
        ospf:
          enabled: false

      static: true
      dns:
        - 1.1.1.1

  overrides:
    talos:
      extensions:
        system:
          - intel-ucode

    kernel:
      parameters:
        - name: intel_iommu
          value: 'on'

        - name: iommu
          value: pt

        - name: pcie_aspm
          value: 'off'

        - name: nvme_core.default_ps_max_latency_us
          value: '0'

        - name: numa_balancing
          value: enable