apiVersion: resolvemy.host/v1alpha1
kind: ClusterNode
metadata:
  name: srv7.dc1.yxl.resolvemy.host

  namespace: core-prod

  labels:
    argocd.argoproj.io/instance: dc1-k3s-node1-ops-cluster

spec:
  name: core-dc1-talos

  description: Main cluster

  type: controlplane

  danger:
    warningdonotdounlessyouknowwhatyouaredoing:
      wipeOnReboot: false

  clusterRef:
    group: resolvemy.host
    kind: Cluster
    name: core-dc1-talos
    namespace: core-prod

  tenantRef:
    group: mylogin.space
    kind: Tenant
    name: core.mylogin.space
    namespace: core-prod

  environment: prod

  bgp:
    instances:
      - asn: 64512
        name: wan-gw
        type: cilium
        peers:
          - address: 172.31.241.69
            localAddress: 172.31.241.70
            asn: 64567
            name: vlan2070.spine-sw1.dc1.yxl.resolvemy.host

#   nics:
#     - macAddress: f0:4d:a2:03:cd:ea
#       rings:
#         rx: 4096

  storage:
    longhornDisks:
      - maxSize: 500GB
        selector:
          wwid: naa.5000cca01dbb21d4

  networks:
    - macAddress: b8:ca:3a:60:00:28
      bridge: false
      model: new
      type: link
      addresses:
        - 172.31.241.70/30

      routes:
        - network: 0.0.0.0/0
          gateway: 172.31.241.69
          metric: 1024

      mtu: 3000

      routing:
        ospf:
          enabled: false

      static: true
      dns:
        - 1.1.1.1

  overrides:
    cni:
      cilium:
        configOverrides:
          devices: eno1
          direct-routing-device: eno1
    pci:
      rebinds:
        - description: cx3-vf0
          driver: vfio-pci
          id: '0000:04:00.1'
        - description: cx3-vf1
          driver: vfio-pci
          id: '0000:04:00.2'
        - description: cx3-vf2
          driver: vfio-pci
          id: '0000:04:00.3'
        - description: cx3-vf3
          driver: vfio-pci
          id: '0000:04:00.4'
        - description: cx3-vf4
          driver: vfio-pci
          id: '0000:04:00.5'
        - description: cx3-vf5
          driver: vfio-pci
          id: '0000:04:00.6'
        - description: cx3-vf6
          driver: vfio-pci
          id: '0000:04:00.7'
        - description: cx3-vf7
          driver: vfio-pci
          id: '0000:04:01.0'

    talos:
      extensions:
        system:
          - intel-ucode
          - nfsd
          - nfs-utils

    kernel:
      parameters:
        - name: intel_iommu
          value: 'on'

        - name: iommu
          value: pt

        - name: pcie_aspm
          value: 'off'

        - name: numa_balancing
          value: enable

        - name: mlx4_core.debug_level
          value: '8'
        - name: mlx4_core.enable_qos
          value: '1'
        - name: mlx4_core.port_type_array
          value: 2,2
        - name: mlx4_core.num_vfs
          value: 0,32,0
        - name: mlx4_core.probe_vf
          value: 0,24,0
        - name: mlx4_core.log_num_mgm_entry_size
          value: '-1'
        - name: mlx4_core.enable_4k_uar
          value: '1'
        - name: mlx4_en.pfctx
          value: '0x08'
        - name: mlx4_en.pfcrx
          value: '0x08'