apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: mysql-core

spec:
  name: MySQL

  username: mysql

  s3:
    enabled: true
    createUserBucket: false
    createBuckets: false
    buckets:
      - 'mysql-backups'

  groups:
    - LDAPService

  writeConnectionSecretToRef:
    name: mysql-core
