{{- if (index .Values "gitea-mirror").enabled }}
{{- range $name, $key := dict "auth" "BETTER_AUTH_SECRET" "encryption" "ENCRYPTION_SECRET" }}
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: 'gitea-mirror-{{ $name }}'
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  length: 64
  digits: 12
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 'gitea-mirror-{{ $name }}'
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshPolicy: 'CreatedOnce'
  target:
    name: 'gitea-mirror-{{ $name }}'
    template:
      engineVersion: 'v2'
      data:
        {{ $key }}: '{{ `{{ .password }}` }}'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: 'gitea-mirror-{{ $name }}'
{{- end }}
{{- end }}
