tenant:
  name: example-tenant

global:
  timezone: 'America/Vancouver'

pubgateway:
  name: main-gw
  namespace: core-prod
  sectionName: https-myloginspace

authentik:
  autoconfigure: true

  application:
    displayName: 'Stash'
    externalHost: 'https://accessmyporn.download'
    group: 'Media'

  applications:
    jellystat:
      enabled: true
      displayName: 'Jellystat'
      externalHost: 'https://jellystat.mylogin.space'
      group: 'Media'

  accessGroups:
    - 'Private Stash'

  route:
    enabled: true

    backend:
      name: 'aaa-myloginspace-proxy'
      namespace: 'core-prod'
      port: 80

jellyfin:
  enabled: true

  image: jellyfin/jellyfin

  tag: '10'

  health:
    enabled: true
    path: '/health'

    startup:
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 60

    readiness:
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6

    liveness:
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3

  volumes:
    config:
      enabled: true

    media:
      enabled: true

      external: true

    transcode:
      enabled: true
      size: '20G'

  monitoring:
    enabled: true
    interval: '1m'

stash:
  enabled: true

  image: ghcr.io/hotio/stash

  tag: 'release'

  health:
    enabled: true
    path: '/healthz'

    startup:
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 60

    readiness:
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6

    liveness:
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3

  userId: 911
  groupId: 911

  volumes:
    config:
      enabled: true

    media:
      enabled: true

      external: true

jellystat:
  enabled: true

  image: ghcr.io/cyfershepard/jellystat
  tag: '1.1.11'

  health:
    enabled: true
    path: '/auth/isConfigured'

    startup:
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 60

    readiness:
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6

    liveness:
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3

  volumes:
    backup:
      enabled: true
      size: '5G'
