tenant:
  name: example-tenant

pubgateway:
  name: main-gw
  namespace: core-prod
  sectionName: https-myloginspace

authentik:
  autoconfigure: true

  application:
    displayName: 'Stash'
    externalHost: 'https://accessmyporn.download'
    group: 'Media'

  accessGroups:
    - 'Private Stash'

  route:
    enabled: true

    backend:
      name: 'aaa-myloginspace-proxy'
      namespace: 'core-prod'
      port: 80

jellyfin:
  enabled: true

  image: jellyfin/jellyfin

  tag: '10'

  volumes:
    config:
      enabled: true

    media:
      enabled: true

      external: true

    transcode:
      enabled: true
      size: '20G'

  monitoring:
    enabled: true
    interval: '1m'

stash:
  enabled: true

  image: ghcr.io/hotio/stash

  tag: 'release'

  nodeSelector:
    kubernetes.io/hostname: 'srv1'

  userId: 911
  groupId: 911

  volumes:
    config:
      enabled: true

    media:
      enabled: true

      external: true
