apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/refs/heads/main/manifests/dynamic-networks-controller.yaml
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/sriov-cni/refs/heads/master/images/sriov-cni-daemonset.yaml
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/sriov-network-device-plugin/refs/heads/master/deployments/sriovdp-daemonset.yaml


patches:
  - target:
      kind: CustomResourceDefinition
      name: network-attachment-definitions.k8s.cni.cncf.io 
      labelSelector: 'app.kubernetes.io/name=prometheus-smartctl-exporter'

    patch: |
      $patch: delete
      kind: CustomResourceDefinition
      metadata:
        name: DOES NOT MATTER