{{- if .Values.forgejo.enabled }}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: 'forgejo-admin'
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  length: 32
  digits: 5
  symbols: 5
  symbolCharacters: '-_$'
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 'forgejo-admin'
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshPolicy: 'CreatedOnce'
  target:
    name: 'forgejo-admin'
    template:
      engineVersion: 'v2'
      data:
        username: 'forgejo_admin'
        password: '{{ `{{ .password }}` }}'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: 'forgejo-admin'
{{- end }}
