{{- if .Values.forgejo.enabled }}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: 'forgejo-oidc'
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  length: 64
  digits: 12
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 'forgejo-oidc'
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshPolicy: 'CreatedOnce'
  target:
    name: 'forgejo-oidc'
    template:
      engineVersion: 'v2'
      data:
        key: 'forgejo-{{ .Values.cluster.name }}'
        secret: '{{ `{{ .password }}` }}'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: 'forgejo-oidc'
{{- end }}
