{{- if .Values.forgejo.enabled }}
apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: 'forgejo-user'
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  name: 'Forgejo {{ .Values.cluster.name }}'
  username: 'forgejo-{{ .Values.cluster.name }}'
  psql:
    enabled: true
    createUserDatabase: true
    crossplane:
      terraformProvider: 'psql-{{ .Values.datacenter }}-{{ .Values.region }}'
      crossplaneProvider: 'psql-{{ .Values.datacenter }}-{{ .Values.region }}'
  {{- if eq .Values.region "yxl" }}
  s3:
    enabled: true
    region: 'us-east-1'
    createUserBucket: false
    createBuckets: true
    buckets:
      - 'forgejo-{{ .Values.cluster.name }}'
    createServiceAccount: true
    crossplane:
      terraformProvider: 's3-{{ .Values.region }}-{{ .Values.datacenter }}-core'
      crossplaneProvider: 's3-{{ .Values.region }}-{{ .Values.datacenter }}-core'
    writeServiceAccountCredentialsSecretRef:
      namespace: '{{ .Release.Namespace }}'
      name: 'forgejo-s3'
  {{- end }}
  writeConnectionSecretToRef:
    name: 'forgejo-user'
{{- end }}
