{{- if .Values.forgejo.enabled }}
apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: 'forgejo-user'
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  name: 'Forgejo {{ .Values.cluster.name }}'
  username: 'forgejo-{{ .Values.cluster.name }}'
  psql:
    enabled: true
    createUserDatabase: true
    crossplane:
      terraformProvider: 'psql-{{ .Values.datacenter }}-{{ .Values.region }}'
      crossplaneProvider: 'psql-{{ .Values.datacenter }}-{{ .Values.region }}'
  writeConnectionSecretToRef:
    name: 'forgejo-user'
{{- end }}
