env: staging

cluster:
  name: k8s
  domain: cluster.local

peers: []

datacenter: dc1

region: yxl

hub: false

gateway:
  name: main-gw
  namespace: core-prod

authentik:
  global:
    podLabels:
      logs: loki-myloginspace

    priorityClassName: tier2-priority

    env:
      - name: AUTHENTIK_WEB__WORKERS
        value: '2'

      - name: AUTHENTIK_WEB__THREADS
        value: '2'

      - name: AUTHENTIK_OUTPOSTS__DISCOVER
        value: 'false'

      - name: AUTHENTIK_POSTGRESQL__DISABLE_SERVER_SIDE_CURSORS
        value: 'false'

      - name: AUTHENTIK_POSTGRESQL__CONN_MAX_AGE
        value: '3600'

      - name: AUTHENTIK_POSTGRESQL__CONN_HEALTH_CHECKS
        value: 'true'

      - name: AUTHENTIK_EMAIL__USERNAME
        valueFrom:
          secretKeyRef:
            name: authentik-core
            key: username

      - name: AUTHENTIK_EMAIL__PASSWORD
        valueFrom:
          secretKeyRef:
            name: authentik-core
            key: password

      - name: AUTHENTIK_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: aaa-authentik-database
            key: SecretKey

      - name: AUTHENTIK_POSTGRESQL__NAME
        valueFrom:
          secretKeyRef:
            name: aaa-authentik-database
            key: Database

      - name: AUTHENTIK_POSTGRESQL__USER
        valueFrom:
          secretKeyRef:
            name: aaa-authentik-database
            key: Username

      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        valueFrom:
          secretKeyRef:
            name: aaa-authentik-database
            key: Password

  authentik:
    email:
      host: mail.mylogin.space
      use_tls: true
      from: tnumovaqly@mail.mylogin.space

    postgresql:
      host: psql-int.mylogin.space

  server:
    replicas: 4

    pdb:
      enabled: true
      minAvailable: 1

    volumeMounts:
      - name: tls-certs
        mountPath: /certs

    volumes:
      - name: tls-certs
        secret:
          secretName: myloginspace-default-certificates

    service:
      annotations: null
      labels:
        wan-mode: public
      servicePortHttpAppProtocol: kubernetes.io/ws
      sessionAffinity: None

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    livenessProbe:
      failureThreshold: 10
      periodSeconds: 30
      timeoutSeconds: 10

    readinessProbe:
      failureThreshold: 10
      successThreshold: 3
      periodSeconds: 30
      timeoutSeconds: 10

    startupProbe:
      failureThreshold: 100
      initialDelaySeconds: 60
      periodSeconds: 30

  worker:
    livenessProbe:
      failureThreshold: 10
      periodSeconds: 30
      timeoutSeconds: 10

    readinessProbe:
      failureThreshold: 10
      periodSeconds: 30
      timeoutSeconds: 10

    startupProbe:
      timeoutSeconds: 6

    volumeMounts:
      - name: tls-certs
        mountPath: /certs

    volumes:
      - name: tls-certs
        secret:
          secretName: myloginspace-default-certificates

  geoip:
    image:
      tag: v6.0.0

  prometheus:
    rules:
      enabled: true

  redis:
    enabled: false

  ldap:
    enabled: true
    replicas: 2

  radius:
    enabled: true
    replicas: 1
    ipAddresses:
      - 10.1.1.18

  proxy:
    enabled: true
    replicas: 1
    ipAddresses:
      - 10.1.1.17

  priorityClassName: ''

openldap:
  enabled: false
  tls:
    secretName: myloginspace-default-certificates
