env: 'prod'

cluster:
  name: 'core-dc1-talos-prod'
  domain: 'cluster.local'

datacenter: 'dc1'
region: 'yxl'

gateway:
  name: 'main-gw'
  namespace: 'core-prod'
  sectionName: 'https-myloginspace'

imageFactory:
  image:
    repository: 'ghcr.io/siderolabs/image-factory'
    tag: 'v1.4.0'
    pullPolicy: 'IfNotPresent'
  cacheSigningKey:
    secretName: 'talos-image-factory-cache-signing-key'
  s3:
    secretName: 'talos-image-factory-s3'
    bucket: 'talos-image-factory'
    region: 'us-east-1'
  artifacts:
    registry: 'forge.core-dc1-talos-prod.dc1.yxl.writemy.codes'
    namespace: 'kjones/actions-lab/imager'
    insecure: false
    components:
      installerBase: 'siderolabs/installer-base'
      installer: 'siderolabs/installer'
      imager: 'siderolabs/imager'
      extensionManifest: 'siderolabs/extensions'
      overlayManifest: 'siderolabs/overlays'
      talosctl: 'siderolabs/talosctl-all'
    schematic:
      namespace: 'kjones/actions-lab'
      repository: 'schematics'
    installer:
      namespace: 'kjones/actions-lab'
      internalRepository: 'talos'
      externalRepository: 'talos'
    talosVersionRecheckInterval: '1m0s'
  resources:
    requests:
      cpu: '100m'
      memory: '256Mi'
    limits:
      cpu: '2'
      memory: '2Gi'
